Repository sulu/sulu, pull requests merged in 2018-10, with the labels that each got.

#4166 Fixed deprecation message for seo twig extension
  composer.json
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
Labels: Bug

#4180 fix datetime formatting for Symfony regression
  UPGRADE.md
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
Labels: Bug

#4184 add conflicting symfony versions
  composer.json
Labels: Bug

#4185 make DatePicker field configurable
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Time.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/DatePicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Time.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Enhancement

#4183 add form node to form schema
  .gitignore
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_expression_param.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_sections.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_without_label.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSeo.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/forms/Collection.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/Role.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
  src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml
  src/Sulu/Component/Content/Metadata/Loader/schema/form-1.0.xsd
Labels: Enhancement

#4187 update references to form xsd
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_expression_param.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_sections.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_without_label.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSeo.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/forms/Collection.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/forms/Media.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/Role.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
  src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml
Labels: Bug

#4188 add missing fields to category form
  src/Sulu/Bundle/CategoryBundle/Resources/config/forms/Category.xml
Labels: Feature

#4186 Add role assignment section
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelect/MultiSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelect/tests/MultiSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/LocalizationStore/LocalizationStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/LocalizationStore/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/LocalizationStore/tests/LocalizationStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/LocalizationStore/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
  src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
  src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/types.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/SecurityBundle/Admin/Helper/SystemLanguageSelect.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Form/fields/RoleAssignments.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Form/tests/fields/RoleAssignments.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignment.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignments.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/index.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/roleAssignment.scss
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/roleAssignments.scss
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/RoleAssignment.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/RoleAssignments.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignment.test.js.snap
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignments.test.js.snap
  src/Sulu/Bundle/SecurityBundle/Resources/js/index.js
Labels: Feature

#4195 fix error when creating male contact
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#4197 fix default value of 0 for SingleSelect
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
Labels: Bug

#4196 use correct Sulu version in Navigation
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
Labels: Feature

#4198 fix font size in matrix items
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/matrix.scss
Labels: Bug

#4200 validate password and roles correctly in user tab
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
Labels: Feature

#4202 fix changing of folders in MediaSelectionOverlay
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
Labels: Bug

#4203 hide pagination if no data is available
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/FolderAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
Labels: Feature

#4204 fix route navigation after deleting a media collection
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/ContentBundle/Resources/js/components/WebspaceSelect/webspaceSelect.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/collectionSection.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
Labels: Bug

#4206 Remove the env file copy composer script
  src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
Labels: Bug

#4173 Improve phpdoc types for phpstan and use AuditableTrait
  src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRule.php
  src/Sulu/Bundle/CategoryBundle/Entity/Category.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryInterface.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationInterface.php
  src/Sulu/Bundle/CategoryBundle/Entity/Keyword.php
  src/Sulu/Bundle/ContactBundle/Entity/Account.php
  src/Sulu/Bundle/ContactBundle/Entity/AccountContact.php
  src/Sulu/Bundle/ContactBundle/Entity/Address.php
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php
  src/Sulu/Bundle/ContactBundle/Entity/Fax.php
  src/Sulu/Bundle/ContactBundle/Entity/SocialMediaProfile.php
  src/Sulu/Bundle/ContactBundle/Entity/SocialMediaProfileType.php
  src/Sulu/Bundle/MediaBundle/Entity/Collection.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionType.php
  src/Sulu/Bundle/MediaBundle/Entity/File.php
  src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
  src/Sulu/Bundle/MediaBundle/Entity/Media.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/BaseRole.php
  src/Sulu/Bundle/SecurityBundle/Entity/Group.php
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
  src/Sulu/Bundle/WebsiteBundle/Entity/Analytics.php
  src/Sulu/Component/Content/Document/Behavior/RedirectTypeBehavior.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
Labels: Enhancement

#4192 Add shadow page fields to Page Settings
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_with_schema.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSettings.xml
  src/Sulu/Bundle/ContentBundle/Resources/js/containers/Form/fields/PageSettingsShadowLocaleSelect.js
  src/Sulu/Bundle/ContentBundle/Resources/js/containers/Form/tests/fields/PageSettingsShadowLocaleSelect.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/index.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/CopyLocaleDialog.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
  src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/LocaleSubscriber.php
  src/Sulu/Bundle/ContentBundle/Serializer/Subscriber/ShadowLocaleSubscriber.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Mapper/ContentMapperTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ContentRepositoryTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/NodeRepositoryTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/BaseTestCase.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/DocumentManager/FindTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/DocumentManager/MappingTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/Model/FullDocument.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/Model/Mapping10Document.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/Model/Mapping5Document.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/app/AppKernel.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/app/Resources/webspaces/.gitkeep
  src/Sulu/Bundle/DocumentManagerBundle/Tests/app/config/config.yml
  src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollector.php
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
  src/Sulu/Component/Content/Compat/DataNormalizer.php
  src/Sulu/Component/Content/Compat/Structure.php
  src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
  src/Sulu/Component/Content/Metadata/Loader/schema/schema-1.0.xsd
  src/Sulu/Component/Content/Metadata/Parser/SchemaXmlParser.php
  src/Sulu/Component/Content/Repository/Content.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
  src/Sulu/Component/DocumentManager/Subscriber/Behavior/Audit/TimestampSubscriber.php
  src/Sulu/Component/DocumentManager/Tests/Bootstrap.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Behavior/Audit/TimestampSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/symfony-di/core.xml
  src/Sulu/Component/DocumentManager/Tests/symfony-di/subscribers.xml
Labels: Feature

#4112 Added exception messages to user provider for enabled and locked
  .travis.yml
  CHANGELOG.md
  src/Sulu/Bundle/SecurityBundle/User/UserProvider.php
Labels: Enhancement

#4209 improve ContactBundle functional tests
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#4211 consolidate initial loader for Datagrids
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/Pagination.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/Pagination.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
Labels: Bug

#4217 Add `setNote` and `getNote` to ContactInterface
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php
Labels: Enhancement

#4214 Place label for shadow toggler next to toggler instead above of it
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_without_label.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Account.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
  src/Sulu/Bundle/ContentBundle/ResourceMetadata/StructureResourceMetadataProvider.php
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageSettings.xml
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetTypesController.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetTypesControllerTest.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/ItemMetadataCase.php
Labels: Feature

#4223 Added autoconfigure for sulu admin class
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
Labels: Feature

#4228 Added support for autowire for rest helper and field descriptor factory
  src/Sulu/Bundle/CoreBundle/Resources/config/list_builder.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
Labels: Feature

#4222 fix loading in ColumnListAdapter when activating item
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
Labels: Bug

#4219 implement deleting of media in datagrid
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Feature

#4224 Add history and formats tab to media form
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/ButtonCell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/MediaBundle/Controller/FormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/mediaCard.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/FormatStore/FormatStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/FormatStore/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/FormatStore/tests/FormatStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/MediaFormats.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/README.md
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/mediaFormats.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/tests/MediaFormats.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaFormats/tests/__snapshots__/MediaFormats.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/MediaHistory.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/README.md
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/mediaHistory.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/tests/MediaHistory.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/tests/__snapshots__/MediaHistory.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaFormatControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
Labels: Feature

#4242 Introduce datagridAdapterDefaultProps
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/datagridAdapterDefaultProps.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/TestHelper/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
Labels: Enhancement

#4227 Make AudienceTargeting and Category tests faster
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/TargetGroupControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
Labels: Enhancement

#4240 fixed travis timeout for php 5.5 test case
  .travis.yml
Labels: Enhancement
