Repository sulu/sulu, pull requests merged in 2018-02, with the labels that each got.

#3764 Allow dynamic order of elements in webspace xmls
  CHANGELOG.md
  src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd
  src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.1.xsd
  src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader10Test.php
  src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
  tests/Resources/DataFixtures/Webspace/valid/sulu.io_deprecatedDynamicOrder.xml
  tests/Resources/DataFixtures/Webspace/valid/sulu.io_dynamicOrder.xml
Labels: Enhancement

#3769 Implement form validation
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/AutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/Suggestion.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/AutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Grid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/grid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/Grid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/__snapshots__/Grid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/tests/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/TextArea.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/tests/TextArea.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/tests/__snapshots__/TextArea.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/textArea.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/colors.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/renderer.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MetadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MetadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
Labels: Feature

#3809 fix strange behaviours on enter keypress in form
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Actions.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
Labels: Bug
