Repository sulu/sulu, pull requests merged in 2018-11, with the labels that each got.

#4230 Allow to move media collections
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/overlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/datagridOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/MultiDatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/tests/MultiDatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/SingleDatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/tests/SingleDatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/MediaBundle/Api/RootCollection.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
Labels: Feature

#4243 Add moving items to Media and Category Datagrids
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/CategoryBundle/Api/RootCategory.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryListRepresentation.php
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
Labels: Feature

#4233 Fix duplicate keys in translation strings JSON.
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
Labels: Enhancement

#4249 Added autowire services for SecurityCheckerInterface and WebspaceManagerInterface
  src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/checker.xml
Labels: Feature

#4229 Added support for list-builder configuration in project config directory
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/CoreBundle/Tests/DependencyInjection/SuluCoreExtensionTest.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/Provider/ChainProvider.php
  src/Sulu/Component/Rest/RestHelperInterface.php
Labels: Feature

#4250 Use field descriptor interface in resthelper
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Component/Rest/RestHelper.php
Labels: Enhancement

#4234 Fix plural form of "person" to "people".
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
Labels: Bug

#4252 Fixed website caching by setting cache_lifetime.enhancer public
  src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-lifetime-enhancer.xml
Labels: Bug, Critical

#4255 Validate composer json
  .travis.yml
  composer.json
Labels: Enhancement

#4256 Get media file extension based on mimetype
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
Labels: Bug

#4257 Fixed url field type initial value
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
Labels: Bug

#4236 Added image rotation based on exif
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
Labels: Feature

#4263 Fixed param default value
  src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php
Labels: Bug

#4266 fix creating of new account without logo
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
Labels: Bug

#4258 add headline param to Input field type
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
Labels: Feature

#4241 Set default locale for admin user to "en".
  CHANGELOG.md
  src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php
Labels: Enhancement

#4268 Added configuration for test environment
  config/packages/test/massive_search.yaml
  config/packages/test/security_admin.yaml
  config/packages/test/sulu_test.yaml
Labels: Enhancement

#4271 Fixed hash serializer for inline serialization
  src/Sulu/Component/Hash/Serializer/Subscriber/HashSerializeEventSubscriber.php
  src/Sulu/Component/Hash/Tests/Unit/Serializer/Subscriber/HashSerializeEventSubscriberTest.php
  src/Sulu/Component/Security/Tests/Unit/Serializer/Subscriber/SecuredEntitySubscriberTest.php
Labels: Bug

#4283 Update readme file with installation and more badges
  README.md
Labels: Enhancement

#4274 added .editorconfig file to improve code style consistency
  .editorconfig
Labels: Enhancement

#4269 add toolbar item for draft deletion of page
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
Labels: Feature

#4295 allow to delete content of properties in excerpt
  src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
Labels: Bug

#4294 fix dirty state after saving empty ckeditor
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/tests/CKEditor5.test.js
Labels: Bug
