Repository sulu/sulu, pull requests merged in 2018-04, with the labels that each got.

#3855 Add FieldType for internal links
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/column.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/columnList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Column.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Item.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Column.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/overlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/datagridOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/__snapshots__/Assignment.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
  src/Sulu/Bundle/ContentBundle/Controller/PageController.php
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
  src/Sulu/Component/Content/Repository/ContentRepository.php
  stylelint.config.js
Labels: Feature

#3886 Add web profiler 3.4.7 as conflict version
  composer.json
Labels: Bug

#3887 fix caching config in test environment
  app/config/config.yml
Labels: Bug

#3881 Adjust FieldTypeProps to allow inspecting the form
  composer.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/TextArea.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/tests/TextArea.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/TextArea.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/FormInspector.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/TextArea.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
Labels: Feature

#3890 Fix scrolling and height of datagrid in media section and overlay
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/mediaSelectionOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
Labels: Bug

#3892 Throw a meaningful error when a form is not embedded in a ResourceTabs
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
Labels: Enhancement

#3879 Disable items by ids in datagrid
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ItemButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Item.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
Labels: Feature

#3587 Implemented sidebar
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/Sidebar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/registries/SidebarViewRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/sidebar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/stores/SidebarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/Sidebar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/__snapshots__/Sidebar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/__snapshots__/withSidebar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/registries/SidebarViewRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/stores/SidebarStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SplitView/SplitView.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SplitView/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.css
Labels: Feature

#3233 Remove temp position property on contact
  UPGRADE.md
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
Labels: Enhancement

#3888 Datagrid AdapterSwitch
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/ButtonGroup.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/buttonGroup.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/tests/ButtonGroup.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/tests/__snapshots__/ButtonGroup.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.eot
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/colors.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/AdapterSwitch.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/AdapterSwitchItem.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/AbstractAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/FolderAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/AdapterSwitch.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/AdapterSwitch.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/adapters/MediaCardOverviewAdapter.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/adapters/MediaCardSelectionAdapter.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Feature

#3894 Move assignment configuration to AdminController
  .circleci/config.yml
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
  src/Sulu/Bundle/AdminBundle/FieldType/FieldTypeOptionRegistry.php
  src/Sulu/Bundle/AdminBundle/FieldType/FieldTypeOptionRegistryInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FieldType/FieldTypeOptionRegistryTest.php
  src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
Labels: Enhancement

#3896 Fix bug in FieldDescriptor
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineConcatenationFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineIdentityFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/FieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/General/PropertyMetadata.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/Driver/Resources/complete.xml
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/Driver/Resources/minimal.xml
Labels: Bug

#3901 Preview voter
  CHANGELOG.md
  src/Sulu/Bundle/PreviewBundle/Resources/config/config_preview.yml
  src/Sulu/Bundle/PreviewBundle/Security/PreviewVoter.php
Labels: Enhancement

#3903 Fix bug in resourcemetadatamapper when block is in section
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
Labels: Critical

#3899 Replaced links in preview with '#'
  CHANGELOG.md
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
Labels: Enhancement

#3912 Fixed content-query when a child is broken
  CHANGELOG.md
  src/Sulu/Component/Content/Repository/Content.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
  src/Sulu/Component/Content/Tests/Unit/Repository/ContentRepositoryTest.php
Labels: Bug

#3902 Field "time"
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Time.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Time.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Feature

#3893 Datagrid fields
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/Datagrid/Field.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/FormResourceMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataPool.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataProviderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Cell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/AdapterSwitch.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/BytesFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/DateFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/DateTimeFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/StringFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/ThumbnailFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/TimeFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/registries/DatagridFieldTransformerRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/AdapterSwitch.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/BytesFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/DateFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/DateTimeFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/StringFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/ThumbnailFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/TimeFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/registries/DatagridAdapterRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/registries/DatagridFieldTransformerRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/registries/NavigationRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/ContentBundle/ResourceMetadata/StructureResourceMetadataProvider.php
  src/Sulu/Bundle/MediaBundle/Resources/config/image-formats.xml
  src/Sulu/Component/Rest/ListBuilder/FieldDescriptorInterface.php
Labels: Feature

#3917 Input component: Fixed double borders
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
Labels: Bug

#3906 Add file version remove
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Api/Media.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
  src/Sulu/Bundle/MediaBundle/Gruntfile.js
  src/Sulu/Bundle/MediaBundle/Resources/public/css/main.css
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/collections/media-edit-overlay/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/collections/media-edit-overlay/versions.html
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/versions.html
  src/Sulu/Bundle/MediaBundle/Resources/public/scss/modules/media-edit-overlay.scss
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Component/Rest/RestController.php
Labels: Feature

#3918 CSV export boolean
  CHANGELOG.md
  src/Sulu/Component/Rest/Csv/CsvHandler.php
  src/Sulu/Component/Rest/RestController.php
  src/Sulu/Component/Rest/Tests/Unit/Csv/CsvHandlerTest.php
Labels: Bug

#3919 Added interface to doctrine-list-builder
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderFactory.php
Labels: Bug

#3915 Fix api ContactLocale constructor typehint
  CHANGELOG.md
  src/Sulu/Bundle/ContactBundle/Api/ContactLocale.php
Labels: Bug

#3921 ViewRenderer: Do not change state in render
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
Labels: Bug

#3909 Add upgrade for test setup changes
  UPGRADE.md
Labels: Enhancement

#3926 Fix profiler for none sulu routes
  CHANGELOG.md
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
Labels: Bug

#3920 Add branch alias for 2.0-dev
  composer.json
Labels: Feature

#3930 Fixed preview style-link
  CHANGELOG.md
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
Labels: Critical

#3927 Add upgrade for HttpCache class
  UPGRADE.md
Labels: Enhancement

#3935 Throw a proper error if the route passed to the router does not exist
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/registries/RouteRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/RouteRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
Labels: Enhancement

#3936 Added inactive state for checkbox
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/Checkbox.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/checkbox.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/__snapshots__/Checkbox.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/Switch.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/tests/Switch.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/tests/__snapshots__/Switch.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/BoolFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Feature

#3937 Fixed priority of request-context-listener
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
Labels: Bug

#3938 Bugfix: Fixed converting of date
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/DatePicker.test.js
Labels: Critical
