Repository sulu/sulu, pull requests merged in 2018-08, with the labels that each got.

#4085 Fix missing image in MediaDetail view
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
Labels: Bug

#4083 Remember active Page in WebspaceOverview
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/loadingStrategies/AbstractLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/loadingStrategies/FullLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/loadingStrategies/InfiniteLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/loadingStrategies/PaginatedLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/FlatStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/AdapterSwitch.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/FullLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/InfiniteLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/registries/DatagridAdapterRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/ColumnStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/FlatStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/TreeStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Repository/ContentRepositoryTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Component/Content/Repository/Content.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
Labels: Feature

#4087 add excerpt tab to page
  src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php
  src/Sulu/Bundle/ContentBundle/Content/Structure/ExcerptStructureExtension.php
  src/Sulu/Bundle/ContentBundle/Controller/ExcerptController.php
  src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
  src/Sulu/Bundle/ContentBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
Labels: Feature

#4090 Add FieldType for categories
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/registries/DatagridAdapterRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/registries/DatagridAdapterRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/selection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/ContentBundle/DependencyInjection/SuluContentExtension.php
  src/Sulu/Bundle/ContentBundle/Resources/config/forms/PageExcerpt.xml
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
Labels: Feature

#4098 Use ToolbarActions to define Toolbar in Form
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/Login.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/registries/ToolbarActionRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/__snapshots__/Form.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/ToolbarActionRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php
  src/Sulu/Bundle/ContentBundle/Controller/AbstractExtensionController.php
  src/Sulu/Bundle/ContentBundle/Controller/ExcerptController.php
  src/Sulu/Bundle/ContentBundle/Controller/ResourcelocatorController.php
  src/Sulu/Bundle/ContentBundle/Controller/SeoController.php
  src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/ContentBundle/Resources/js/index.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/PageForm.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/README.md
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/index.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/pageForm.scss
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/PageForm.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/__snapshots__/PageForm.test.js.snap
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/SeoControllerTest.php
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
Labels: Feature

#4097 always activate WebLink component
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
Labels: Enhancement

#4107 Show publish state in Form component
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/PublishIndicator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/tests/PublishIndicator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Icons.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/icons.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/stores/ToolbarStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/ExcerptControllerTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/SeoControllerTest.php
Labels: Feature

#4111 Add keyboard shortcuts to AutoComplete components
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/AutoCompletePopover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/suggestion.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/AutoCompletePopover.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/Popover.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/SingleAutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/MultiAutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/MultiAutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
Labels: Feature

#4108 Copy locales in pages
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/ToolbarActionRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/index.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Admin/ContentAdmin.php
  src/Sulu/Bundle/ContentBundle/Resources/js/index.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/CopyLocaleDialog.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/CopyLocaleDialog.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/toolbarActions/copyLocaleDialog.scss
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  styleguide.config.js
Labels: Feature

#4113 Fix error when pressing save buttons right after each other
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
Labels: Bug

#4114 Fix TreeTable view for pages
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/TreeStructureStrategy.test.js
Labels: Bug

#4115 Exclude shadows on ghost via toggler
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toggler.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Dropdown.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Toggler.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Toggler.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContentBundle/Resources/translations/admin.en.json
Labels: Feature

#4109 Remove validation-state from rendered link
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Markup/LinkTag.php
  src/Sulu/Bundle/ContentBundle/Tests/Unit/Markup/LinkTagTest.php
Labels: Bug

#4123 remove warning for missing translations
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/__snapshots__/ArrowMenu.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/tests/__snapshots__/Selection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/ToolbarActionRegistry.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/CollectionFormOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
Labels: Enhancement

#4116 Add button for moving and copying page
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/overlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/Overlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/ColumnStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/datagridOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/MultiDatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiDatagridOverlay/tests/MultiDatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Selection/tests/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/SingleDatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleDatagridOverlay/tests/SingleDatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Feature
