Repository sulu/sulu, pull requests merged in 2018-06, with the labels that each got.

#4005 implement error snackbar
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Snackbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/snackbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Snackbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Snackbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/toolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/colors.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStorePool.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/stores/ToolbarStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/__snapshots__/Form.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/PageForm.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/PageForm.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/__snapshots__/PageForm.test.js.snap
Labels: Feature

#4003 Number field / NumberFieldTransformer / Number content type
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/ButtonGroup.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/Number.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/tests/Number.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/tests/__snapshots__/Number.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/NumberFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/DateTimeFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/NumberFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Number.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Number.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
  src/Sulu/Bundle/ContentBundle/Resources/js/components/WebspaceSelect/WebspaceSelect.js
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Component/Content/ContentTypeInterface.php
  src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
  src/Sulu/Component/Content/Types/Number.php
Labels: Feature

#4007 Load correct translations
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/Application.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/Config.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/ResourceMetadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceMetadataStore/tests/ResourceMetadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  testSetup.config.js
Labels: Enhancement

#4009 Bugfix: Datagrid search reload
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Search.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Search.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Search.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Bug

#3998 Fixed user-blame
  src/Sulu/Bundle/PersistenceBundle/Tests/Functional/EventSubscriber/ORM/UserBlameSubscriberIntegrationTest.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/UserBlameSubscriberTest.php
Labels: Bug

#4040 remove reset of page when returning from a form to the datagrid
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
Labels: Bug

#4042 Add symfony 3.4.12 as conflict to fix caching tests
  CHANGELOG.md
  composer.json
Labels: Bug

#4041 Add CKEditor 5 as text editor
  composer.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/tests/CKEditor5.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/TextEditor.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/TextEditor.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/TextEditor.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/registries/TextEditorRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/tests/TextEditor.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/tests/__snapshots__/TextEditor.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/tests/registries/TextEditorRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
  styleguide.config.js
  tests/js/mocks/svg.js
  tests/js/testSetup.config.js
  webpack.config.js
Labels: Feature

#4044 Fixed document creation in webspace-initializer
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Preview/PageRouteDefaultsProvider.php
  src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
  src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
Labels: Bug

#4047 Fix display errors in Firefox
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/textArea.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
Labels: Bug

#4048 fix save validation if empty data is delivered from server
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
Labels: Bug
