Repository sulu/sulu, pull requests merged in 2018-03, with the labels that each got.

#3806 fix compatibility on lowest and fix appveyor
  CHANGELOG.md
  appveyor.yml
  composer.json
  src/Sulu/Component/Cache/Tests/Unit/Cache/DataCacheTest.php
Labels: Bug

#3807 Remove recreation of MediaStores in MediaOverview and MediaSelection
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/FlatStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Bug

#3801 fix superfluous updates on binded observable on the router
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/PageForm.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Bug

#3819 Fix forgotten context binding for resetPreviewUrl method
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/collections/media-edit-overlay/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/main.js
Labels: Bug

#3810 Fixed rename and publish exception if page has link to a child
  CHANGELOG.md
  composer.json
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
Labels: Bug

#3829 Toolbar: Disable dropdown when all options are disabled
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Dropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Dropdown.test.js
Labels: Bug

#3823 remember selected objects instead of ids
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Enhancement

#3831 Require symfony web-link component as needed
  composer.json
Labels: Bug

#3820 Added base-domains to query for custom-urls
  CHANGELOG.md
  src/Sulu/Bundle/CustomUrlBundle/Resources/config/document.xml
  src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
  src/Sulu/Component/CustomUrl/Repository/CustomUrlRepository.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
Labels: Bug

#3842 update to mobx4
  .eslintrc.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/FullLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/InfiniteLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/registries/RouteRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/RouteRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/package.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/PageForm.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/tests/CollectionStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
Labels: Enhancement

#3844 Fix accidentally escaping of select value
  CHANGELOG.md
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1520426818057.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1521102556740.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1521102556740.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1520426818057.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1521102556740.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1521102556740.js
  src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.js
  src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.min.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
  src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
Labels: Bug

#3846 Added authored field to base-page-document index
  CHANGELOG.md
  UPGRADE.md
  src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
Labels: Enhancement

#3813 Ignore wrong template exception
  CHANGELOG.md
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Gruntfile.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/css/main.css
  src/Sulu/Bundle/SnippetBundle/Resources/public/css/main.min.css
  src/Sulu/Bundle/SnippetBundle/Resources/public/dist/components/snippet/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/dist/components/webspace/settings/snippets/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/webspace/settings/snippets/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/js/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/scss/main.scss
  src/Sulu/Bundle/SnippetBundle/Resources/public/scss/modules/snippet-content.scss
  src/Sulu/Bundle/SnippetBundle/Resources/public/scss/modules/webspace.scss
  src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.de.xlf
  src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.en.xlf
  src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.fr.xlf
  src/Sulu/Bundle/SnippetBundle/Resources/translations/sulu/backend.nl.xlf
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManagerInterface.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Twig/SnippetAreaTwigExtensionTest.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetAreaTwigExtension.php
Labels: Bug

#3848 Added check for unknown-document for sulu_content_load
  CHANGELOG.md
  src/Sulu/Component/Content/Mapper/ContentMapper.php
Labels: Bug, Critical

#3811 Implement Assignment FieldType
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/assignment.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/datagridOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/stores/AssignmentStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/__snapshots__/Assignment.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Assignment/tests/stores/AssignmentStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Assignment.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/registries/FieldRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Assignment.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/registries/FieldRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/PageForm/tests/PageForm.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
Labels: Feature

#3660 Datepicker Component
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/tests/__snapshots__/ArrowMenu.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/datePicker.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/popover.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/ContentBundle/Resources/js/components/WebspaceSelect/tests/__snapshots__/WebspaceSelect.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  stylelint.config.js
Labels: Feature

#3863 remove jackrabbit build from appveyor
  appveyor.yml
Labels: Enhancement

#3857 Fix errors in styleguide
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/Bundles.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/README.md
  styleguide.config.js
Labels: Bug

#3859 ColumnList Scrolling in WebspaceOverview
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Column.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/column.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/columnList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Column.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Column.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/columnListAdapter.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
Labels: Enhancement

#3871 Clear MediaOverview stores when using back button
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Bug

#3868 Prepend manifest.json configuration and update min requirement to symfony 3.4
  composer.json
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
Labels: Enhancement

#3872 StructureResourceMetadataProvider only in Admin kernel
  src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
Labels: Bug

#3876 Load data with template
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
  src/Sulu/Bundle/ContentBundle/Resources/public/dist/components/content/form/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/dist/components/content/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/dist/model/content.js
  src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/js/model/content.js
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/StructureSubscriberTest.php
Labels: Bug
