Repository sulu/sulu, pull requests merged in 2018-09, with the labels that each got.

#4125 Ordering pages in ColumnList
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownListOption.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Item.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/FlatStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/AdapterSwitch.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/FullLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/InfiniteLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/registries/DatagridAdapterRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/ColumnStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/FlatStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/TreeStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/DatagridOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/DatagridOverlay/tests/DatagridOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Feature

#4129 Add a URL field type
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Select.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/displayValue.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/__snapshots__/Url.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/url.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
Labels: Feature

#4137 Implemented initializer update-config hooks
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/types.js
  src/Sulu/Bundle/ContentBundle/Resources/js/containers/Form/fields/SearchResult.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/MediaSelection.js
Labels: DX, Enhancement

#4143 Add limit to Datagrid pagination
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/InfiniteScroller.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/tests/InfiniteScroller.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/Pagination.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/Pagination.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/displayValue.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Select.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/tests/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/tests/__snapshots__/SingleSelect.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/FolderAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/loadingStrategies/PaginatedLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/FolderAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/loadingStrategies/PaginatedLoadingStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/logoutOnUnauthorizedResponse.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/adapters/MediaCardAdapter.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Feature

#4121 Set a timeout when purging caches
  CHANGELOG.md
  src/Sulu/Component/HttpCache/ProxyClient/Symfony.php
Labels: Bug

#4134 Added input field to pagination.
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/__snapshots__/Email.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/Number.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/tests/__snapshots__/Number.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/Pagination.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/Pagination.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Phone/tests/__snapshots__/Phone.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/__snapshots__/ResourceLocator.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/AbstractTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Search.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/FolderAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/MetadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MetadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/Login.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/LoginForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/ResetForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/SingleMediaUpload.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Feature

#4150 Added .env file generation
  src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
Labels: Enhancement

#4153 only check for reserved and required keyword in StructureXmlLoader
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
Labels: Enhancement

#4154 Fix loading of environment specific configurations
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Bug

#4155 Add expressions in form XMLs to conditionally display field types
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Item.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MetadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Tests/Unit/ResourceMetadata/ResourceMetadataMapperTest.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
Labels: Feature

#4147 Added root kernel path to be available as document data fixtures paths
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
Labels: Enhancement

#4164 Fix kernel name
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Critical

#4140 Fixed missing http cache parameters under dev and test env
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
Labels: Bug

#4163 Change ContentTypeManager::getAll to return only aliases instead of instances
  UPGRADE.md
  src/Sulu/Bundle/ContentBundle/Command/ContentTypesDumpCommand.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
  src/Sulu/Component/Content/ContentTypeManager.php
  src/Sulu/Component/Content/ContentTypeManagerInterface.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/ContentTypeManagerTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
Labels: Enhancement

#4177 Matrix: Fix bug when value does not exists
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Row.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/tests/Matrix.test.js
Labels: Bug
