Repository sulu/sulu, pull requests merged in 2018-05, with the labels that each got.

#3945 Fix test after npm update
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
Labels: Bug

#3941 Fix: the sitemap query builder only considers the "de" hiddenInSitemap flag.
  CHANGELOG.md
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapContentQueryBuilder.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorTest.php
Labels: Bug

#3947 Add FieldType for checkbox
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Feature

#3934 Add sorting functionality in Datagrid with remembering the state
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/HeaderCell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/updateRouterAttributesFromView.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
Labels: Feature

#3949 fix security check for deleting draft
  CHANGELOG.md
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1521102556740.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1525694489969.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1525694489969.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1521102556740.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1525694489969.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1525694489969.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
  src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
  src/Sulu/Bundle/ContentBundle/Controller/NodeController.php
  src/Sulu/Bundle/ContentBundle/Resources/public/dist/components/content/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/dist/services/content-manager.js
  src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/main.js
  src/Sulu/Bundle/ContentBundle/Resources/public/js/services/content-manager.js
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/NodeControllerTest.php
Labels: Bug

#3952 add prefer-const rule to eslint
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/MultiSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/PopoverPositioner.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/normalizers/RatioNormalizer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/RectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/normalizers/RoundingNormalizer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  styleguide.config.js
Labels: Enhancement

#3951 add yoda condition rule to eslint
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
Labels: Enhancement

#3898 Add user tab to contact
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/Datagrid/DatagridInterface.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/FormResourceMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadata.php
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/ResourceMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/PasswordConfirmation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/passwordConfirmation.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/PasswordConfirmation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/PasswordConfirmation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/PasswordConfirmation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/ContentBundle/Resources/config/structure.xml
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/User.xml
  src/Sulu/Bundle/SecurityBundle/Resources/public/js/components/users/main.js
  src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Metadata/PropertyMetadata.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/XmlLoaderTest.php
Labels: Feature

#3582 Datagrid Adapter: TreeListAdapter
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.eot
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/__snapshots__/Icon.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Cell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/HeaderCell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/AbstractTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TreeListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/config/list-builder/BasePageDocument.xml
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
Labels: Feature

#3953 Fix sulu route options with dash
  CHANGELOG.md
  src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
  src/Sulu/Bundle/RouteBundle/Tests/app/Resources/test_config.yml
Labels: Bug

#3954 Color picker component
  .eslintrc.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/ColorPicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/colorPicker.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/colorPickerGlobal.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/ColorPicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/datePicker.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/Email.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/__snapshots__/Email.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/field.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ColorPicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ColorPicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: Feature

#3962 Removed export-ignore attribute for package.json files
  .gitattributes
Labels: Bug

#3969 rename info_text to infoText
  src/Sulu/Bundle/AdminBundle/ResourceMetadata/Form/Option.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
Labels: Enhancement

#3957 Added function to get value for property name
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/FormInspector.test.js
Labels: DX, Enhancement

#3964 update to flow 0.71
  .flowconfig
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/withContainerSize.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/AbstractTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/updateRouterAttributesFromView.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
Labels: Enhancement

#3968 Fix build of dist file for audiencetargeting bundle
  CHANGELOG.md
  src/Sulu/Bundle/AudienceTargetingBundle/Gruntfile.js
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/public/dist/components/target-groups/edit/details/conditions/condition-list.html
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/public/dist/components/target-groups/list/list.html
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/public/dist/main.js
Labels: Bug

#3974 fix font size in dialog
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
Labels: Design

#3973 Improve contrast in table styles
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
Labels: Design

#3967 Fix loading of minified js files for production
  CHANGELOG.md
  src/Sulu/Bundle/AdminBundle/Gruntfile.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1516279004076.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1526554713231.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1526554713231.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1516279004076.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1526554713231.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1526554713231.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
  src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
  src/Sulu/Bundle/CategoryBundle/Gruntfile.js
  src/Sulu/Bundle/CollaborationBundle/Gruntfile.js
  src/Sulu/Bundle/ContactBundle/Gruntfile.js
  src/Sulu/Bundle/ContentBundle/Gruntfile.js
  src/Sulu/Bundle/CustomUrlBundle/Gruntfile.js
  src/Sulu/Bundle/DocumentManagerBundle/Gruntfile.js
  src/Sulu/Bundle/DocumentManagerBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/LocationBundle/Gruntfile.js
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/images/layers-2x.png
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/images/layers.png
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/images/marker-icon-2x.png
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/images/marker-icon.png
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/images/marker-shadow.png
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/vendor/leaflet/leaflet.css
  src/Sulu/Bundle/PreviewBundle/Gruntfile.js
  src/Sulu/Bundle/PreviewBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/ResourceBundle/Gruntfile.js
  src/Sulu/Bundle/SearchBundle/Gruntfile.js
  src/Sulu/Bundle/SearchBundle/Resources/public/dist/components/dropdown-input/main.html
  src/Sulu/Bundle/SearchBundle/Resources/public/dist/components/search-results/main.html
  src/Sulu/Bundle/SearchBundle/Resources/public/dist/components/search-results/search-results.html
  src/Sulu/Bundle/SearchBundle/Resources/public/dist/components/search-totals/main.html
  src/Sulu/Bundle/SearchBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/SearchBundle/package.json
  src/Sulu/Bundle/SecurityBundle/Gruntfile.js
  src/Sulu/Bundle/SnippetBundle/Gruntfile.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/TagBundle/Gruntfile.js
  src/Sulu/Bundle/WebsiteBundle/Gruntfile.js
  src/Sulu/Bundle/WebsiteBundle/Resources/public/dist/main.js
  src/Sulu/Bundle/WebsocketBundle/Gruntfile.js
  src/Sulu/Bundle/WebsocketBundle/Resources/public/dist/main.js
Labels: Bug

#3979 Fix testcase use statements
  src/Sulu/Component/Rest/Tests/Unit/Listing/ListRestHelperTest.php
  src/Sulu/Component/Rest/Tests/Unit/RequestParametersTraitTest.php
  src/Sulu/Component/Rest/Tests/Unit/RestControllerTest.php
  src/Sulu/Component/Rest/Tests/Unit/RestHelperTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/DoctrineAccessControlProviderTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/PhpcrAccessControlProviderTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityCheckerTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityContextVoterTest.php
  src/Sulu/Component/Security/Tests/Unit/Serializer/Subscriber/SecuredEntitySubscriberTest.php
  src/Sulu/Component/Serializer/Tests/Unit/ArraySerializationVisitorTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/BuilderTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/DataProviderPoolTest.php
  src/Sulu/Component/Symfony/Tests/Unit/CompilerPass/TaggedServiceCollectorCompilerPassTest.php
  src/Sulu/Component/Tag/Tests/Unit/Request/TagRequestHandlerTest.php
  src/Sulu/Component/Util/Tests/Unit/ArrayUtilsTest.php
  src/Sulu/Component/Util/Tests/Unit/SortUtilsTest.php
  src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
  src/Sulu/Component/Util/Tests/Unit/SuluVersionPassTest.php
  src/Sulu/Component/Util/Tests/Unit/TextUtilsTest.php
  src/Sulu/Component/Util/Tests/Unit/WildcardUrlUtilTest.php
  src/Sulu/Component/Websocket/Tests/Unit/AbstractWebsocketAppTest.php
  src/Sulu/Component/Websocket/Tests/Unit/MessageDispatcher/MessageBuilderTest.php
  src/Sulu/Component/Websocket/Tests/Unit/MessageDispatcher/MessageDispatcherTest.php
  src/Sulu/Component/Websocket/Tests/Unit/RatchetAppManagerTest.php
  src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/AdminRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/ParameterRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/RequestAttributesTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/UrlRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/EnvironmentTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalInformationTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalTest.php
  src/Sulu/Component/Webspace/Tests/Unit/SegmentTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Settings/SettingsManagerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/StructureProvider/WebspaceStructureProviderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Url/ReplacerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Url/WebspaceUrlChainProviderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Url/WebspaceUrlProviderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/UrlTest.php
  src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
  src/Sulu/Component/Webspace/Tests/Unit/WebspaceTestCase.php
Labels: Enhancement

#3986 add sourcemaps to build
  webpack.config.js
Labels: DX, Enhancement

#3975 Make grid responsive
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/baseItem.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/grid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/__snapshots__/Grid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/PasswordConfirmation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/passwordConfirmation.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tabs.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/__snapshots__/Tabs.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/renderer.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Form.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/form.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/__snapshots__/ResourceTabs.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/mediaDetail.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/__snapshots__/MediaDetail.test.js.snap
  webpack.config.js
Labels: Design

#3980 Fix kernel.project_dir parameter for PreviewKernel
  CHANGELOG.md
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
Labels: Bug

#3988 Template switching correct mapping
  CHANGELOG.md
  UPGRADE.md
  src/Sulu/Bundle/ContentBundle/Content/Types/Date.php
  src/Sulu/Component/Content/Compat/Block/BlockProperty.php
  src/Sulu/Component/Content/Compat/Block/BlockPropertyInterface.php
  src/Sulu/Component/Content/Document/Subscriber/StructureSubscriber.php
  src/Sulu/Component/Content/Types/BlockContentType.php
Labels: Bug

#3989 add account selection to contact
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/AutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoComplete/tests/AutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/AutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/autoComplete.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/stores/AutoCompleteStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/tests/AutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/tests/__snapshots__/AutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/AutoComplete/tests/stores/AutoCompleteStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/renderer.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/Contact.xml
  webpack.config.js
Labels: Feature

#3994 Update jest to 23.0.0
  package.json
Labels: Enhancement

#3993 Remove multiple requests for SingleMediaUpload
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaUpload.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/SingleMediaUpload.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/MediaDetail.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetail/tests/MediaDetail.test.js
Labels: Enhancement

#3999 add form for Tags
  src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
  src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
  src/Sulu/Bundle/TagBundle/Resources/config/forms/Tag.xml
  src/Sulu/Bundle/TagBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/TagBundle/Resources/translations/admin.en.json
Labels: Feature

#4000 fix travis build which is stalling in contact tests
  bin/runtests
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#4001 Bugfix: Field date and time without utc calculation
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/DateFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/fieldTransformers/TimeFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/DateFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/fieldTransformers/TimeFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Time.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Time.test.js
Labels: Bug

#4004 Added time-field-transformer to registry
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
Labels: Bug
