Repository sulu/sulu, pull requests merged in 2018-07, with the labels that each got.

#4049 fix margins for pagination buttons in datagrid
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/datagrid.scss
Labels: Enhancement

#4050 remove unnecessary tests in AccountController
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
Labels: Bug

#4057 Removed password-hash from user-api
  CHANGELOG.md
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
Labels: Critical

#4058 Added escaping of values in contact/media list
  CHANGELOG.md
  src/Sulu/Bundle/ContactBundle/Resources/public/dist/components/card-decorator/card-view.js
  src/Sulu/Bundle/ContactBundle/Resources/public/js/components/card-decorator/card-view.js
  src/Sulu/Bundle/ContactBundle/Resources/views/Template/base.form.html.twig
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/collections/masonry-decorator/masonry-view.js
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/masonry-decorator/masonry-view.js
Labels: Critical

#4056 Added security-check for collections in media controller
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Resources/config/list-builder/Media.xml
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
Labels: Critical

#4060 escape title in media overlay
  CHANGELOG.md
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1527496454314.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1531748709722.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1531748709722.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1527496454314.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1531748709722.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1531748709722.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
  src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/collections/media-edit-overlay/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/dist/components/media-selection/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/media-edit-overlay/main.js
  src/Sulu/Bundle/MediaBundle/Resources/public/js/components/media-selection/main.js
Labels: Critical

#4062 fix reset of page in datagrid when search or sort is set initially
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
Labels: Bug

#4067 avoid returning the same id multiple times in filter query of smart content
  CHANGELOG.md
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
  src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
Labels: Critical

#4077 Move titles resp. webspace select and datagrid toolbar into the same line
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/datagrid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/WebspaceOverview.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Enhancement

#4065 Allow to delete page from ColumnList
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownListOption.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbarDropdownOption.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/stores/DatagridStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/stores/DatagridStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/structureStrategies/ColumnStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/Datagrid.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/Datagrid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Datagrid/tests/__snapshots__/Datagrid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/WebspaceOverview.test.js
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Datagrid/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelection/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Feature

#4080 Fix positioning of elements in ColumnList
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PublishIndicator/publishIndicator.scss
Labels: Bug

#4081 Center loading icon of Button
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
Labels: Bug

#4078 Open overlay to copy content when Ghost form is opened
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Column.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Column.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/GhostIndicator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/ghostIndicator.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/tests/GhostIndicator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/GhostIndicator/tests/__snapshots__/GhostIndicator.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/Radio.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/RadioGroup.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/__snapshots__/ResourceLocator.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Switch/switch.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/adapters/TreeTableAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/GhostDialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/ghostDialog.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/FormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/GhostDialog.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/FormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContentBundle/Controller/PageController.php
  src/Sulu/Bundle/ContentBundle/Resources/js/stores/WebspaceStore/WebspaceStore.js
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Controller/PageControllerTest.php
Labels: Feature

#4082 Make ColumnList, Table and Navigation more keyboard friendly
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Row.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/Table.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/tests/__snapshots__/Table.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Datagrid/tests/adapters/__snapshots__/TreeTableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/ContentBundle/Resources/js/views/WebspaceOverview/tests/__snapshots__/WebspaceOverview.test.js.snap
Labels: Enhancement
