Repository sulu/sulu, pull requests merged in 2019-03, with the labels that each got.

#4459 Use colspan instead of size in grid
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/ItemMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Section.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/Section.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Section.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/BaseItem.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Section.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/baseItem.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/Grid.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/tests/__snapshots__/Grid.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/PasswordConfirmation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Cell.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/__snapshots__/RoleAssignments.test.js.snap
  src/Sulu/Component/Content/Compat/Block/BlockPropertyWrapper.php
  src/Sulu/Component/Content/Compat/Property.php
  src/Sulu/Component/Content/Compat/PropertyInterface.php
  src/Sulu/Component/Content/Compat/Structure/LegacyPropertyFactory.php
  src/Sulu/Component/Content/Mapper/Translation/TranslatedProperty.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Metadata/PropertyMetadata.php
  src/Sulu/Component/Content/Metadata/SectionMetadata.php
  src/Sulu/Component/Content/Tests/Unit/Compat/Structure/LegacyPropertyFactoryTest.php
Labels: Enhancement

#4465 Fix closing of confirmation overlay for clearing the website cache
  src/Sulu/Bundle/WebsiteBundle/Controller/CacheController.php
Labels: Bug

#4460 Fix bug in Requester for nested objects
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
Labels: Bug

#4344 Fix media types configuration
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
Labels: Bug

#4471 Fix CKEditor preview for content that is not wrapped in an HTML tag
  CHANGELOG.md
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1551359256222.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1551863392508.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/app.min.1551863392508.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1551359256222.js
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1551863392508.css
  src/Sulu/Bundle/AdminBundle/Resources/public/dist/login.min.1551863392508.js
  src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.js
  src/Sulu/Bundle/AdminBundle/Resources/public/js/vendor/husky/husky.min.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/index.html.dist.twig
  src/Sulu/Bundle/AdminBundle/Resources/views/Security/login.html.dist.twig
Labels: Bug

#4442 Add resource store properties to list store options
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ListRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ListRouteBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ListRouteBuilderTest.php
Labels: Feature

#4469 Sulu core configuration: Remove required attribute from paths
  src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
Labels: Bug

#4450 Fix generation of inset thumbnails
  src/Sulu/Bundle/MediaBundle/Media/FormatLoader/BaseXmlFormatLoader.php
  src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader10.php
  src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader11.php
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/image-formats/version11.xml
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader10Test.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatLoader/XmlFormatLoader11Test.php
Labels: Bug

#4473 Fix smart-content to allow null data
  src/Sulu/Component/Content/Compat/Block/BlockProperty.php
  src/Sulu/Component/SmartContent/ContentType.php
  src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
Labels: Bug

#4464 Enable content manager to decide on crop for image formats
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/__snapshots__/ImageRectangleSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/ModifiableRectangle.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/modifiableRectangle.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/ModifiableRectangle.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/RectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/__snapshots__/ModifiableRectangle.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/__snapshots__/RectangleSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/__mocks__/withContainerSize.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaFormatStore/MediaFormatStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaFormatStore/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaFormatStore/tests/MediaFormatStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaFormatStore/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/CropOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/MediaDetails.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/cropOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/CropOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/FocusPointOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/MediaDetails.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/__snapshots__/MediaDetails.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaFormatControllerTest.php
Labels: Feature

#4433 Fix fresh User object comparison to the deserialized User object
  src/Sulu/Bundle/SecurityBundle/Entity/BaseUser.php
Labels: Bug

#4467 Fix single media selection content data for deleted media
  src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/SingleMediaSelectionTest.php
Labels: Bug

#4488 JMS Serializer: Handle DateTimeImmutable correctly
  src/Sulu/Component/Rest/Handler/DateHandler.php
Labels: Bug

#4490 Remove unused css files
  src/Sulu/Bundle/CustomUrlBundle/Resources/public/css/main.css
  src/Sulu/Bundle/CustomUrlBundle/Resources/public/css/main.min.css
  src/Sulu/Bundle/LocationBundle/Resources/public/css/main.css
  src/Sulu/Bundle/LocationBundle/Resources/public/css/main.min.css
  src/Sulu/Bundle/SearchBundle/Resources/public/css/main.css
  src/Sulu/Bundle/SearchBundle/Resources/public/css/main.min.css
  src/Sulu/Bundle/WebsiteBundle/Resources/public/css/main.css
  src/Sulu/Bundle/WebsiteBundle/Resources/public/css/main.min.css
Labels: Enhancement

#4487 Implement ExternalLink for CKEditor
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkBalloonView.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkCommand.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkPlugin.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/ExternalUnlinkCommand.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/constants.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/edit.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/link.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/plugins/ExternalLinkPlugin/unlink.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CKEditor5/tests/CKEditor5.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/colors.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
  webpack.config.js
Labels: Feature

#4493 Add webspace and portal name to template attributes
  src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
Labels: Feature

#4492 Remove request attributes from request analyzer resolver
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolver.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/RequestAnalyzerResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
  src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
  src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
  src/Sulu/Component/Webspace/Analyzer/RequestAnalyzerInterface.php
  src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
Labels: Enhancement

#4495 Set position of content section of Dialog to relative to hide overflow
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
Labels: Bug

#4477 Add overlaySize option to FormOverlayList and Builder
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormOverlayListRouteBuilderTest.php
Labels: Feature

#4482 Add setView for Admin Route object
  src/Sulu/Bundle/AdminBundle/Admin/Routing/Route.php
Labels: Feature
