Repository sulu/sulu, pull requests merged in 2019-05, with the labels that each got.

#4538 CustomUrl with redirect behavior redirects to HTTP schema
  CHANGELOG.md
  src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php
  src/Sulu/Component/CustomUrl/Routing/Enhancers/SeoEnhancer.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/RedirectEnhancerTest.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/SeoEnhancerTest.php
Labels: Bug

#4476 Add resourceStorePropertiesToFormStore option to FormOverlayList
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormOverlayListRouteBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormOverlayListRouteBuilderTest.php
Labels: Feature

#4535 Update js dependencies
  UPGRADE.md
  package.json
  webpack.config.js
Labels: Enhancement

#4545 Fix colspan of overlays in contact form
  src/Sulu/Bundle/ContactBundle/Resources/js/index.js
Labels: Bug

#4546 Allow to unpublish a page
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
Labels: Feature

#4547 Allow to create a contact with an account but without a position
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/__snapshots__/Input.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/SingleAutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#4548 Generate URL for ghost locales
  .circleci/config.yml
  package.json
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
  src/Sulu/Component/Content/Document/Subscriber/ResourceSegmentSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php
Labels: Bug

#4552 Allow nesting properties in forms and show preview in all page tabs
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Renderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Controller/AbstractExtensionController.php
  src/Sulu/Bundle/PageBundle/Controller/ExcerptController.php
  src/Sulu/Bundle/PageBundle/Controller/SeoController.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_excerpt.xml
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_seo.xml
  src/Sulu/Bundle/PageBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/PageBundle/Resources/config/serializer/Document.BasePageDocument.xml
  src/Sulu/Bundle/PageBundle/Resources/js/containers/Form/fields/SearchResult.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/Form/tests/fields/SearchResult.test.js
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ExcerptControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SeoControllerTest.php
Labels: Feature

#4553 Add reload button for preview
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
  src/Sulu/Bundle/PreviewBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/PreviewBundle/Resources/translations/admin.en.json
Labels: Feature

#4555 Add tab for snippet taxonomies
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/forms/snippet_taxonomies.xml
Labels: Feature

#4558 Add search field in ListOverlay
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/AbstractAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/ListOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/tests/ListOverlay.test.js
Labels: Enhancement

#4565 Rename snippet content type to snippet_selection
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/CategoryBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/test_page.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/with_snippet.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ContentTypesDumpCommandTest.php
  src/Sulu/Bundle/PersistenceBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/ResourceBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SearchBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/hotel_page.xml
  src/Sulu/Bundle/TagBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/simple.xml
Labels: Enhancement

#4551 Add possibility to define a mailto link
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/plugins/ExternalLinkPlugin/ExternalLinkOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/plugins/ExternalLinkPlugin/__snapshots__/ExternalLinkOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/CopyLocaleDialog.test.js.snap
Labels: Feature

#4561 Add more fields to snippet list
  src/Sulu/Bundle/SnippetBundle/Resources/config/lists/snippets.xml
Labels: Enhancement

#4566 Rename contact content type to contact_account_selection
  UPGRADE.md
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php
  src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
  src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactAccountSelectionTest.php
Labels: Enhancement

#4527 Disallow interactions with static elements
  .eslintrc.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/Backdrop.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Backdrop/tests/__snapshots__/Backdrop.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Column.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdown.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ToolbarDropdownList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Column.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/toolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/__snapshots__/ImageRectangleSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/navigation.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/tests/__snapshots__/Popover.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/ModifiableRectangle.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/__snapshots__/ModifiableRectangle.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/__snapshots__/RectangleSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/Select.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/Snackbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/__snapshots__/ResourceLocatorHistory.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardOverviewAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/DropzoneOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/__snapshots__/MultiMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/tests/__snapshots__/WebspaceSelect.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/__snapshots__/PageList.test.js.snap
Labels: Enhancement

#4567 Add contact details fields to contact form
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/SingleItemSection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/DropdownButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/tests/DropdownButton.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/tests/__snapshots__/DropdownButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/field.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/url.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/types.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Api/Account.php
  src/Sulu/Bundle/ContactBundle/Api/Contact.php
  src/Sulu/Bundle/ContactBundle/Api/Email.php
  src/Sulu/Bundle/ContactBundle/Api/Fax.php
  src/Sulu/Bundle/ContactBundle/Api/Phone.php
  src/Sulu/Bundle/ContactBundle/Api/SocialMediaProfile.php
  src/Sulu/Bundle/ContactBundle/Api/Url.php
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/Entity/EmailType.php
  src/Sulu/Bundle/ContactBundle/Entity/FaxType.php
  src/Sulu/Bundle/ContactBundle/Entity/PhoneType.php
  src/Sulu/Bundle/ContactBundle/Entity/SocialMediaProfileType.php
  src/Sulu/Bundle/ContactBundle/Entity/UrlType.php
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/account_details.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/contact_details.xml
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/ContactDetails.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/Email.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/Fax.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/Field.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/Phone.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/README.md
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/SocialMedia.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/Website.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/field.scss
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/index.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/tests/ContactDetails.test.js
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/tests/__snapshots__/ContactDetails.test.js.snap
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/types.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/Form/fields/ContactDetails.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/Form/tests/fields/ContactDetails.test.js
  src/Sulu/Bundle/ContactBundle/Resources/js/index.js
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Feature

#4562 Fix BinaryFileResponse of html files
  CHANGELOG.md
  src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
Labels: Bug

#4549 Fix app ready by remove bundleReady and startAdmin manually
  .eslintrc.json
  .gitattributes
  UPGRADE.md
  assets/admin/index.js
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/Bundles.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Bundles/tests/Bundles.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/Initializer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Initializer/tests/Initializer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/index.js
  src/Sulu/Bundle/ContactBundle/Resources/js/index.js
  src/Sulu/Bundle/CustomUrlBundle/Resources/js/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/index.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/index.js
  src/Sulu/Bundle/SnippetBundle/Resources/js/index.js
  src/Sulu/Bundle/WebsiteBundle/Resources/js/index.js
  webpack.config.js
Labels: Bug

#4569 Reset page of medias to one when returning from MediaDetails view
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/MediaDetails.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaDetails/tests/MediaDetails.test.js
Labels: Bug

#4570 Remove wrong call to translate for non-translatable social media services
  src/Sulu/Bundle/ContactBundle/Resources/js/index.js
Labels: Bug

#4540 Fix copying of teaser selection in WebspaceCopyCommand
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Command/WebspaceCopyCommand.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Command/WebspaceCopyCommandTest.php
  src/Sulu/Bundle/ContentBundle/Tests/app/Resources/pages/teasers.xml
Labels: Bug

#4575 Fix missing webspace and active item on back navigation when page form was directly loaded
  .travis.yml
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/FormRouteBuilderTrait.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/UserStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/UserStore/tests/UserStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormRouteBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ResourceTabRouteBuilderTest.php
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
Labels: Enhancement

#4573 Resolve taxonomies in snippet_selection ContentType
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Bundle/SnippetBundle/Snippet/SnippetResolver.php
  src/Sulu/Bundle/SnippetBundle/Snippet/SnippetResolverInterface.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetContentTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/SnippetResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverInterface.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Twig/ContentTwigExtensionTest.php
  src/Sulu/Component/Content/Compat/PageInterface.php
  src/Sulu/Component/Content/Compat/Structure/PageBridge.php
  src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Tests/Unit/Compat/Structure/StructureBridgeTest.php
Labels: Feature

#4579 Fix controller reference validation with FQCN
  .travis.yml
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Command/ValidateWebspacesCommand.php
Labels: Bug

#4571 Fix language switcher for static routes
  CHANGELOG.md
  src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolverTest.php
Labels: Bug

#4572 Fix false 406 status code for controller InvalidArgumentExceptions
  CHANGELOG.md
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
Labels: Bug

#4582 Fix export of MultiSelectionStore
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
Labels: Enhancement
