Repository sulu/sulu, pull requests merged in 2019-11, with the labels that each got.

#4866 Clear cache if image formats are changed
  src/Sulu/Bundle/MediaBundle/DependencyInjection/AbstractImageFormatCompilerPass.php
Labels: Bug

#4871 Fix sitemap provider tags definition
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
Labels: Bug

#4880 Add autowiring of LocalizationManagerInterface
  src/Sulu/Bundle/CoreBundle/Resources/config/localization.xml
Labels: Enhancement

#4882 Fix crashing when media_selection contains invalid value
  src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/MediaSelectionContentTypeTest.php
Labels: Bug

#4868 Consider webspace when creating an internal redirect
  src/Sulu/Bundle/WebsiteBundle/Resources/config/website.xml
  src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
Labels: Bug

#4890 Add method to handle routables without the routable interface
  UPGRADE.md
  src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php
  src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php
  src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
  src/Sulu/Bundle/RouteBundle/Manager/RouteManagerInterface.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
Labels: Enhancement

#4892 Introduce null generator for route-bundle and fix the history overlay
  src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/RouteBundle/DependencyInjection/RouteGeneratorCompilerPass.php
  src/Sulu/Bundle/RouteBundle/Entity/Route.php
  src/Sulu/Bundle/RouteBundle/Generator/NullRouteGenerator.php
  src/Sulu/Bundle/RouteBundle/Resources/config/generator.xml
Labels: Feature

#4894 Improve structureResolver getExtensionData from document
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
Labels: Enhancement

#4872 Fix loading of unbuilt js files in chrome over http2 push
  composer.json
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
Labels: Enhancement

#4899 Fix missing reset of URL if multiple external links are set in CKEditor5
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
Labels: Bug

#4900 Extract teaser attributes to getAttribute method
  src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
Labels: Enhancement

#4909 Fix services in SuluHttpCacheExtension tests
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
Labels: Bug

#4908 Provide a default user provider for the firewall
  config/packages/security_admin.yaml
  config/packages/test/security_admin.yaml
Labels: Enhancement

#4897 Add the SymfonyTestsListener to all phpunit configuration files
  phpunit.xml.dist
  src/Sulu/Bundle/AudienceTargetingBundle/phpunit.xml.dist
  src/Sulu/Bundle/CategoryBundle/phpunit.xml.dist
  src/Sulu/Bundle/ContactBundle/phpunit.xml.dist
  src/Sulu/Bundle/CoreBundle/phpunit.xml.dist
  src/Sulu/Bundle/CustomUrlBundle/phpunit.xml.dist
  src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist
  src/Sulu/Bundle/HttpCacheBundle/phpunit.xml.dist
  src/Sulu/Bundle/LocationBundle/phpunit.xml.dist
  src/Sulu/Bundle/MarkupBundle/phpunit.xml.dist
  src/Sulu/Bundle/MediaBundle/phpunit.xml.dist
  src/Sulu/Bundle/PageBundle/phpunit.xml.dist
  src/Sulu/Bundle/PersistenceBundle/phpunit.xml.dist
  src/Sulu/Bundle/PreviewBundle/phpunit.xml.dist
  src/Sulu/Bundle/RouteBundle/phpunit.xml.dist
  src/Sulu/Bundle/SearchBundle/phpunit.xml.dist
  src/Sulu/Bundle/SecurityBundle/phpunit.xml.dist
  src/Sulu/Bundle/SnippetBundle/phpunit.xml.dist
  src/Sulu/Bundle/TagBundle/phpunit.xml.dist
  src/Sulu/Bundle/WebsiteBundle/phpunit.xml.dist
Labels: Enhancement

#4911 Fix http cache directory for symfony cache
  src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php
Labels: Bug

#4869 Remove templating requirement
  UPGRADE.md
  composer.json
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/SearchBundle/Tests/Resources/TestBundle/Controller/SearchController.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
  templates/base.html.twig
Labels: Enhancement

#4915 Show MimeTypeIndicator instead of infinite loader if image cannot be loaded for a reason
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
Labels: Bug

#4925 find and findChildren should return either a NavigationItem or null
  src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
Labels: Enhancement
