Repository sulu/sulu, pull requests merged in 2019-08, with the labels that each got.

#4660 Remove loader in settings tab when versioning is deactivated
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
Labels: Enhancement

#4659 Remove obsolete fieldsActions
  src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactMediaController.php
  src/Sulu/Bundle/ResourceBundle/Controller/FilterController.php
Labels: Enhancement

#4635 Filter media by types in media selection overlay
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelectionOverlay/MultiMediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelectionOverlay/tests/MultiMediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/utils/MediaSelectionHelper/convertMediaTypesFromParams.js
  src/Sulu/Bundle/MediaBundle/Resources/js/utils/MediaSelectionHelper/index.js
Labels: Enhancement

#4640 Increase phpstan level from 0 to 1 in phpstan.neon
  phpstan.neon
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactTitleController.php
  src/Sulu/Bundle/ContactBundle/Controller/PositionController.php
  src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadCountries.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentFixtureLoader.php
  src/Sulu/Bundle/MediaBundle/Entity/File.php
  src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Focus/Focus.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/PageBundle/Content/Types/PageSelection.php
  src/Sulu/Bundle/PageBundle/Controller/VersionController.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php
  src/Sulu/Component/Content/Compat/Structure.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
  src/Sulu/Component/Snippet/Import/SnippetImport.php
Labels: Enhancement

#4665 Disallow editing of resource locator on homepage
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
Labels: Enhancement

#4668 Add dependency cruiser with rules
  .circleci/config.yml
  dependency-cruiser.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/Overlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/Popover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/tests/RectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Option.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/tests/withContainerSize.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/withContainerSize/withContainerSize.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/structureStrategies/FlatStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/structureStrategies/TreeStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/MultiSelectionStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/DOM/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/DOM/__mocks__/afterElementsRendered.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/DOM/afterElementsRendered.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/DOM/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/DOM/tests/afterElementsRendered.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/react/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/react/buildHocDisplayName.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/react/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/react/tests/buildHocDisplayName.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/TeaserSelection.js
Labels: Enhancement

#4667 Fix generation of URL for child pages
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
Labels: Bug

#4661 Hide UI elements with missing permission
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/tests/withSidebar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Sidebar/withSidebar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/withToolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/withToolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/getViewKeyFromRoute.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/getViewKeyFromRoute.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/AudienceTargetingBundle/Admin/AudienceTargetingAdmin.php
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/CustomUrlBundle/Admin/CustomUrlAdmin.php
  src/Sulu/Bundle/CustomUrlBundle/Resources/config/admin.xml
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
  src/Sulu/Bundle/WebsiteBundle/Admin/WebsiteAdmin.php
  src/Sulu/Component/Webspace/Manager/WebspaceCollection.php
Labels: Feature

#4673 Fix rendering contact add form
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
Labels: Bug

#4670 Add loader to MediaCard while image is loading
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/MediaCard.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/mediaCard.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/MediaCard.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/tests/__snapshots__/MediaCard.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardOverviewAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Enhancement

#4680 Use permissions from security context if no object security has been set
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/RolePermissions.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/tests/RolePermissions.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/tests/__snapshots__/RolePermissions.test.js.snap
  src/Sulu/Bundle/SecurityBundle/Resources/js/index.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/stores/SecurityContextStore/SecurityContextStore.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/types.js
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
Labels: Bug

#4683 Fix controller validation definition as fcqn
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
Labels: Bug

#4687 Rename security column of se_roles table to securitySystem for MySQL 8.0 compatibility
  UPGRADE.md
  appveyor.yml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/BaseRole.orm.xml
Labels: Enhancement

#4691 Add 'getAllLocales' to webspace-manager
  UPGRADE.md
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Build/NodeOrderBuilderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Command/MaintainResourceLocatorCommandTest.php
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Manager/Manager/CustomUrlManagerTest.php
  src/Sulu/Component/Localization/Manager/LocalizationManager.php
  src/Sulu/Component/Localization/Manager/LocalizationManagerInterface.php
  src/Sulu/Component/Localization/Provider/LocalizationProvider.php
  src/Sulu/Component/Localization/Provider/LocalizationProviderInterface.php
  src/Sulu/Component/Webspace/Analyzer/Attributes/ParameterRequestProcessor.php
  src/Sulu/Component/Webspace/Manager/WebspaceCollection.php
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
Labels: Enhancement

#4695 Fix target entity of target-group association of FileVersion
  src/Sulu/Bundle/MediaBundle/EventListener/MediaAudienceTargetingSubscriber.php
  src/Sulu/Bundle/MediaBundle/Resources/config/audience_targeting.xml
Labels: Bug

#4699 Avoid bc break in twig templates by provide uuid and id properties for pages
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationItem.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
Labels: Enhancement

#4705 Fix display issues with pin button of navigation
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/navigation.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/__snapshots__/Navigation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/__snapshots__/Navigation.test.js.snap
Labels: Bug

#4709 Update to latest JS packages
  .browserslistrc
  .eslintrc.json
  UPGRADE.md
  flow-typed/npm/jest_v24.x.x.js
  index.js
  package.json
  postcss.config.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/checkbox.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Button.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Select.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ChangelogLine.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/README.md
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/item.scss
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  styleguide.config.js
  stylelint.config.js
  tests/js/mocks/fos-jsrouting-router.js
  webpack.config.js
Labels: Enhancement

#4702 Hide buttons in column list if view permissions for pages is missing
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ItemButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/ColumnList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/ColumnListAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/ColumnListAdapter.test.js.snap
  src/Sulu/Bundle/PageBundle/Controller/NodeController.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepositoryInterface.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
Labels: Enhancement

#4710 Fix PageList in Safari
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/pageList.scss
Labels: Bug
