Repository sulu/sulu, pull requests merged in 2019-10, with the labels that each got.

#4771 Check Preview token and generate one if not exist
  src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
Labels: Enhancement

#4762 Extend WebsiteController from AbstractController instead of deprecated Controller class
  UPGRADE.md
  src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
  src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-lifetime-enhancer.xml
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
Labels: Enhancement

#4775 Fix localization serialization in webspaces request
  src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/WebspaceControllerTest.php
Labels: Bug

#4760 Add profile and security contexts rest routes to api endpoint
  .travis.yml
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SecurityBundle/Controller/ContextsController.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ProfileControllerTest.php
Labels: Bug

#4781 Fix deprecated RestController viewHandler
  src/Sulu/Component/Rest/AbstractRestController.php
  src/Sulu/Component/Rest/RestControllerTrait.php
Labels: Bug

#4776 Make webspace manager environment variable optional
  UPGRADE.md
  src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
Labels: Enhancement

#4779 Make array serializer service public
  src/Sulu/Bundle/CoreBundle/Resources/config/serializer.xml
  src/Sulu/Component/Serializer/ArraySerializer.php
Labels: Enhancement

#4794 Improve phpdoc for static code analyzers
  src/Sulu/Bundle/ContactBundle/Entity/Account.php
  src/Sulu/Bundle/ContactBundle/Entity/Address.php
  src/Sulu/Bundle/ContactBundle/Entity/BankAccount.php
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactInterface.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManagerInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
  src/Sulu/Bundle/TestBundle/Testing/CreateClientTrait.php
  src/Sulu/Component/Webspace/Webspace.php
Labels: Enhancement

#4793 Add computed locales to list view
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
Labels: Feature

#4810 Fix getContainer and initPhpCr for tests
  src/Sulu/Bundle/TestBundle/Testing/ContainerTrait.php
  src/Sulu/Bundle/TestBundle/Testing/PhpCrInitTrait.php
Labels: Bug

#4777 Fix sitemap dumper
  UPGRADE.md
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Sitemap/PagesSitemapProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Sitemap/PagesSitemapProviderTest.php
  src/Sulu/Bundle/TestBundle/Testing/ContainerTrait.php
  src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
  src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/command.xml
  src/Sulu/Bundle/WebsiteBundle/Resources/config/sitemap.xml
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap.xml.twig
  src/Sulu/Bundle/WebsiteBundle/Sitemap/AbstractSitemapProvider.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/Provider/PagesSitemapProvider.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderInterface.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPool.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPoolInterface.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapUrl.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperInterface.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererInterface.php
  src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPoolTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
Labels: Bug, Enhancement

#4796 Fix exception message in ViewNotFoundException
  src/Sulu/Bundle/AdminBundle/Exception/ViewNotFoundException.php
Labels: Enhancement

#4795 Fix account interface function types
  UPGRADE.md
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Entity/Account.php
  src/Sulu/Bundle/ContactBundle/Entity/AccountInterface.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
Labels: Bug

#4800 Fix no host in parse_url of PreviewRenderer
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Search/SearchManagerTest.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
Labels: Bug

#4812 Optimize image output
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
Labels: Enhancement

#4818 Fix image width calculation problems with float values
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Scaler/Scaler.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Scaler/ScalerTest.php
Labels: Bug

#4739 Fix location content type default map provider option
  CHANGELOG.md
  src/Sulu/Bundle/LocationBundle/Resources/public/dist/components/location/main.js
  src/Sulu/Bundle/LocationBundle/Resources/public/js/components/location/main.js
  src/Sulu/Bundle/LocationBundle/Resources/views/Template/content-types/location.html.twig
Labels: Bug

#4803 Fix SingleAccountSelection ContentType
  src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php
  src/Sulu/Bundle/ContactBundle/Tests/Unit/SingleAccountSelectionTest.php
Labels: Bug

#4828 removed storageOptions param in getFormats call
  src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
Labels: Bug

#4829 Resolve persistence-bundle entities in references option of doctrine schemas
  src/Sulu/Bundle/CoreBundle/Resources/config/doctrine.xml
  src/Sulu/Bundle/PersistenceBundle/DependencyInjection/Compiler/ResolveTargetEntitiesPass.php
  src/Sulu/Component/Doctrine/ReferencesOption.php
Labels: Bug

#4832 Make getTestUser function static
  src/Sulu/Bundle/TestBundle/Testing/TestUserTrait.php
Labels: Enhancement

#4787 Fix optional ffmpeg configuration
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
Labels: Enhancement

#4831 Show proper error message when not available default type is set on a block
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/complex.xml
  src/Sulu/Component/Content/Exception/InvalidBlockDefaultTypeException.php
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
  tests/Resources/DataFixtures/Page/template_with_invalid_block_default_type.xml
Labels: Enhancement

#4836 Fix templating error
  composer.json
Labels: Bug

#4837 Improve assert http status for client phpstan return type
  src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
Labels: Enhancement

#4835 Use ResourceLocatorStrategy in UI based on webspace configuration
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/EventListener/WebspaceSerializeEventSubscriber.php
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/stores/webspaceStore/types.js
  src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/loadResourceLocatorInputTypeByWebspace.js
  src/Sulu/Bundle/PageBundle/Resources/js/utils/Webspace/tests/loadResourceLocatorInputTypeByWebspace.test.js
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/WebspaceControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/EventListener/WebspaceSerializeEventSubscriberTest.php
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
Labels: Bug

#4843 Avoid dirty state and multiple request when opening empty smart content
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SmartContent.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/FilterOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContent.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/stores/smartContentConfigStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/FilterOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/SmartContent.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/SmartContentConfigStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/stores/smartContentConfigStore.test.js
Labels: Bug

#4814 Fix missing webspace when page is deleted in form
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
Labels: Bug

#4842 Fix CollectionRepresentation serialization in website context
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/serializer.xml
  src/Sulu/Component/Serializer/RepresentationSubscriber.php
Labels: Bug

#4778 Fix target group evaluator without webspace
  src/Sulu/Bundle/AudienceTargetingBundle/TargetGroup/TargetGroupEvaluator.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/TargetGroupEvaluatorTest.php
Labels: Bug

#4834 Add branch aliases for development
  composer.json
Labels: Enhancement

#4752 Fix authentication handler redirect
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/SecurityBundle/Security/AuthenticationHandler.php
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/LoginControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationEntryPointTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationHandlerTest.php
Labels: Bug

#4106 Ignore required fields when initialize webspace
  src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
  src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
Labels: Bug

#4757 Open item details on double-click in ColumnListAdapter
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Column.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/ColumnList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/adapters/ColumnListAdapter.js
Labels: Enhancement

#4848 Register specific bundles only if they exist in TestKernel
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
Labels: Enhancement

#4847 Implement a command that downloads the current JS build
  composer.json
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
Labels: Enhancement, Feature

#4851 Remove symfony.lock file from gitignore after create-project
  src/Sulu/Bundle/CoreBundle/Composer/ScriptHandler.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Rule/PageRuleTest.php
Labels: Enhancement

#4853 Rename test files to match their corresponding file names
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/registries/formToolbarActionRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/registries/listToolbarActionRegistry.test.js
Labels: Enhancement

#4852 Remove unused code from NavigationItems
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
Labels: Enhancement

#4857 Add path prefix to media url
  src/Sulu/Bundle/MediaBundle/Media/Storage/S3Storage.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/S3StorageTest.php
Labels: Bug

#4856 Set default type on existing entity without type
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
Labels: Bug

#4859 Fix branch aliases for development
  composer.json
Labels: Bug
