Repository sulu/sulu, pull requests merged in 2019-06, with the labels that each got.

#4585 Make click area of search button in List bigger
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
Labels: Enhancement

#4550 Fix failing ColumnList after deleting the last selected page
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/PageBundle/Content/PageSelectionContainer.php
  src/Sulu/Bundle/PageBundle/Controller/NodeController.php
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/SmartContentQueryBuilderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Content/PageSelectionContainerTest.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Navigation/NavigationTest.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/SmartContent/ContentDataItem.php
  src/Sulu/Component/Content/SmartContent/PageDataProvider.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
Labels: Bug

#4584 List and assign contacts to accounts
  src/Sulu/Bundle/AdminBundle/Admin/NavigationRegistry.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ResourceTabRouteBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/Tabs.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/NavigationRegistryTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ResourceTabRouteBuilderTest.php
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/account_details.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/account_contacts.xml
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
Labels: Feature

#4588 Fix tests for new enzyme version
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/tests/WebspaceSelect.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/tests/__snapshots__/WebspaceSelect.test.js.snap
Labels: Bug

#4592 Add loadExcerpt to snippet twig extension and fix loadExcerpt for pages
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Twig/SnippetTwigExtensionTest.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtension.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtensionInterface.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverInterface.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolverTest.php
Labels: Bug, Feature

#4601 Fix ckeditor dependency error
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: Bug

#4605 Fix sulu document init routes generation
  src/Sulu/Component/Webspace/Document/Initializer/WebspaceInitializer.php
Labels: Bug

#4596 Handle conflict if other user has changed snippet or page in the mean time
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Bug

#4610 Fix migration of teaser with other properties
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201905071542.php
Labels: Bug
