Repository sulu/sulu, pull requests merged in 2019-09, with the labels that each got.

#4651 Upgrade KernelTestCase class to Symfony KernelTestCase
  UPGRADE.md
  bin/runtests
  phpstan.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/CachingTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/TargetGroupControllerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/BaseTestCase.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Media/Storage/S3StorageTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
  src/Sulu/Bundle/PreviewBundle/Tests/Functional/Preview/Renderer/PreviewRendererTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/BaseFunctionalTestCase.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Command/SnippetLocaleCopyCommandTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
  src/Sulu/Bundle/TestBundle/Testing/ContainerTrait.php
  src/Sulu/Bundle/TestBundle/Testing/CreateClientTrait.php
  src/Sulu/Bundle/TestBundle/Testing/GeneratePhpunitConfig.php
  src/Sulu/Bundle/TestBundle/Testing/KernelTestCase.php
  src/Sulu/Bundle/TestBundle/Testing/KernelTrait.php
  src/Sulu/Bundle/TestBundle/Testing/PhpCrInitTrait.php
  src/Sulu/Bundle/TestBundle/Testing/PurgeDatabaseTrait.php
  src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
  src/Sulu/Bundle/TestBundle/Testing/TestUserTrait.php
  src/Sulu/Bundle/TestBundle/Testing/WebsiteTestCase.php
  src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
Labels: Enhancement

#4718 Fix height of list under WebspaceTabs
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ListOverlay/listOverlay.scss
Labels: Bug

#4714 Remove React deprecations
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/RectangleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Select.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/Navigation.js
Labels: Enhancement

#4720 Make AdapterSwitch in PageList clickable
  src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/webspaceTabs.scss
Labels: Bug

#4717 Show errors with message
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/Snackbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/snackbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/Snackbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/__snapshots__/Toolbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/stores/ToolbarStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/formOverlayList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Feature

#4726 Fix missing occurs properties in forms
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/blocks.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
Labels: Bug

#4634 Remove sensio labs framework extra bundle requirement
  composer.json
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/prod/doctrine.yaml
  phpunit.xml.dist
  src/Sulu/Bundle/AudienceTargetingBundle/Controller/TargetGroupController.php
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/CategoryBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/PageBundle/Controller/NodeController.php
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PageBundle/Controller/VersionController.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/PageBundle/Resources/config/routing_versioning_api.yml
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/TagBundle/Controller/TagController.php
  src/Sulu/Bundle/TagBundle/Resources/config/routing_api.yml
Labels: Enhancement

#4730 Add ToolbarAction to create dropdowns
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteDraftToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DropdownToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/DropdownToolbarAction.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DropdownToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/copyLocaleAction.scss
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleDialog.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/EditToolbarAction.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/__snapshots__/CopyLocaleDialog.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/CopyLocaleDialog.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/EditToolbarAction.js
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
Labels: Enhancement

#4732 Remove NodeController
  src/Sulu/Bundle/PageBundle/Controller/NodeController.php
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PageBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/PageBundle/Resources/config/serializer/Document.BasePageDocument.xml
  src/Sulu/Bundle/PageBundle/Serializer/Subscriber/StructureSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerFieldsTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/NodeControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerFieldsTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Component/Content/Repository/Content.php
Labels: Enhancement

#4024 Add support for multi image format support jpg, png, webp
  .gitignore
  UPGRADE.md
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheInterface.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImageConverterInterface.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/LocalFormatCacheTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
Labels: Feature

#4735 Add class for ToolbarAction
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Admin/Routing/DropdownToolbarAction.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/TogglerToolbarAction.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ToolbarAction.php
  src/Sulu/Bundle/AdminBundle/Admin/Routing/ToolbarActionsRouteBuilderTrait.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DropdownToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DropdownToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/DropdownToolbarActionSubscriber.php
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/TogglerToolbarActionSubscriber.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormOverlayListRouteBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/FormRouteBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/ListRouteBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/PreviewFormRouteBuilderTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Admin/AudienceTargetingAdmin.php
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/CustomUrlBundle/Admin/CustomUrlAdmin.php
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/AdminControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
  src/Sulu/Bundle/WebsiteBundle/Admin/WebsiteAdmin.php
Labels: Enhancement

#4749 Fix loading of routes_admin.yaml and routes_website.yaml
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Bug

#4747 Add webspace and target group selection to preview
  src/Sulu/Bundle/AdminBundle/Admin/Routing/PreviewFormRouteBuilder.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Routing/PreviewFormRouteBuilderTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php
  src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/__snapshots__/Preview.test.js.snap
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/index.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
Labels: Feature

#4751 Remove RequestLocaleTranslator service
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorEventListener.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListener.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorEventListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Translator/RequestLocaleTranslatorTest.php
  src/Sulu/Bundle/WebsiteBundle/Translator/RequestLocaleTranslator.php
  src/Sulu/Component/Webspace/Analyzer/Attributes/PortalInformationRequestProcessor.php
  src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
Labels: Enhancement

#3794 Replace Country entity with Symfony Intl Regionbundle
  UPGRADE.md
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContactBundle/Api/Address.php
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/CountryController.php
  src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadCountries.php
  src/Sulu/Bundle/ContactBundle/DataFixtures/countries.xml
  src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/Address.php
  src/Sulu/Bundle/ContactBundle/Entity/AddressRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/Country.php
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Address.orm.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Country.orm.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/accounts.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/contacts.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/ContactBundle/Resources/js/index.js
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactMediaControllerTest.php
Labels: Enhancement

#4745 Fix container build with unused media environment parameters
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
Labels: Enhancement

#4756 Remove symfony/force-lowest and fix some min requirements
  composer.json
Labels: Enhancement

#4761 Drop support for symfony 3.4
  UPGRADE.md
  composer.json
Labels: Enhancement

#4724 Update dependencies pagerfanta, php-http, toflar/psr6-symfony-http-cache-store, php-ffmpeg
  composer.json
Labels: Enhancement

#4764 Upgrade DoctrineFixturesBundle to newest verison
  composer.json
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateRoleCommandTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Command/CreateUserCommandTest.php
Labels: Enhancement

#4748 Improve test bundle for easier usage in projects
  .travis.yml
  UPGRADE.md
  composer.json
  phpstan.neon
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/AppCache.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/CachingTest.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/SearchIntegration/SearchIntegrationTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Mapper/ContentMapperSnippetTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Search/BaseTestCase.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Search/SearchManagerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Snippet/SnippetRepositoryTest.php
  src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php
  src/Sulu/Bundle/TestBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/config.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/context_admin.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/services.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
  src/Sulu/Bundle/TestBundle/Resources/config/test_user_provider.xml
  src/Sulu/Bundle/TestBundle/Testing/AssertHttpStatusCodeTrait.php
  src/Sulu/Bundle/TestBundle/Testing/PhpCrInitTrait.php
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
  src/Sulu/Bundle/TestBundle/Testing/TestVoter.php
Labels: Enhancement

#4672 Add redirect to locale-prefix for partial match requests
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
Labels: Bug
