Repository sulu/sulu, pull requests merged in 2020-01, with the labels that each got.

#4953 Swap render index arguments
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumper.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapDumperTest.php
Labels: Bug

#4914 Add remove method to route-repository
  UPGRADE.md
  src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php
  src/Sulu/Bundle/RouteBundle/Entity/RouteRepositoryInterface.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Entity/RouteRepositoryTest.php
Labels: Enhancement

#4863 Add optional svg support
  composer.json
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/services_imagine_svg.xml
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/files/sulu.svg
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
Labels: Feature

#4862 Add media-adapter for vips
  composer.json
  phpstan.neon
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services_imagine_vips.xml
Labels: Feature

#4968 Improve performance for one layered images
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
Labels: Enhancement

#4978 Fix bug when loading items in admin for smart content with properties param
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/OptionMetadata.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
Labels: Bug

#4980 Add nullable to UserBlameInterface getCreator and getChanger functions
  src/Sulu/Component/Persistence/Model/UserBlameInterface.php
  src/Sulu/Component/Persistence/Model/UserBlameTrait.php
Labels: Enhancement

#4975 Allow blocks in blocks
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/sortableBlockList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/blockPreviewTransformers/StringBlockPreviewTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/blockPreviewTransformers/StripHtmlBlockPreviewTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/fieldBlocks.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/blockPreviewTransformers/StringBlockPreviewTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/blockPreviewTransformers/__snapshots__/StringBlockPreviewTransformer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/blockPreviewTransformers/__snapshots__/StripHtmlBlockPreviewTransformer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_nested_blocks.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/FieldBlocks/blockPreviewTransformers/singleMediaSelectionBlockPreviewTransformer.scss
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
  tests/Resources/DataFixtures/Page/template_with_nested_blocks.xml
Labels: Feature

#4991 Introduce proper limit for snippet content type and use pagination
  src/Sulu/Bundle/SnippetBundle/Resources/public/dist/components/snippet-content/main.js
  src/Sulu/Bundle/SnippetBundle/Resources/public/js/components/snippet-content/main.js
Labels: Bug

#4983 Fix conflict message when referenced snippet is being deleted
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManagerInterface.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
Labels: Bug

#4984 Rename display_condition option of toolbar actions of Form view to visible_condition
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteDraftToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
Labels: Enhancement

#4999 Fix TestUserProvider supportsClass call
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
Labels: Bug

#4998 Fix assigning more than 10 teasers when using elasticsearch
  CHANGELOG.md
  src/Sulu/Bundle/ContentBundle/Teaser/ContentTeaserProvider.php
  src/Sulu/Bundle/ContentBundle/Tests/Unit/Teaser/ContentTeaserProviderTest.php
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
Labels: Bug

#4927 add used PHP extensions to composer.json
  composer.json
Labels: Bug

#5012 Update to jest 25 for better testing performance
  flow-typed/npm/jest_v24.x.x.js
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/tests/__snapshots__/ColorPicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/Email.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Phone/tests/Phone.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/Option.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/Option.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/tests/Toggler.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/tests/__snapshots__/Toggler.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/SingleMediaUpload.test.js
Labels: DX, Technical Debt

#5013 Remove unneeded type attribute in script tags
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/views/Template/hit-script.html.twig
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/matomo/head-close.html.twig
Labels: DX, Technical Debt

#5018 Disallow add, delete and edit operations on SystemCollections
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/CollectionStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/tests/CollectionStore.test.js
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
Labels: Bug

#5015 Fix width of content in blocks to avoid overflow
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
Labels: Bug

#5010 Fix fast pagination of List view
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/loadingStrategies/AbstractLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/structureStrategies/ColumnStructureStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/structureStrategies/ColumnStructureStrategy.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/RequestPromise.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/RequestPromise.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/index.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
Labels: Bug

#5023 Add comment to explain purpose of SULU_ADMIN_EMAIL environment variable
  .env
Labels: DX
