Repository sulu/sulu, pull requests merged in 2020-03, with the labels that each got.

#5089 Add size and skin props to Chip component
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/Chip.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/chip.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/Chip.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/__snapshots__/Chip.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/MultiAutoComplete.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/multiAutoComplete.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/MultiAutoComplete.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiAutoComplete/tests/__snapshots__/MultiAutoComplete.test.js.snap
Labels: Feature

#4939 Add PageTreeRoute
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/SmartContent.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/index.js
  src/Sulu/Bundle/RouteBundle/Command/MovePageTreeCommand.php
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/RouteBundle/DependencyInjection/SuluRouteExtension.php
  src/Sulu/Bundle/RouteBundle/Document/Subscriber/PageTreeRouteSubscriber.php
  src/Sulu/Bundle/RouteBundle/Document/Subscriber/RoutableSubscriber.php
  src/Sulu/Bundle/RouteBundle/PageTree/NullPageTreeUpdater.php
  src/Sulu/Bundle/RouteBundle/PageTree/PageTreeMoverInterface.php
  src/Sulu/Bundle/RouteBundle/PageTree/PageTreeRepository.php
  src/Sulu/Bundle/RouteBundle/PageTree/PageTreeTrait.php
  src/Sulu/Bundle/RouteBundle/PageTree/PageTreeUpdaterInterface.php
  src/Sulu/Bundle/RouteBundle/Resources/config/command.xml
  src/Sulu/Bundle/RouteBundle/Resources/config/page_tree_move.xml
  src/Sulu/Bundle/RouteBundle/Resources/config/page_tree_update.xml
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/fields/PageTreeRoute.js
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/PageTreeRoute.test.js
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/__snapshots__/PageTreeRoute.test.js.snap
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/types.js
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
  src/Sulu/Bundle/RouteBundle/Resources/js/package.json
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Content/PageTreeRouteContentTypeTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
  src/Sulu/Component/Route/Document/Behavior/RoutableBehavior.php
Labels: Feature

#5092 Add generation for route field-type
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
  src/Sulu/Bundle/RouteBundle/DependencyInjection/SuluRouteExtension.php
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
Labels: DX

#5100 Fix display column options in List container even when searching is disabled
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
Labels: Bug

#5105 Fix ResourceRouteRegistry to accept boxed observable inside of parameters
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/registries/resourceRouteRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
Labels: Bug

#5103 Fix support for custom url protocols
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
  src/Sulu/Bundle/PageBundle/Content/Types/Url.php
Labels: Bug

#5107 Fix sorting of category medias
  UPGRADE.md
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationMedia.php
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslationMedia.orm.xml
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
Labels: Bug

#5109 Fix disabled request analyzer for esi requests
  src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/RouterListenerTest.php
Labels: Bug

#5108 Register CategoryManagerInterface::class as alias for sulu_category.category_manager service
  src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
Labels: DX

#5087 Fix aliases for joins without relations
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineJoinDescriptor.php
  src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
  src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/Resources/options.xml
Labels: Bug

#5110 Allow usage of twig ^3.0
  composer.json
Labels: DX

#5112 Replace stof/doctrine-extensions-bundle with antishov/doctrine-extensions-bundle
  composer.json
Labels: DX

#5106 Add single-category-selection configuration
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/CategoryBundle/Content/Types/CategorySelection.php
  src/Sulu/Bundle/CategoryBundle/Content/Types/SingleCategorySelection.php
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
  src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/CategoryBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Content/Types/SingleCategorySelectionTest.php
Labels: Feature

#5113 Replace deprecated TranslatorInterface with new one
  composer.json
  src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationRegistry.php
  src/Sulu/Bundle/AdminBundle/Metadata/ListMetadata/XmlListMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/DropdownToolbarActionSubscriber.php
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/TogglerToolbarActionSubscriber.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Navigation/NavigationRegistryTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/ListMetadata/XmlListMetadataLoaderTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/BrowserRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/DeviceTypeRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/LocaleRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/OperatingSystemRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/QueryStringRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/ReferrerRule.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/BrowserRuleTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/DeviceTypeRuleTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/LocaleRuleTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/OperatingSystemRuleTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/QueryStringRuleTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/ReferrerRuleTest.php
  src/Sulu/Bundle/PageBundle/Markup/Link/PageLinkProvider.php
  src/Sulu/Bundle/PageBundle/Rule/PageRule.php
  src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Markup/LinkTagTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Markup/Link/PageLinkProviderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Rule/PageRuleTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Teaser/PageTeaserProviderTest.php
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
  src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfigurationProvider.php
  src/Sulu/Bundle/SearchBundle/Tests/Unit/Search/Configuration/IndexConfigurationProviderTest.php
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/UserLocaleListenerTest.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
Labels: DX

#5111 Specifiy required symfony security packages
  composer.json
Labels: DX

#5115 Remove kernel.root_dir requirement from cache clearer
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
Labels: DX

#5116 Add missing exit code for all commands
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
  src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
  src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
  src/Sulu/Bundle/MediaBundle/Command/InitCommand.php
  src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
  src/Sulu/Bundle/PageBundle/Command/CleanupHistoryCommand.php
  src/Sulu/Bundle/PageBundle/Command/ContentLocaleCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/MaintainResourceLocatorCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidatePagesCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceExportCommand.php
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetExportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php
  src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
Labels: DX

#5122 Fix creating of media reference in categories
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
Labels: Bug

#5099 Fix switching of template with different block types
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
Labels: Bug

#5124 Resolve merge-conflict error
  src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/Resources/options.xml
Labels: Bug

#5114 Fixes JS error when translations are empty.
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Controller/AdminControllerTest.php
Labels: Bug

#5135 Add object-shorthand eslint rule
  .eslintrc.json
  .gitignore
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/SingleItemSection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/ColumnList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/tests/InfiniteScroller.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Matrix.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/Row.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/tests/Matrix.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/Pagination.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Body.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Header.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/Table.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Controls.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Items.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/metadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/Search.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/FolderAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceMultiSelect/tests/ResourceMultiSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/metadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/userStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/PreviewForm/tests/PreviewForm.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/Form/tests/fields/ContactDetails.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/MediaCardAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/MediaCardOverviewAdapter.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/MultiMediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/PageTreeRoute.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/Permissions/Permissions.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/RoleAssignments.js
  styleguide.config.js
Labels: DX

#5132 Fix error when using smart content media provider without includeSubFolders
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
  src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
Labels: Bug

#5123 Fix handling of content-type header in Website and SearchController
  src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/config_website.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/simple.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/templates/default.html.twig
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/WebsiteControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Controller/DefaultControllerTest.php
Labels: Bug

#5096 Fix FileValidator class not being configured
  .circleci/config.yml
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/FileValidator/FileValidator.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php
Labels: Bug

#5141 Avoid setting limit if the default limit has already been set
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/Router.test.js
Labels: Bug

#5148 Only set default template for pages when no template is currently selected
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TypedFormMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/metadataStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/__snapshots__/MetadataStore.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/__snapshots__/metadataStore.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/metadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/metadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/metadataStore/tests/metadataStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/snippets/default.xml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaVersionUpload.test.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/tests/toolbarActions/TemplateToolbarAction.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/Form/toolbarActions/TemplateToolbarAction.js
Labels: Bug

#5117 Add sulu admin http client service
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
Labels: DX

#5152 Fix SuluSecurityListener with InvokeableControllers
  src/Sulu/Bundle/SecurityBundle/EventListener/SuluSecurityListener.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
Labels: Bug
