Repository sulu/sulu, pull requests merged in 2020-09, with the labels that each got.

#5470 Fix function to get user from token-storage if no token is set
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/NavigationTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Navigation/NavigationTwigExtension.php
  src/Sulu/Component/Content/Query/ContentQueryExecutor.php
  src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
Labels: Bug

#5475 Fix user refresh on test user provider
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
Labels: Bug

#5479 Reuse Form component in GhostDialog to avoid creating own CSS
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/Dialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/dialog.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/Dialog.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/grid.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/GhostDialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/ghostDialog.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
Labels: DX

#5485 Fix template switching for pages preview
  src/Sulu/Bundle/PreviewBundle/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Controller/PreviewControllerTest.php
Labels: Bug

#5490 Avoid using IS_ANONYMOUS constant introduced in Symfony 5.1
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
Labels: Bug

#5392 Add link to selected default-snippet in SnippetAreas view
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/Button.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/button.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/tests/__snapshots__/ButtonGroup.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CardCollection/tests/__snapshots__/CardCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/tests/__snapshots__/Dialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DropdownButton/tests/__snapshots__/DropdownButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/tests/__snapshots__/FileUploadButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Actions.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/tests/__snapshots__/Overlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/__snapshots__/CardCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/AdapterSwitch.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/FieldFilterItem.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/ForgotPasswordForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/Login.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/LoginForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/ResetPasswordForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/__snapshots__/ResourceLocatorHistory.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/tests/__snapshots__/EditOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SmartContent/tests/__snapshots__/FilterOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/__snapshots__/FormOverlayList.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/containers/TargetGroupRules/tests/__snapshots__/ConditionList.test.js.snap
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/containers/TargetGroupRules/tests/__snapshots__/RuleOverlay.test.js.snap
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/tests/__snapshots__/ContactDetails.test.js.snap
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/__snapshots__/MediaVersionUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/__snapshots__/SingleMediaUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/tests/__snapshots__/Item.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/__snapshots__/PageList.test.js.snap
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/SnippetAreas.js
  src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/snippetAreas.scss
  src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/tests/SnippetAreas.test.js
  src/Sulu/Bundle/SnippetBundle/Resources/js/views/SnippetAreas/tests/__snapshots__/SnippetAreas.test.js.snap
Labels: UX

#5493 Adjust typehints in AccountManager and ContactManager to use interfaces
  src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
Labels: DX

#5494 Fix xliff export/import for documents with route content-types
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
Labels: Bug

#5425 Adjust segment feature to be compatible with the SuluArticleBundle
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/PageBundle/Content/Types/SegmentSelect.php
  src/Sulu/Bundle/PageBundle/Content/templates/excerpt.xml
  src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_block_settings.xml
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_excerpt.xml
  src/Sulu/Bundle/PageBundle/Resources/js/containers/Form/fields/SegmentSelect.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/Form/tests/fields/SegmentSelect.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/README.md
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/SegmentSelect.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/WebspaceSegmentSelect.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/tests/SegmentSelect.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/tests/__snapshots__/SegmentSelect.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/types.js
  src/Sulu/Bundle/PageBundle/Resources/js/containers/SegmentSelect/webspaceSegmentSelect.scss
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Export/WebspaceExportTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/QueryBuilderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/SegmentSelectTest.php
  src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationQueryBuilder.php
  src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Navigation/NavigationMapperTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/ContentRouteProviderTest.php
  src/Sulu/Component/Content/SmartContent/QueryBuilder.php
  src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  src/Sulu/Component/SmartContent/ContentType.php
  src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
Labels: DX, Feature

#5488 Fix media smart content for collections with multiple permissions
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
  src/Sulu/Bundle/SecurityBundle/AccessControl/AccessControlQueryEnhancer.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
Labels: Bug

#5472 Allow to copy page between webspaces
  config/webspaces/sulu-blog.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/MissingTypeDialog.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/SchemaFormStoreDecorator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/MissingTypeDialog.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/MissingTypeDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/CardCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/stores/ListStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/stores/ListStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/PermissionFormOverlay.test.js
  src/Sulu/Bundle/PageBundle/Resources/config/document.xml
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/PageList.test.js
  src/Sulu/Bundle/PageBundle/Serializer/Subscriber/StructureSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Component/Content/Compat/Structure/StructureBridge.php
  src/Sulu/Component/Content/Document/Subscriber/WebspaceSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WebspaceSubscriberTest.php
Labels: Feature

#5500 Move LocationBundle documentation from source code to docs
  src/Sulu/Bundle/LocationBundle/Resources/docs/index.md
Labels: DX

#5502 Remove outdated SearchBundle documentation from source code
  src/Sulu/Bundle/SearchBundle/Resources/docs/index.rst
Labels: DX

#5458 Introduce SaveWithFormDialogToolbarAction to show forms on save
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Admin/View/SaveWithFormDialogToolbarAction.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/FormInspector.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/FormInspector.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/CopyLocaleToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteDraftToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DropdownToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithFormDialogToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TogglerToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractFormToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DropdownToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithFormDialogToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/AbstractListToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/SaveWithFormDialogToolbarActionSubscriber.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Admin/View/SaveWithFormDialogToolbarActionTest.php
  src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/tests/toolbarActions/EnableUserToolbarAction.test.js
Labels: Feature

#5457 Inherit page and collection permissions to children
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/PermissionFormOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/PermissionFormOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/MediaSelectionOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/CollectionStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/CollectionStore/tests/CollectionStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/CollectionRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/ContentRepositoryTest.php
  src/Sulu/Bundle/SecurityBundle/Controller/PermissionController.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Exception/AccessControlDescendantProviderNotFoundException.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/permission_inheritance.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SecurityBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Controller/PermissionControllerTest.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManagerInterface.php
  src/Sulu/Component/Security/Authorization/AccessControl/DescendantProviderInterface.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
Labels: Feature

#5510 Fix cache:clear in admin context
  src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/EventSubscriber/CacheCommandSubscriberTest.php
Labels: Bug

#5513 Remove null-loader because it is not used anymore
  package.json
Labels: DX
