Repository sulu/sulu, pull requests merged in 2020-04, with the labels that each got.

#5137 Fixed correct locale for article route generation
  src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
Labels: Bug

#5163 Update react-styleguidist
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColorPicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Dialog/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Masonry/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiAutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiSelect/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Number/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Overlay/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Phone/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Popover/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Radio/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/RectangleSelection/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/README.md
  src/Sulu/Bundle/ContactBundle/Resources/js/components/Bic/README.md
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/README.md
  src/Sulu/Bundle/ContactBundle/Resources/js/components/Iban/README.md
  src/Sulu/Bundle/CustomUrlBundle/Resources/js/components/CustomUrl/README.md
  src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/README.md
  src/Sulu/Bundle/MediaBundle/Resources/js/components/MediaCard/README.md
  src/Sulu/Bundle/PageBundle/Resources/js/components/WebspaceSelect/README.md
Labels: DX

#5159 Update react-dropzone
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/FileUploadButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/tests/__snapshots__/FileUploadButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/__snapshots__/MediaVersionUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/__snapshots__/MultiMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/__snapshots__/SingleMediaUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: DX

#5160 Update ckeditor
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: DX

#5165 Update flow to 0.110.0
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Section.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Grid/Section.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/OptionList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Select.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/stores/ToolbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractFormToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/AbstractListToolbarAction.js
Labels: DX

#5168 Use array-move package directly instead of deprecated version from react-sortable-hoc
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
Labels: DX

#5171 Include security systems of configured webspaces in PageAdmin
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
Labels: DX

#5128 Fix problem with Contacts in Search Index
  src/Sulu/Bundle/ContentBundle/Search/EventListener/HitListener.php
  src/Sulu/Bundle/ContentBundle/Tests/Unit/Search/EventListener/HitListenerTest.php
Labels: Bug

#5166 Add key property to Role entity
  UPGRADE.md
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Bundle/SecurityBundle/Exception/RoleKeyAlreadyExistsException.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/forms/role_details.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/lists/roles.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
Labels: DX, Feature

#5178 Remove nodes cache config
  config/packages/prod/sulu_document_manager.yaml
Labels: Bug

#5187 Remove symfony/web-server-bundle
  UPGRADE.md
  composer.json
  config/bundles.php
Labels: DX

#5186 Make ControllerNameParser optional
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Resources/config/command.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ValidateWebspacesCommandTest.php
Labels: DX

#5180 Use central cache directory for symfony filesystem cache pool
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
Labels: Bug

#5190 Improve test performance by removing some routes that are not neccessary anymore
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
Labels: DX

#5126 [MediaBundle] Azure Blob Storage implementation
  composer.json
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/AzureBlobStorage.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_azure_blob.xml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/AzureBlobStorageTest.php
Labels: Feature

#5184 Normalize generated container class name
  phpstan.neon
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Bug

#5194 Fix lowest test for azure storage
  composer.json
Labels: Bug

#5195 Add missing service aliases
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
Labels: DX

#5188 Add support for Symfony RoutingConfigurator in Kernel
  UPGRADE.md
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: DX

#5191 Remove deprecated twig spaceless tag and fix sitemap index for multiple providers
  composer.json
  src/Sulu/Bundle/PageBundle/Resources/config/export.xml
  src/Sulu/Bundle/PageBundle/Resources/views/Export/Snippet/1.2.xliff.twig
  src/Sulu/Bundle/PageBundle/Resources/views/Export/Snippet/base.export.twig
  src/Sulu/Bundle/PageBundle/Resources/views/Export/Webspace/1.2.xliff.twig
  src/Sulu/Bundle/PageBundle/Resources/views/Export/Webspace/base.export.twig
  src/Sulu/Bundle/SnippetBundle/Resources/config/export.xml
  src/Sulu/Bundle/WebsiteBundle/Controller/SitemapController.php
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Sitemap/sitemap-index.xml.twig
  src/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRenderer.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/TestSitemapProvider.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/services.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/webspaces/test_with_index.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Sitemap/XmlSitemapRendererTest.php
  src/Sulu/Component/Export/Export.php
Labels: DX

#5197 Fix minimum size calculation for crops
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/ImageRectangleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ImageRectangleSelection/tests/ImageRectangleSelection.test.js
Labels: Bug

#5175 Add swiftmailer listener plugin
  composer.json
  src/Sulu/Bundle/MarkupBundle/Listener/SwiftMailerListener.php
  src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/SwiftMailerListenerTest.php
Labels: DX

#5204 Fix clearing of preview cache
  src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/EventSubscriber/CacheCommandSubscriberTest.php
Labels: Bug

#5213 Run preview cache clear command only when App\Kernel exists
  src/Sulu/Bundle/PreviewBundle/EventSubscriber/CacheCommandSubscriber.php
Labels: Bug

#5215 Remove requirement for doctrine cache bundle
  UPGRADE.md
  composer.json
  config/bundles.php
  phpstan.neon
  src/Sulu/Bundle/PreviewBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PreviewBundle/DependencyInjection/SuluPreviewExtension.php
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewCache.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewCacheTest.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
Labels: DX, Feature

#5201 Avoid setting id properties on block values
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
Labels: Bug

#5226 Get ride of usage of kernel.root_dir
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php
  src/Sulu/Bundle/PageBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
Labels: DX

#5238 Drop symfony 4.3 support
  composer.json
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
  src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: DX

#5230 Update usage of new kernel event classes
  src/Sulu/Bundle/AudienceTargetingBundle/EventListener/DeviceDetectorSubscriber.php
  src/Sulu/Bundle/AudienceTargetingBundle/EventListener/TargetGroupSubscriber.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
  src/Sulu/Bundle/MarkupBundle/Listener/MarkupListener.php
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/MarkupListenerTest.php
  src/Sulu/Bundle/SecurityBundle/EventListener/SuluSecurityListener.php
  src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/UserLocaleListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/RedirectExceptionSubscriber.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/RouterListener.php
  src/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListener.php
  src/Sulu/Bundle/WebsiteBundle/EventSubscriber/GeneratorEventSubscriber.php
  src/Sulu/Bundle/WebsiteBundle/Routing/RequestListener.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/RouterListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/EventListener/TranslatorListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RedirectExceptionSubscriberTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/RequestListenerTest.php
Labels: DX

#5231 Fix SuluCollector compatibility
  src/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollector.php
Labels: DX

#5235 Remove old controller reference syntax
  config/templates/pages/example.xml
  config/templates/pages/homepage.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/CategoryBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/CoreBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/CustomUrlBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/CustomUrlBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/templates/pages/images.xml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/DefaultStructureCache.php
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/article.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/block.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/blocks.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/complex.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/html5.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/internal_link.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/internal_link_page.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/internallinks.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/invalidhtml.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/mandatory.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/section.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/simple.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/singleinternallink.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/smartcontent.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/teasers.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/test_page.xml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/templates/pages/with_snippet.xml
  src/Sulu/Bundle/PersistenceBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SearchBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/hotel_page.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/TagBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/TestBundle/Resources/structures/pages/default.xml
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/data/apostrophe/apostrophe.xml
  tests/Resources/DataFixtures/Page/template_block.xml
  tests/Resources/DataFixtures/Page/template_block_type_without_meta.xml
  tests/Resources/DataFixtures/Page/template_block_types.xml
  tests/Resources/DataFixtures/Page/template_with_nested_blocks.xml
  tests/Resources/DataFixtures/Page/template_with_nested_sections.xml
  tests/Resources/DataFixtures/Page/template_with_schema.xml
Labels: DX

#5228 Extend sulu event from new event class
  UPGRADE.md
  composer.json
  src/Sulu/Bundle/CategoryBundle/Event/CategoryDeleteEvent.php
  src/Sulu/Bundle/PreviewBundle/Preview/Events/PreRenderEvent.php
  src/Sulu/Bundle/SearchBundle/Search/Event/StructureMetadataLoadEvent.php
  src/Sulu/Bundle/TagBundle/Event/TagDeleteEvent.php
  src/Sulu/Bundle/TagBundle/Event/TagMergeEvent.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeDeleteEvent.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeEvent.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeOrderEvent.php
  src/Sulu/Component/DocumentManager/Event/AbstractEvent.php
  src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
  src/Sulu/Component/Rest/ListBuilder/Event/ListBuilderCreateEvent.php
  src/Sulu/Component/Security/Event/PermissionUpdateEvent.php
Labels: DX

#5232 Remove navigation context from homepage
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
Labels: UX

#5236 Change service definition for DefaultController
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
Labels: DX

#5240 Fix copy language with different template
  CHANGELOG.md
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Tests/Functional/Mapper/ContentMapperTest.php
Labels: Bug

#5242 Fix custom url serialization without creator or changer
  src/Sulu/Bundle/CustomUrlBundle/EventListener/CustomUrlSerializeEventSubscriber.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/CustomUrlSerializeEventSubscriberTest.php
Labels: Bug, Performance

#5247 Fix deprecated cache clear event
  src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php
  src/Sulu/Bundle/WebsiteBundle/Event/CacheClearEvent.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Cache/CacheClearerTest.php
Labels: DX

#5219 Add deep links in referencing field types
  config/webspaces/sulu-test.xml
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/MultiItemSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/MultiItemSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/MultiItemSelection/tests/__snapshots__/MultiItemSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Selection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Selection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/MultiSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/MultiSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/MultiSelection/tests/__snapshots__/MultiSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/ResourceTabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/ContactAccountSelection.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/tests/ContactAccountSelection.test.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/tests/__snapshots__/ContactAccountSelection.test.js.snap
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/Form/fields/ContactAccountSelection.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/Form/tests/fields/ContactAccountSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/MultiMediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/MultiMediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaSelection/tests/__snapshots__/MultiMediaSelection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/types.js
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/PageBundle/Resources/js/containers/TeaserSelection/tests/__snapshots__/TeaserSelection.test.js.snap
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/snippets/hotel.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Component/Content/Repository/Content.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
Labels: Feature

#5244 Avoid duplicated boot of test kernel
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/CollaborationControllerTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/TargetGroupControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/KeywordControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Category/CategoryManagerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactMediaControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactTitleControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/PositionControllerTest.php
  src/Sulu/Bundle/CoreBundle/Tests/Functional/Controller/LocalizationControllerTest.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlRouteControllerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/config_website.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_website.yml
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaFormatControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaPreviewControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaRedirectControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaWebsiteControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/test.txt
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerFieldsTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/VersionControllerTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
  src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/GroupControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ProfileControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleSettingControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Entity/UserRepositoryTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetAreaControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/templates/default.html.twig
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/AnalyticsControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/WebsiteControllerTest.php
Labels: DX

#5248 Invalidate System collections cache in warmUp
  src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
  src/Sulu/Component/Media/Tests/Unit/SystemCollections/SystemCollectionManagerTest.php
Labels: DX

#5255 Add deep links to single selections
  UPGRADE.md
  config/webspaces/sulu-blog.xml
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/SingleItemSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/singleItemSelection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/SingleItemSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleItemSelection/tests/__snapshots__/SingleItemSelection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleSelection/tests/__snapshots__/SingleSelection.test.js.snap
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/SingleMediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/SingleMediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaSelection/tests/__snapshots__/SingleMediaSelection.test.js.snap
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Resources/config/serializer/Document.BasePageDocument.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/RouteBundle/Resources/js/containers/Form/tests/fields/__snapshots__/PageTreeRoute.test.js.snap
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
Labels: UX

#5257 Use interface of CategoryTranslation for CategoryTranslationMedia
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslationMedia.orm.xml
Labels: Bug

#5258 Fix deprecation in authorizationChecker isGranted
  src/Sulu/Component/Security/Authorization/SecurityChecker.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityCheckerTest.php
Labels: DX

#5259 Fix EventDispatcher Test compatibility
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ChildrenCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/QueryResultCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ReferrerCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Metadata/BaseMetadataFactoryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/ProxyFactoryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Query/QueryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/FindSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/RefreshSubscriberTest.php
Labels: DX

#5261 Use maintained fork of cron expression library
  composer.json
Labels: DX

#5243 Change Document Fixtures to dependency injection
  UPGRADE.md
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentExecutor.php
  src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentFixtureGroupInterface.php
  src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentFixtureLoader.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Compiler/DocumentFixturePass.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/command.xml
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/data_fixtures.xml
  src/Sulu/Bundle/DocumentManagerBundle/SuluDocumentManagerBundle.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/DataFixtures/FooFixture.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/DataFixtures/GroupBarFixture.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/DataFixtures/GroupFooFixture.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/DataFixtures/DocumentFixtureLoaderTest.php
Labels: DX
