Repository sulu/sulu, pull requests merged in 2020-02, with the labels that each got.

#4878 Show better preview content block exception
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
Labels: DX

#5033 Fix build download for other platforms
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
Labels: Bug, DX

#5032 Fixing TwigException parameter types
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/PreviewRendererException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/RouteDefaultsProviderNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/TemplateNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/TwigException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/UnexpectedException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceLocalizationNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/WebspaceNotFoundException.php
Labels: DX

#5024 Replace host right after loading webspaces to avoid repeating this logic
  UPGRADE.md
  src/Sulu/Bundle/CoreBundle/Resources/config/request_analyzer.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
  src/Sulu/Bundle/HttpCacheBundle/Cache/CacheManager.php
  src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php
  src/Sulu/Bundle/HttpCacheBundle/Resources/config/cache-manager.xml
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/Cache/CacheManagerTest.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/webspaces/sulu.io.xml
  src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/command.xml
  src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/PortalLoaderTest.php
  src/Sulu/Component/Webspace/Analyzer/Attributes/WebsiteRequestProcessor.php
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
  tests/Resources/DataFixtures/Webspace/multiple/massiveart.xml
  tests/Resources/DataFixtures/Webspace/valid/sulu.io.xml
  tests/Resources/DataFixtures/Webspace/valid/sulu.io_hostReplacer.xml
Labels: Bug

#5037 Use correct default scheme for sulu_content_path
  src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
Labels: DX

#5040 Improve download language command
  composer.json
  phpstan.neon
  src/Sulu/Bundle/AdminBundle/Command/DownloadLanguageCommand.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
Labels: DX

#5049 Fix media copyright and description to be deletable
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Resources/config/forms/media_details.xml
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
Labels: Bug

#5059 Register RouteManagerInterface::class as alias for sulu_route.manager.route_manager service
  src/Sulu/Bundle/RouteBundle/Resources/config/manager.xml
Labels: DX

#5057 Fix url and path generation for text with non-latin symbols
  appveyor.yml
  composer.json
  src/Sulu/Bundle/CoreBundle/DataFixtures/replacers.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/core.xml
  src/Sulu/Bundle/DocumentManagerBundle/Slugifier/Urlizer.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Import/WebspaceImportTest.php
  src/Sulu/Component/DocumentManager/Slugifier/PathCleanupSlugifier.php
  src/Sulu/Component/PHPCR/PathCleanup.php
  src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
Labels: Bug

#5075 Redesign list to make space for filter feature
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Breadcrumb/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/cardCollection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/columnOptions.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ProfileFormOverlay/profileFormOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/resourceLocatorHistory.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceSingleSelect/editOverlay.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/formOverlayList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/List.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/list.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/exportToolbarAction.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tabs.scss
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/containers/TargetGroupRules/ruleOverlay.scss
  src/Sulu/Bundle/ContactBundle/Resources/js/views/List/toolbarActions/addContactToolbarAction.scss
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/locationOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/singleMediaDropzone.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/collectionFormOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/permissionFormOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/mediaSelectionOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/cropOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/focusPointOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/pageList.scss
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/tests/__snapshots__/PageList.test.js.snap
Labels: UX

#5076 Add cache providers for phpcr metadata and nodes
  config/packages/prod/sulu_document_manager.yaml
  config/packages/stage/sulu_document_manager.yaml
Labels: Performance

#5066 Add tags to metadata and add filter for metadata provider
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TagMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TypedFormMetadata.php
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/FormMetadataProviderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Component/Content/Metadata/Loader/schema/form-1.0.xsd
Labels: Feature
