Repository sulu/sulu, pull requests merged in 2020-11, with the labels that each got.

#5580 Fix MediaDataProvider if no security is configured
  src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
Labels: Bug

#5576 Fix default-values for multiple-select in blocks
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
Labels: Bug

#5581 Implement single_snippet_selection content-type
  config/templates/pages/example.xml
  src/Sulu/Bundle/SnippetBundle/Content/SingleSnippetSelection.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/SnippetBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SingleSnippetSelectionTest.php
  templates/pages/example.html.twig
Labels: Feature

#5589 Collect tags from types only if data is an array
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
Labels: Bug

#5595 Fix segment request processor without webspace
  src/Sulu/Component/Webspace/Analyzer/Attributes/SegmentRequestProcessor.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/SegmentRequestProcessorTest.php
Labels: Bug

#5584 Initialize ListStore with page 1 in MediaSelectionOverlay
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/MediaSelectionOverlay.js
Labels: Bug

#5588 Fix ImageMap default values
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/ImageMap/ImageMap.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/ImageMap.test.js
Labels: Bug

#5583 Improve phpdoc in AdminBundle
  src/Sulu/Bundle/AdminBundle/Admin/AdminPool.php
  src/Sulu/Bundle/AdminBundle/Admin/View/ViewRegistry.php
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
Labels: hacktoberfest-accepted

#5609 Add subscript, superscript and code plugins to ckeditor
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkPlugin.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/InternalLinkPlugin.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: UX

#5591 Replace invalid characters in resource locator
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ResourceLocator/tests/ResourceLocator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/ResourceLocator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/ResourceLocator.test.js
Labels: Bug

#5614 Some fixes for PHPStan level 2 on AudienceTargetingBundle
  src/Sulu/Bundle/CategoryBundle/Api/Category.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManagerInterface.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepositoryInterface.php
Labels: DX

#5620 Include postcss.config.js in UpdateBuildCommand
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
Labels: DX

#5637 Add autowire for media TypeManagerInterface
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
Labels: DX

#5600 Fix add request format to redirect url
  src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProviderTest.php
Labels: Bug

#5605 Adding default to anonymous column
  UPGRADE.md
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
Labels: Bug

#5654 Allow components as children of Select Option
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/DisplayValue.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/__snapshots__/DisplayValue.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleSelect/README.md
Labels: DX
