Repository sulu/sulu, pull requests merged in 2020-06, with the labels that each got.

#5315 Fix errors happening on error template rendering
  src/Sulu/Bundle/WebsiteBundle/Controller/ErrorController.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Controller/ErrorControllerTest.php
Labels: Bug

#5304 Add possibility to include search fields as indexed
  src/Sulu/Bundle/ContentBundle/Search/Metadata/StructureProvider.php
Labels: Feature

#5323 Fix /cmf/snippets node not exist in live workspace
  CHANGELOG.md
  src/Sulu/Bundle/SnippetBundle/Document/SnippetInitializer.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
  src/Sulu/Component/Util/SuluNodeHelper.php
Labels: Bug

#5325 Update branch aliases
  composer.json
Labels: DX

#5331 Use in appveyor stable version of composer
  appveyor.yml
Labels: Bug

#4798 Add compatibility to symfony 5
  UPGRADE.md
  appveyor.yml
  bin/console.php
  composer.json
  config/bundles.php
  phpstan.neon
  public/index.php
  src/Sulu/Bundle/AdminBundle/Controller/CollaborationController.php
  src/Sulu/Bundle/AudienceTargetingBundle/Controller/TargetGroupController.php
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/CategoryBundle/Controller/KeywordController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactTitleController.php
  src/Sulu/Bundle/ContactBundle/Controller/PositionController.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
  src/Sulu/Bundle/CoreBundle/Controller/LocalizationController.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/CoreBundle/Resources/config/rest.xml
  src/Sulu/Bundle/CustomUrlBundle/Controller/CustomUrlController.php
  src/Sulu/Bundle/CustomUrlBundle/Controller/CustomUrlRouteController.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/FormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PageBundle/Controller/PageResourcelocatorController.php
  src/Sulu/Bundle/PageBundle/Controller/ResourcelocatorController.php
  src/Sulu/Bundle/PageBundle/Controller/TeaserController.php
  src/Sulu/Bundle/PageBundle/Controller/VersionController.php
  src/Sulu/Bundle/PageBundle/Controller/WebspaceController.php
  src/Sulu/Bundle/PageBundle/Controller/WebspaceLocalizationController.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
  src/Sulu/Bundle/SecurityBundle/Controller/ContextsController.php
  src/Sulu/Bundle/SecurityBundle/Controller/GroupController.php
  src/Sulu/Bundle/SecurityBundle/Controller/PermissionController.php
  src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleSettingController.php
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SnippetBundle/Controller/LanguageController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/TagBundle/Controller/TagController.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/context_admin.yml
  src/Sulu/Bundle/WebsiteBundle/Controller/AnalyticsController.php
  src/Sulu/Component/HttpKernel/SuluKernel.php
  src/Sulu/Component/Rest/Csv/CsvHandler.php
  src/Sulu/Component/Rest/ExceptionSerializerHandler.php
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
  src/Sulu/Component/Rest/Tests/Unit/Csv/CsvHandlerTest.php
Labels: DX, Feature

#5306 Add settings to hide blocks
  .flowconfig
  config/templates/pages/example.xml
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/fieldBlocks.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Heading.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/heading.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/SchemaFormStoreDecorator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Heading.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/__snapshots__/Checkbox.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/__snapshots__/Heading.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_blocks.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_block_settings.xml
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Mapper/ContentMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/QueryBuilderTest.php
  src/Sulu/Component/Content/Compat/Block/BlockProperty.php
  src/Sulu/Component/Content/Compat/Block/BlockPropertyType.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
  src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  templates/pages/example.html.twig
Labels: UX

#5338 Update recipe config files
  config/packages/cache.yaml
  config/packages/dev/debug.yaml
  config/packages/dev/monolog.yaml
  config/packages/dev/routing.yaml
  config/packages/framework.yaml
  config/packages/prod/monolog.yaml
  config/packages/routing.yaml
  config/packages/stage/routing.yaml
  config/packages/test/routing.yaml
Labels: DX

#5327 Add svg support by default
  composer.json
Labels: DX, To Discuss, UX

#5360 Fix category medias typehint
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslationInterface.php
Labels: DX

#5369 Add icons to list for MediaType
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/MediaBundle/Resources/config/lists/media.xml
Labels: Feature
