Repository sulu/sulu, pull requests merged in 2020-08, with the labels that each got.

#5418 Store values from image crop as integers
  CHANGELOG.md
  src/Sulu/Bundle/MediaBundle/Entity/FormatOptions.php
  src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
Labels: Bug

#5442 Fix export data function of audience-target selection
  src/Sulu/Bundle/AudienceTargetingBundle/Content/Types/AudienceTargetingGroups.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Content/Types/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Content/Types/AudienceTargetingGroupsTest.php
  src/Sulu/Bundle/ContentBundle/Tests/Functional/Export/WebspaceExportTest.php
Labels: Bug

#5393 Add command for regeneration formats
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/regenerate-formats/200x/2-test.svg
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/regenerate-formats/400x400-inset/10/3-2020-test-test.svg
  src/Sulu/Bundle/MediaBundle/Tests/Fixtures/regenerate-formats/50x50/01/1-test.svg
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Command/FormatCacheRegenerateCommandTest.php
Labels: Feature

#5448 Write permissions of pages also to live workspace
  src/Sulu/Bundle/PageBundle/Resources/config/document.xml
  src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/SecuritySubscriberTest.php
Labels: Feature

#5450 Add website security to properly test security related features
  config/bundles.php
  config/packages/security_website.yaml
  config/routes/sulu_website.yml
  templates/static/login.html.twig
Labels: DX

#5437 Allow to secure media download on website
  src/Sulu/Bundle/MediaBundle/Api/Media.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManagerInterface.php
  src/Sulu/Bundle/MediaBundle/Resources/config/lists/media.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yml
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/adapters/MediaCardAdapter.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/FocusPointOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/MediaVersionUpload.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/MediaVersionUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/SingleMediaUpload.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaHistory/MediaHistory.js
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerAdminTest.php
Labels: Feature

#5452 Allow newer version of ramsey/uuid, league/flysystem-azure-blob-storage and php-ffmpeg/php-ffmpeg
  composer.json
Labels: DX

#5432 Add possibility for distinct to count field descriptor
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCountFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/CountPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ListXmlLoader.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/Resources/schema/list-2.0.xsd
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/FieldDescriptor/DoctrineCountFieldDescriptorTest.php
Labels: Feature

#5443 Add user context based cache configuration
  config/packages/fos_http_cache.yaml
  config/routes/fos_http_cache.yaml
  tests/Kernel.php
Labels: Feature

#5397 Filter out obsolete entries when changing value of Select field
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Select.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Select.test.js
Labels: Bug

#5453 Added column "User locked" to contacts list to display locked state o…
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/contacts.xml
Labels: Feature

#5455 Fix mobx regression causing error in development build
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/Toolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/types.js
Labels: Bug

#5414 Fix serialization regression for TargetGroups
  composer.json
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/doctrine/TargetGroup.orm.xml
  src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/JmsObjectConstructorCompilerPass.php
  src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php
Labels: Bug

#5436 Throw proper error message when invalid form XML is loaded
  src/Sulu/Bundle/AdminBundle/Exception/InvalidRootTagException.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/data/form_invalid_root_tag.xml
Labels: Bug

#5357 Fix composer 2 compatibility for php 7.3 and lower
  composer.json
Labels: DX

#5427 Add dropdown for overflowing tabs
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/CollapsedTab.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/CollapsedTabList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tab.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/collapsedTab.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/collapsedTabList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tab.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tabs.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/Tabs.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/__snapshots__/Tabs.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/Items.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Items.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Toolbar/tests/Toolbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/ResourceTabs.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/ResourceTabs/tests/__snapshots__/ResourceTabs.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/Tabs.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/__snapshots__/Tabs.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/tests/WebspaceTabs.test.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/tests/__snapshots__/WebspaceTabs.test.js.snap
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
Labels: Feature

#5420 Implement handling of resource_store_properties_to_request param in SingleSelection field
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/SingleListOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/SingleListOverlay/tests/SingleListOverlay.test.js
Labels: Feature
