Repository sulu/sulu, pull requests merged in 2020-07, with the labels that each got.

#5378 Make sure ContentMapperSubscriber runs before the RemoveSubscriber
  src/Sulu/Component/Content/Document/Subscriber/Compat/ContentMapperSubscriber.php
Labels: Bug

#5398 Activate babel cacheDirectory
  webpack.config.js
Labels: DX, Performance

#5405 Fix documented return types in DefaultSnippetManagerInterface
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManagerInterface.php
Labels: DX

#5400 Update size of focus point selection when window is resized
  src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/ImageFocusPoint.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/tests/ImageFocusPoint.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/tests/__snapshots__/ImageFocusPoint.test.js.snap
Labels: Bug

#5429 Remove urlizer requirement
  composer.json
Labels: DX

#5383 Add contact_selection and account_selection content-type
  config/templates/pages/example.xml
  src/Sulu/Bundle/ContactBundle/Content/Types/AccountSelection.php
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelection.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/ContactBundle/Resources/config/content.xml
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/ContactBundle/Tests/Unit/AccountSelectionTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactSelectionTest.php
Labels: Feature

#5380 Add position name to serialized contact
  src/Sulu/Bundle/ContactBundle/Api/Contact.php
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#5435 Correct serialization type of tags for Accounts and Contacts
  CHANGELOG.md
  src/Sulu/Bundle/ContactBundle/Entity/AbstractAccount.php
  src/Sulu/Bundle/ContactBundle/Entity/Contact.php
Labels: Bug

#5433 Add anonymous roles for each system
  UPGRADE.md
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/Initializer.php
  src/Sulu/Bundle/SecurityBundle/Build/SecurityBuilder.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/UserRole.php
  src/Sulu/Bundle/SecurityBundle/Exception/AssignAnonymousRoleException.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/command.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/lists/roles.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RolePermissions/RolePermissions.js
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Entity/UserRoleTest.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
  src/Sulu/Component/Security/Authentication/RoleRepositoryInterface.php
Labels: Feature
