Repository sulu/sulu, pull requests merged in 2021-06, with the labels that each got.

#6093 Use lts version of proxy manager
  composer.json
Labels: Bug

#6102 Add postinstall info command
  src/Sulu/Bundle/AdminBundle/Command/InfoCommand.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
Labels: DX

#6056 Add @babel/plugin-proposal-nullish-coalescing-operator to transpile code of react-leaflet package
  babel.config.json
  package.json
  src/Sulu/Bundle/LocationBundle/Resources/js/package.json
  styleguide.config.js
  webpack.config.js
Labels: Bug

#6107 Fix writing 0 as numeric value
  src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
  src/Sulu/Component/Content/Types/Number.php
Labels: Bug

#6116 Add Symfony ResetInterface for ReferenceStore
  src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
  src/Sulu/Bundle/TagBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/ReferenceStore/ReferenceStore.php
Labels: Feature

#6115 Introduce ChangeContext to prevent marking form as dirty when setting default value
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Form.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Checkbox.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Select.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SingleSelect.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/SmartContent.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/AbstractFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/SchemaFormStoreDecorator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Form.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Select.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/SingleSelect.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Url.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/MemoryFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/ResourceFormStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/ResourceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/ResourceStore/tests/ResourceStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteDraftToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SetUnpublishedToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TogglerToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TogglerToolbarAction.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/MediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/fields/SingleMediaSelection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/MediaSelection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Form/tests/fields/SingleMediaSelection.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/tests/toolbarActions/EnableUserToolbarAction.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/toolbarActions/EnableUserToolbarAction.js
Labels: UX

#6130 Use maintained tag of jackrabbit image in test workflow
  .github/workflows/test-application.yaml
Labels: DX
