Repository sulu/sulu, pull requests merged in 2021-09, with the labels that each got.

#6223 Fix startup performance and ckeditor styling of react-styleguidist integration
  styleguide.config.js
Labels: DX

#6221 Check webspace permissions for hiding toolbar actions when creating new page
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DeleteToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/PublishToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TogglerToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/TypeToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/AbstractFormToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteDraftToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DeleteToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/PublishToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithFormDialogToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SetUnpublishedToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/TypeToolbarAction.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/SecurityBundle/Resources/js/views/Form/tests/toolbarActions/EnableUserToolbarAction.test.js
Labels: UX

#6228 Use webspace permissions for hiding toolbar actions only when creating new page
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
Labels: Bug

#6230 Add routerAttributesToFormMetadata option to FormOverlayList view
  src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/FormOverlayList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/FormOverlayList/tests/FormOverlayList.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormOverlayListViewBuilderTest.php
Labels: DX

#6222 Add userConditionDataProvider to allow for checking user roles in conditions
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/conditionDataProviders/userConditionDataProvider.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/conditionDataProviders/userConditionDataProvider.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/tests/userStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/types.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/formatStore/tests/FormatStore.test.js
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
Labels: DX

#6231 Fix application crash if autocomplete query is not a valid regular expression
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/Suggestion.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/__snapshots__/Suggestion.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SingleAutoComplete/tests/__snapshots__/SingleAutoComplete.test.js.snap
Labels: Bug

#6234 Fix InfiniteLoadingStrategy to prevent missing and duplicated list items
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/loadingStrategies/InfiniteLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/loadingStrategies/InfiniteLoadingStrategy.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/CollectionSection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
Labels: Bug

#6253 Fix FixturesBuilder purging all documents
  src/Sulu/Bundle/CoreBundle/Build/FixturesBuilder.php
Labels: Bug

#6255 Fix update build command for forks
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
Labels: Bug

#6252 Fix import of empty value in Checkbox content type
  src/Sulu/Bundle/PageBundle/Content/Types/Checkbox.php
Labels: Bug

#6258 Fix section in block as first element overlap buttons
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/grid.scss
Labels: Bug
