Repository sulu/sulu, pull requests merged in 2021-05, with the labels that each got.

#5981 Remove abstract from SuluTestCase
  src/Sulu/Bundle/TestBundle/Testing/SuluTestCase.php
Labels: DX

#5978 Single file for our dev security config
  config/packages/security.yaml
  config/packages/security_website.yaml
  config/packages/test/security.yaml
Labels: DX

#5980 Run php lint task in own step
  .github/workflows/test-application.yaml
  composer.json
Labels: DX

#5993 Update babel.config.json to resolve warning
  babel.config.json
  package.json
Labels: DX

#5990 Remove flush from EventRecordRepository
  UPGRADE.md
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
  src/Sulu/Bundle/EventLogBundle/Application/Subscriber/StoreEventRecordSubscriber.php
  src/Sulu/Bundle/EventLogBundle/Domain/Repository/EventRecordRepositoryInterface.php
  src/Sulu/Bundle/EventLogBundle/Domain/Repository/NullEventRecordRepository.php
  src/Sulu/Bundle/EventLogBundle/Infrastructure/Doctrine/Repository/EventRecordRepository.php
  src/Sulu/Bundle/EventLogBundle/Infrastructure/Doctrine/Subscriber/EventRecordMetadataSubscriber.php
  src/Sulu/Bundle/EventLogBundle/Resources/config/doctrine/EventRecord.orm.xml
  src/Sulu/Bundle/EventLogBundle/Resources/config/services.xml
  src/Sulu/Bundle/EventLogBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/EventLogBundle/Tests/Application/config/with_payload/config.yaml
  src/Sulu/Bundle/EventLogBundle/Tests/Functional/Infrastructure/Doctrine/Repository/EventRecordRepositoryTest.php
  src/Sulu/Bundle/EventLogBundle/Tests/Unit/Application/Subscriber/StoreEventRecordSubscriberTest.php
  src/Sulu/Bundle/EventLogBundle/Tests/Unit/Infrastructure/Doctrine/Subscriber/EventRecordMetadataSubscriberTest.php
Labels: Bug

#5956 Upgrade react-datetime to 3.0.0
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/DatePicker.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/DatePicker.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/DatePicker/tests/__snapshots__/DatePicker.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: DX

#5979 Fix route collection builder is deprecation message
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: DX

#5995 Enhance domain events for analytics
  src/Sulu/Bundle/WebsiteBundle/Analytics/AnalyticsManager.php
  src/Sulu/Bundle/WebsiteBundle/Domain/Event/AnalyticsCreatedEvent.php
  src/Sulu/Bundle/WebsiteBundle/Domain/Event/AnalyticsModifiedEvent.php
  src/Sulu/Bundle/WebsiteBundle/Domain/Event/AnalyticsRemovedEvent.php
Labels: DX

#5999 Activate PreviewBundle also for website context
  config/bundles.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
Labels: DX

#5996 Add domain events for default snippets
  UPGRADE.md
  src/Sulu/Bundle/SnippetBundle/Domain/Event/WebspaceDefaultSnippetModifiedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/WebspaceDefaultSnippetRemovedEvent.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
Labels: DX

#5977 Remove pagerfanta dependency
  composer.json
  src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
  src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
Labels: DX

#6002 Fix user auditable fields migration
  UPGRADE.md
Labels: Bug

#5953 Upgrade react-leaflet to 3.0.0 version
  package.json
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/Location.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/Location.test.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/LocationOverlay.test.js
  src/Sulu/Bundle/LocationBundle/Resources/js/package.json
Labels: DX

#6049 Make behaviour of media dropzone more predictable
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/DropzoneOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/dropzoneOverlay.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: UX

#6067 Prevent badge request when navigating away from tab view
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/Badge.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/stores/BadgeStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/tests/Badge.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/tests/stores/BadgeStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
Labels: Bug

#6068 Fix spacing at bottom of media overview when using table adapter
  src/Sulu/Bundle/AdminBundle/Resources/js/components/InfiniteScroller/infiniteScroller.scss
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/mediaOverview.scss
Labels: Bug

#6085 Prevent loading config files multiple times
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Bug
