Repository sulu/sulu, pull requests merged in 2021-08, with the labels that each got.

#6174 Create missing node when editing page without node in live workspace
  src/Sulu/Bundle/PageBundle/Document/Subscriber/PublishSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Component/Content/Document/Subscriber/SecuritySubscriber.php
Labels: Bug

#6161 Add autocomplete attributes to LoginForm, ResetPasswordForm, ForgotPasswordForm
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/PasswordConfirmation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/PasswordConfirmation/tests/__snapshots__/PasswordConfirmation.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/tests/__snapshots__/Application.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ForgotPasswordForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/LoginForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/ForgotPasswordForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/Login.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/LoginForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/ResetPasswordForm.test.js.snap
Labels: Feature

#6147 Reduce seo meta description length from 320 to 160 characters
  src/Sulu/Bundle/PageBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_seo.xml
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
Labels: UX

#6183 Move project specific javascript code into separate app.js file
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
Labels: DX

#6187 Fix windows video thumbnail generation
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/MediaImageExtractor.php
  src/Sulu/Bundle/MediaBundle/Media/Video/VideoThumbnailService.php
Labels: Bug

#6186 Use generic DropdownToolbarAction instead of SaveWithPublishingToolbarAction in PageAdmin
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/DropdownToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/PublishToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/tests/toolbarActions/SaveWithPublishingToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DropdownToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/PublishToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/SaveWithPublishingToolbarAction.js
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
Labels: DX

#6184 Fixed default meta for Media
  src/Sulu/Bundle/MediaBundle/Api/Media.php
Labels: Bug

#6190 Define react version and flow version in eslint config
  .eslintrc.json
Labels: DX

#6194 Improve consistency of colors used in admin UI
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ArrowMenu/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/suggestion.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/checkbox.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/action.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/option.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/global.scss
Labels: UX

#6188 Add possibility to add additional data to login request
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ForgotPasswordForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/Login.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/LoginForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/ResetPasswordForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/ForgotPasswordForm.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/Login.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/LoginForm.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/ResetPasswordForm.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/tests/userStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/userStore.js
Labels: DX
