Repository sulu/sulu, pull requests merged in 2021-04, with the labels that each got.

#5917 Run windows test cases with doctrinedbal instead of jackrabbit to improve performance
  .github/workflows/test-application.yaml
Labels: DX

#5888 Set aliases for PersistenceBundle repositories in PHP instead of XML
  src/Sulu/Bundle/AudienceTargetingBundle/DependencyInjection/SuluAudienceTargetingExtension.php
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
  src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
  src/Sulu/Bundle/CategoryBundle/SuluCategoryBundle.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/DependencyInjection/SuluRouteExtension.php
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/SuluRouteBundle.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/SuluSecurityBundle.php
  src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
  src/Sulu/Bundle/TagBundle/Resources/config/services.xml
Labels: DX

#5921 Add phpstan, php-cs files to export-ignore in .gitattributes file
  .gitattributes
Labels: DX

#5919 Referencing controllers with a single colon is deprecated
  src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/routing_website.yml
  src/Sulu/Bundle/LocationBundle/Resources/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yml
  src/Sulu/Bundle/PreviewBundle/Resources/config/routing.yml
  src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Routing/RouteProviderTest.php
  src/Sulu/Bundle/SearchBundle/Resources/config/routing.yml
  src/Sulu/Bundle/SearchBundle/Resources/config/routing_website.yml
  src/Sulu/Bundle/SearchBundle/Tests/Resources/TestBundle/Resources/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Resources/config/routing.yml
  src/Sulu/Bundle/SnippetBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/WebsiteBundle/Resources/config/routing.yml
  src/Sulu/Bundle/WebsiteBundle/Routing/ContentRouteProvider.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/ContentRouteProviderTest.php
  src/Sulu/Component/CustomUrl/Routing/CustomUrlRouteProvider.php
  src/Sulu/Component/CustomUrl/Routing/Enhancers/ExternalLinkEnhancer.php
  src/Sulu/Component/CustomUrl/Routing/Enhancers/RedirectEnhancer.php
  src/Sulu/Component/CustomUrl/Routing/Enhancers/TrailingHTMLEnhancer.php
  src/Sulu/Component/CustomUrl/Routing/Enhancers/TrailingSlashEnhancer.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/CustomUrlRouteProviderTest.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/ExternalLinkEnhancerTest.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/RedirectEnhancerTest.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/TrailingHTMLEnhancerTest.php
  src/Sulu/Component/CustomUrl/Tests/Unit/Routing/Enhancers/TrailingSlashEnhancerTest.php
Labels: DX

#5924 Update locale of preview when switching locale of form
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
Labels: Bug

#5934 Fix ImageMapContentType on null value
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/ImageMapContentTypeTest.php
Labels: Bug

#5945 Add resourceTitleLocale to DomainEvent
  UPGRADE.md
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryCreatedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordCreatedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordModifiedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordRemovedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryModifiedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryMovedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryRemovedEvent.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Domain/Event/CustomUrlCreatedEventTest.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Domain/Event/CustomUrlModifiedEventTest.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Domain/Event/CustomUrlRemovedEventTest.php
  src/Sulu/Bundle/CustomUrlBundle/Tests/Unit/Domain/Event/CustomUrlRouteRemovedEventTest.php
  src/Sulu/Bundle/EventLogBundle/Domain/Event/DomainEvent.php
  src/Sulu/Bundle/EventLogBundle/Domain/Model/EventRecord.php
  src/Sulu/Bundle/EventLogBundle/Domain/Model/EventRecordInterface.php
  src/Sulu/Bundle/EventLogBundle/Infrastructure/Doctrine/Repository/EventRecordRepository.php
  src/Sulu/Bundle/EventLogBundle/Resources/config/doctrine/EventRecord.orm.xml
  src/Sulu/Bundle/EventLogBundle/Tests/Functional/Infrastructure/Doctrine/Repository/EventRecordRepositoryTest.php
  src/Sulu/Bundle/EventLogBundle/Tests/Unit/Domain/Event/DomainEventTest.php
  src/Sulu/Bundle/EventLogBundle/Tests/Unit/Domain/Model/EventRecordTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Domain/Event/TagCreatedEventTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Domain/Event/TagMergedEventTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Domain/Event/TagModifiedEventTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Domain/Event/TagRemovedEventTest.php
Labels: DX

#5949 Add more space between avatar and logo to properties
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/account_details.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/forms/contact_details.xml
Labels: DX

#5942 Enable Admin Bundle in website context
  config/bundles.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/AddAdminPass.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/AddAdminPassTest.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: DX

#5933 Allow to set mode of route field type via param in XML template
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
Labels: Feature

#5950 Update ckeditor to 27.1.0
  UPGRADE.md
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  webpack.config.js
Labels: DX, UX

#5951 Update postcss and required dependencies
  package.json
  styleguide.config.js
  webpack.config.js
Labels: DX

#5952 Upgrade react-sortable-hoc to 2.0.0 and query-string to 7.0.0 version
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
Labels: DX

#5967 Fix admin bundle without security checker enabled
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/AddAdminPass.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/AddAdminPassTest.php
Labels: Bug

#5958 Use buildQueryString util instead of external query-string package in PreviewBundle
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
Labels: DX
