Repository sulu/sulu, pull requests merged in 2021-02, with the labels that each got.

#5789 Fix PHP 8 compatibility in AccessControlManager
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
Labels: Bug

#5784 Sort items returned by server to march order of selected ids in MultiSelectionStore
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/MultiSelectionStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/MultiSelectionStore/tests/MultiSelectionStore.test.js
Labels: DX

#5768 Fix format manager generated urls with multiple dots
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
Labels: Bug

#5738 PHPStan level 2 for component webspace
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
Labels: DX

#5739 PHPStan level 2 in smartContent
  src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
Labels: DX

#5767 Add UploadToolbarAction
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldTransformers/BytesFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Bytes/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Bytes/tests/transformBytesToReadableString.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Bytes/transformBytesToReadableString.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/DropdownToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/UploadToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/__snapshots__/UploadToolbarAction.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/UploadToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Feature, UX

#5780 Move blocked_file_types configuration
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/DependencyInjection/SuluMediaExtensionTest.php
Labels: DX

#5758 Add badges to tabs
  src/Sulu/Bundle/AdminBundle/Admin/View/Badge.php
  src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/View/FormViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilder.php
  src/Sulu/Bundle/AdminBundle/Admin/View/PreviewFormViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Admin/View/TabViewChildBuilderTrait.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/Badge.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/badge.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/tests/Badge.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/tests/__snapshots__/Badge.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/Tab.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tab.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/Tabs.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Tabs/tests/__snapshots__/Tabs.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/Badge.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/stores/BadgeStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/tests/Badge.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/tests/stores/BadgeStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Badge/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/Requester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/tests/Requester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Requester/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/Tabs.test.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/BadgeTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormOverlayListViewBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/FormViewBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/ListViewBuilderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/View/PreviewFormViewBuilderTest.php
Labels: Feature, UX

#5777 Add sulu_category_url_remove and sulu_category_url_toggle twig functions
  src/Sulu/Bundle/CategoryBundle/Twig/CategoryTwigExtension.php
  src/Sulu/Component/Category/Request/CategoryRequestHandler.php
  src/Sulu/Component/Category/Request/CategoryRequestHandlerInterface.php
  src/Sulu/Component/Category/Tests/Unit/Request/CategoryRequestHandlerTest.php
Labels: DX

#5792 Fix list padding and disabled input field for safari and firefox
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/chip.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/input.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/textArea.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/url.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/list.scss
Labels: UX

#5803 Handle undefined user-agent in DeviceDetectorSubscriber
  src/Sulu/Bundle/AudienceTargetingBundle/EventListener/DeviceDetectorSubscriber.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/EventListener/DeviceDetectorSubscriberTest.php
Labels: Bug

#5774 Upgrade doctrine packages
  UPGRADE.md
  composer.json
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Category/CategoryManagerTest.php
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/DataFixtures/ORM/LoadDefaultTypes.php
  src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactManagerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/RootPathPurgeInitializer.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/WorkspaceInitializer.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/RootPathPurgeInitializerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/WorkspaceInitializerTest.php
  src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadCollectionTypes.php
  src/Sulu/Bundle/MediaBundle/DataFixtures/ORM/LoadMediaTypes.php
  src/Sulu/Bundle/MediaBundle/EventListener/MediaAudienceTargetingSubscriber.php
  src/Sulu/Bundle/MediaBundle/Media/TypeManager/TypeManager.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/TypeManager/TypeManagerTest.php
  src/Sulu/Bundle/PageBundle/DocumentManager/ContentInitializer.php
  src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php
  src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/UserManager/UserManagerTest.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
  src/Sulu/Bundle/SnippetBundle/Document/SnippetInitializer.php
  src/Sulu/Bundle/TagBundle/Tag/TagManager.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Tag/TagManagerTest.php
  src/Sulu/Component/Doctrine/ReferencesOption.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/TimestampableSubscriber.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
  src/Sulu/Component/Persistence/Repository/RepositoryInterface.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/MetadataSubscriberTest.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/UserBlameSubscriberTest.php
  src/Sulu/Component/Rest/Listing/ListRepository.php
  src/Sulu/Component/Rest/Listing/ListRestHelper.php
  src/Sulu/Component/Rest/Tests/Unit/Listing/ListRestHelperTest.php
  src/Sulu/Component/Security/Authentication/UserSettingRepositoryInterface.php
  src/Sulu/Component/Security/Authorization/AccessControl/DoctrineAccessControlProvider.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/DoctrineAccessControlProviderTest.php
Labels: DX, Feature

#5807 Remove guzzle requirement for PHP 8 support
  composer.json
  src/Sulu/Bundle/LocationBundle/DependencyInjection/SuluLocationExtension.php
  src/Sulu/Bundle/LocationBundle/Resources/config/geolocator.xml
  src/Sulu/Bundle/LocationBundle/Resources/config/guzzle.xml
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/GoogleGeolocatorTest.php
Labels: DX

#5811 Fix psr18 client min requirements for using symfony http client
  composer.json
Labels: Bug

#5814 Use the antishov/doctrine-extensions-bundle for PHP 8 compatibility
  composer.json
Labels: DX

#5813 Prepare PHP 8 compatibility
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/MediaImageExtractorTest.php
  src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
  src/Sulu/Component/Rest/RestControllerTrait.php
  src/Sulu/Component/Util/SuluNodeHelper.php
  src/Sulu/Component/Util/Tests/Unit/SortUtilsTest.php
  src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
Labels: DX

#5810 Add repository interface as alias for persistence bundle service ids
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/services.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/TagBundle/Resources/config/services.xml
Labels: DX

#5798 Add visible property to NavigationItem to allow for hiding navigation items
  src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/Navigation.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/Navigation.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/tests/registries/NavigationRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Navigation/types.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
Labels: Feature

#5797 Display helpful error message if uploaded media is blocked or exceeds maximum filesize
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/InvalidFileException.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/InvalidFileTypeException.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/MaxFileSizeExceededException.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/UploadFileNotSetException.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/MediaCollection.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/MediaOverview.js
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/MediaOverview.test.js
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/MediaBundle/Resources/translations/admin.en.json
Labels: UX

#5818 Prepare PHP 8 compatibility for 2.2
  src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
Labels: DX

#5812 Remove url validation
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/tests/Url.test.js
Labels: Bug

#5782 Add marker interface for DocumentManager event subscribers to enable autoconfiguration
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
  src/Sulu/Component/DocumentManager/Subscriber/EventSubscriberInterface.php
Labels: DX

#5815 Remove email validation from js component
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/StringMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/Email.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/Email.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Email/tests/__snapshots__/Email.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/MemoryFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/ResourceFormStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/stores/memoryFormStoreFactory.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/createAjv.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/formats/idnEmailValidator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/formats/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/formats/tests/idnEmailValidator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/keywords/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/keywords/nameDefinition.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/StringMetadataTest.php
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/tests/__snapshots__/ContactDetails.test.js.snap
  src/Sulu/Bundle/PageBundle/Content/Types/Email.php
  src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
  src/Sulu/Bundle/PageBundle/Tests/Unit/Content/Types/EmailTest.php
Labels: Feature, UX

#5834 Resolve absolute urls for sulu-link tags
  src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php
  src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/LinkTagTest.php
Labels: Bug

#5757 Add php 8 support
  .github/workflows/test-application.yaml
  appveyor.yml
  composer.json
Labels: DX, Feature, Performance

#5839 Fix category not found and fallback to default locale for category converter
  src/Sulu/Bundle/CategoryBundle/Search/Converter/CategoryConverter.php
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Search/Converter/CategoryConverterTest.php
Labels: Bug

#5837 Replace appveyor with github actions
  .github/workflows/test-application.yaml
  appveyor.yml
  src/Sulu/Bundle/TranslateBundle/Tests/Functional/Translate/ExportTest.php
Labels: DX

#5833 Load page teasers from phpcr
  UPGRADE.md
  src/Sulu/Bundle/PageBundle/Controller/TeaserController.php
  src/Sulu/Bundle/PageBundle/Resources/config/teaser.xml
  src/Sulu/Bundle/PageBundle/Teaser/PHPCRPageTeaserProvider.php
  src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Teaser/PHPCRPageTeaserProviderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Teaser/PageTeaserProviderTest.php
Labels: Performance

#5832 Fix snippet copy locale
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
Labels: Bug

#5849 Prevent doubleclick of item while ordering column list
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/Item.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/item.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/Item.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ColumnList/tests/__snapshots__/Item.test.js.snap
Labels: Bug, UX
