Repository sulu/sulu, pull requests merged in 2022-12, with the labels that each got.

#6690 Upgrade webpack to version 5
  UPGRADE.md
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/blockCollection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Url/Url.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/formats/idnEmailValidator.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Ajv/formats/tests/idnEmailValidator.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Email/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Email/tests/validateEmail.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Email/validateEmail.js
  webpack.config.js
Labels: DX

#6929 Update js dependencies babel-loader, postcss, styleguidist and stylelint packages
  UPGRADE.md
  package.json
Labels: DX

#6916 Add emoji support for url slugger
  src/Sulu/Component/PHPCR/PathCleanup.php
  src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
Labels: Feature

#6928 Improving the role querying in user creation
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
Labels: Performance

#6932 Update phpstan baseline
  phpstan-baseline.neon
Labels: DX

#6933 Fix phpstan baseline error and update jest snapshot for QRCode lib
  .env
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/tests/__snapshots__/QRCode.test.js.snap
Labels: DX

#6927 Add `active` index for table `at_target_groups`
  UPGRADE.md
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/doctrine/TargetGroup.orm.xml
Labels: Performance

#6934 Fix admin build with webpack 4
  babel.config.json
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldTransformers/HtmlFieldTransformer.js
  webpack.config.js
Labels: Bug

#6936 Fix snapshot test of qrcode library
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/tests/__snapshots__/QRCode.test.js.snap
Labels: DX

#6941 Changed height of description-label and error-label to min-height
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/field.scss
Labels: Bug

#6943 Change help and error messages from <label> to <div>
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Form/tests/__snapshots__/Form.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Field.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/GhostDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/MissingTypeDialog.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Renderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/__snapshots__/Section.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/overlays/__snapshots__/ExternalLinkTypeOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/overlays/__snapshots__/LinkTypeOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/containers/TargetGroupRules/tests/__snapshots__/RuleOverlay.test.js.snap
  src/Sulu/Bundle/ContactBundle/Resources/js/components/ContactDetails/tests/__snapshots__/ContactDetails.test.js.snap
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/__snapshots__/LocationOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Link/tests/overlays/__snapshots__/MediaLinkTypeOverlay.test.js.snap
Labels: Bug

#6946 Fix background color of matrix item
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Matrix/item.scss
Labels: Bug

#6949 Make folders keyboard operable
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FolderList/Folder.js
Labels: UX

#6951 Make table actions reachable for keyboards
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Table/table.scss
Labels: UX

#6953 Wrap masonry item in unordered list element
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Masonry/Masonry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Masonry/tests/__snapshots__/Masonry.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/List/tests/adapters/__snapshots__/MediaCardOverviewAdapter.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
Labels: Bug

#6959 Fix webpack build and slim dependency
  .browserslistrc
  babel.config.json
  package.json
  webpack.config.js
Labels: Bug

#6963 Fix for latitude and longitude german translations
  src/Sulu/Bundle/ContactBundle/Resources/translations/admin.de.json
Labels: Bug

#6964 Move config from inline js to data attr
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Config/Config.js
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
Labels: Feature
