Repository sulu/sulu, pull requests merged in 2022-04, with the labels that each got.

#6519 Prevent infinite loading of contact_account_selection
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/ContactAccountSelection.js
  src/Sulu/Bundle/ContactBundle/Resources/js/containers/ContactAccountSelection/tests/ContactAccountSelection.test.js
Labels: Bug

#6502 Fixed the meta title of the Sulu admin
  src/Sulu/Bundle/AdminBundle/Resources/views/Admin/main.html.twig
Labels: UX

#6526 Catch invalid path exception from phpcr in load by resource-locator
  src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
Labels: Bug

#6534 Fix handling of homepage for invalid path check
  src/Sulu/Component/Content/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
Labels: Bug

#6506 Add qrcode field type
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/QRCode.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/qrcode.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/tests/QRCode.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/tests/__snapshots__/QRCode.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/QRCode/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/QRCode.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: Feature

#6540 Fix cache clear when cache tags are disabled
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
  src/Sulu/Bundle/WebsiteBundle/Cache/CacheClearer.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
Labels: Bug

#6550 Allow newer version of matomo device detector
  composer.json
Labels: DX

#6554 Fix symfony type warning message
  src/Sulu/Bundle/ActivityBundle/SuluActivityBundle.php
Labels: DX

#6555 Fix symfony type warning message
  src/Sulu/Bundle/PreviewBundle/SuluPreviewBundle.php
  src/Sulu/Bundle/TrashBundle/SuluTrashBundle.php
Labels: DX

#6560 Add php-cs-fixer global import rule for classes
  .php-cs-fixer.dist.php
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactTitle.php
  src/Sulu/Bundle/ContactBundle/Entity/Position.php
  src/Sulu/Bundle/MarkupBundle/Listener/SwiftMailerListener.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/MediaException.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaWebsiteControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Exception/AssignAnonymousRoleException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/SecurityException.php
  src/Sulu/Bundle/TagBundle/Tag/Exception/TagAlreadyExistsException.php
  src/Sulu/Bundle/TagBundle/Tag/Exception/TagNotFoundException.php
  src/Sulu/Component/Content/Compat/Structure.php
  src/Sulu/Component/Content/Compat/StructureInterface.php
  src/Sulu/Component/Content/Exception/ResourceLocatorGeneratorException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorMovedException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorNotFoundException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorNotValidException.php
  src/Sulu/Component/Content/Metadata/Loader/Exception/TemplateException.php
  src/Sulu/Component/Content/Metadata/Loader/Exception/TemplateNotFoundException.php
  src/Sulu/Component/Content/Template/Exception/TemplateException.php
  src/Sulu/Component/Content/Template/Exception/TemplateNotFoundException.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
  src/Sulu/Component/Content/Types/ResourceLocator/ResourceLocatorInformation.php
  src/Sulu/Component/Doctrine/ReferencesOption.php
  src/Sulu/Component/Persistence/RelationTrait.php
  src/Sulu/Component/Rest/Exception/RestException.php
  src/Sulu/Component/Rest/RestHelperInterface.php
  src/Sulu/Component/Security/Authorization/AccessControl/DoctrineAccessControlProvider.php
  src/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProvider.php
  src/Sulu/Exception/FeatureNotImplementedException.php
Labels: DX

#6564 Replace antishov/doctrine-extensions-bundle with stof/doctrine-extensions-bundle
  composer.json
Labels: DX

#6567 Fix configuration deprecation calls
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/LocationBundle/Resources/config/guzzle.xml
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
Labels: DX

#6568 Fix passconfig type for document manager event registerlistenerpass
  src/Sulu/Bundle/DocumentManagerBundle/SuluDocumentManagerBundle.php
Labels: DX
