Repository sulu/sulu, pull requests merged in 2022-05, with the labels that each got.

#6573 Upgrade lazy security configuration
  config/packages/security.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/config.yml
Labels: DX

#6575 Update request type from MASTER_REQUEST to MAIN_REQUEST
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
Labels: DX

#6580 Upgrade WebsiteController for Symfony 6 compatibility
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
Labels: DX

#6584 Upgrade the FlattenExceptionNormalizer for Symfony 6 compatibility
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
Labels: DX

#6585 Fix custom url route parameter symfony 6 compatibility and remove unnecessary configuration and lines
  src/Sulu/Bundle/CustomUrlBundle/Resources/config/routing.xml
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerAdminTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/CacheControllerTest.php
Labels: DX

#6591 Relay deletion errors to snackbar
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/MediaCollection.js
Labels: Bug

#6572 Render add button when hovering space between blocks
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/blockCollection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/sortableBlockList.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
Labels: Feature

#6602 Fix prophecy deprecation warning
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Metadata/PasswordPolicyFormMetadataVisitorTest.php
Labels: DX

#6601 Upgrade document manager cache service definition and http cache return types
  UPGRADE.md
  config/packages/sulu_document_manager.yaml
  src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php
  src/Sulu/Bundle/SecurityBundle/Security/LogoutSuccessHandler.php
Labels: DX

#6604 Upgrade Security configuration with enable_authenticator_manager true
  UPGRADE.md
  config/packages/security.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/CollaborationControllerTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/config.yml
Labels: DX

#6619 Fix sortBy in DataProviderRepositoryTrait
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
Labels: Bug

#6620 Rerender form fields when type changes to prevent stale components
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Renderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
Labels: Bug

#6614 Remove unused eslint-disable directives
  .eslintrc.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldFilterTypes/AbstractFieldFilterType.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TableAdapter.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/TreeTableAdapter.test.js
Labels: DX

#6599 Replace remove block button with dropdown that can display multiple actions
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/ActionPopover.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/ActionPopoverItem.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/Block.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/actionPopoverItem.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/Block.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/tests/__snapshots__/Block.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlock.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/SortableBlockList.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/SortableBlock.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/BlockCollection.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/__snapshots__/SortableBlock.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/Icon.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/tests/Icon.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/__snapshots__/FieldBlocks.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/List.test.js
Labels: UX

#6624 Add block action for duplication existing block
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Feature, UX

#6625 Add LogoutSuccessHandler bridge between Symfony 5.4 and 6.0
  src/Sulu/Bundle/SecurityBundle/Security/LogoutSuccessHandler.php
  src/Sulu/Bundle/SecurityBundle/Security/LogoutSuccessHandlerInterface.php
Labels: DX
