Repository sulu/sulu, pull requests merged in 2022-06, with the labels that each got.

#6628 Allow reference cascading when deleting tags
  UPGRADE.md
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Group.orm.xml
  src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml
Labels: Bug

#6630 Implement block action for copying and cutting a single block
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/actionPopoverItem.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/blockCollection.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/selection.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/sulu-icon.css
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/clipboard/clipboard.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/clipboard/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/clipboard/tests/clipboard.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/clipboard/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/index.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Feature, UX

#6641 Update files from skeleton
  config/bootstrap.php
  config/packages/security.yaml
  config/packages/stof_doctrine_extensions.yaml
  config/routes.yaml
  config/routes/annotations.yaml
  config/routes/annotations_admin.yaml
  config/routes/annotations_website.yaml
  config/routes_admin.yaml
  config/routes_website.yaml
  config/services.yaml
  public/index.php
Labels: Bug

#6651 Fix logout response for symfony 6
  src/Sulu/Bundle/SecurityBundle/EventListener/LogoutEventSubscriber.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/LogoutEventSubscriberTest.php
Labels: Bug

#6658 Add test cases for copy and paste functionality of blocks
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/BlockCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/tests/FieldBlocks.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/clipboard/tests/clipboard.test.js
Labels: DX
