Repository sulu/sulu, pull requests merged in 2022-11, with the labels that each got.

#6876 Fix overlay path in icon font (Sulu 2.4)
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.svg
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.ttf
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/fonts/sulu.woff
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Icon/selection.json
Labels: Bug, UX

#6885 Fix border colors of buttons inside buttonGroup
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/buttonGroup.scss
Labels: Bug

#6887 Update phpstan baseline 1.9.0
  phpstan-baseline.neon
Labels: DX

#6892 Add helpfully links to browser dev console in Sulu Admin
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: DX

#6895 Add FOSJSRouting endpoint regression test
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/FOSJSRoutingControllerTest.php
Labels: Technical Debt

#6897 Update phpstan baseline and fix tokengenerator error
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/Util/TokenGenerator.php
Labels: DX

#6898 Fix node lint task
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
Labels: DX

#6899 Update phpstan baseline
  phpstan-baseline.neon
Labels: DX

#6902 Fix default-user placeholder contrast
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Navigation/userSection.scss
Labels: UX

#6904 Allows CategoryConverter to convert documents without a locale
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Controller/KeywordController.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryInterface.php
  src/Sulu/Bundle/CategoryBundle/Search/Converter/CategoryConverter.php
Labels: Bug

#6907 Ignore php.ini and .php-version
  .gitignore
Labels: DX

#6893 Adding admin resource URLs to FOSJsRouter automatically
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/ExposeResourceRoutesPass.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
  src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/LocationBundle/DependencyInjection/SuluLocationExtension.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/SearchBundle/DependencyInjection/SuluSearchExtension.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
Labels: Feature, DX

#6906 Add page resource segment to PageRemovedEvent
  src/Sulu/Bundle/PageBundle/Domain/Event/PageRemovedEvent.php
  src/Sulu/Bundle/PageBundle/EventListener/DomainEventSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/EventListener/DomainEventSubscriberTest.php
  src/Sulu/Bundle/TestBundle/Testing/SetGetPrivatePropertyTrait.php
Labels: Feature

#6910 Add support for avif image formats
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
Labels: Feature
