Repository sulu/sulu, pull requests merged in 2022-10, with the labels that each got.

#6836 Add indexes to improve performance of route table query
  UPGRADE.md
  src/Sulu/Bundle/RouteBundle/Resources/config/doctrine/Route.orm.xml
Labels: Performance

#6841 Fix missing icons for copy toolbar actions
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyLocaleToolbarAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Form/toolbarActions/CopyToolbarAction.js
Labels: Bug, UX

#6844 Fix flacky UserControllerTest
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
Labels: DX

#6848 Fix TargetGroupSubscriber throw error on BinaryFileResponse
  src/Sulu/Bundle/AudienceTargetingBundle/EventListener/TargetGroupSubscriber.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
Labels: Bug

#6849 Remove deprecated urls variable from sulu_content_load result
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
Labels: DX

#6850 Fix PHPdoc types for name in media API class
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Api/Media.php
Labels: DX

#6852 Remove self closing slash from seo tags
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Extension/seo.html.twig
Labels: Bug

#6861 Add restart of preview when locale of form is changed
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
Labels: Bug

#6807 Fix query parameters for external links
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/overlays/ExternalLinkTypeOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/overlays/ExternalLinkTypeOverlay.test.js
Labels: Bug

#6869 Update phpstan baseline
  phpstan-baseline.neon
Labels: DX

#6859 Add copy-snippet button in form
  phpstan-baseline.neon
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Component/Content/Document/Subscriber/WebspaceSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WebspaceSubscriberTest.php
Labels: Feature

#6868 Add condition to StructureProvider
  src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
Labels: Performance, DX

#6871 Fix phpstan issue and code style
  src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
Labels: DX

#6875 Fix context of start function inside of restart
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/stores/PreviewStore.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/stores/PreviewStore.test.js
Labels: Bug

#6879 Fix search mapping prefix with multiple block types
  src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
Labels: Bug
