Repository sulu/sulu, pull requests merged in 2022-07, with the labels that each got.

#6670 Avoid admin UI crash with false translation
  src/Sulu/Bundle/AdminBundle/Resources/js/utils/Translator/Translator.js
Labels: Bug

#6676 Add support for position sticky inside tabs container
  src/Sulu/Bundle/AdminBundle/Resources/js/components/View/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/View/View.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/View/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/View/variables.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/View/view.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/ViewRenderer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/registries/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/registries/viewRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/ViewRenderer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/__snapshots__/ViewRenderer.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/tests/registries/ViewRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ViewRenderer/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/Tabs.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tabs.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/views/Tabs/tests/__snapshots__/Tabs.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/index.js
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/pageList.scss
  src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/tests/__snapshots__/WebspaceTabs.test.js.snap
  src/Sulu/Bundle/PageBundle/Resources/js/views/WebspaceTabs/variables.scss
Labels: Feature

#5129 Add sticky ckeditor toolbar
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FormOverlay/formOverlay.scss
Labels: UX

#6680 Move js linting in own task
  .github/workflows/test-application.yaml
Labels: DX

#6688 Upgrade ckeditor to version 34.2.0 and postcss to version 8
  UPGRADE.md
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/CKEditor5.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  webpack.config.js
Labels: DX

#6683 Add floating snackbar
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Block/block.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/BlockCollection.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockToolbar/BlockToolbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockToolbar/blockToolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/Snackbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/snackbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/Snackbar.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Snackbar/tests/__snapshots__/Snackbar.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SnackbarContainer/README.md
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SnackbarContainer/SnackbarContainer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SnackbarContainer/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/SnackbarContainer/snackbarContainer.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/Application.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/FieldBlocks/FieldBlocks.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/snackbarStore/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/snackbarStore/snackbarStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/snackbarStore/tests/snackbarStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/snackbarStore/types.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Feature

#6694 Fix path to ckeditor theme in webpack config
  webpack.config.js
Labels: Bug

#6478 Add possibility for query parameters in link field type and ckeditor link overlay
  config/templates/pages/example.xml
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/InternalLinkPlugin.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Link.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Link.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/Link.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/overlays/LinkTypeOverlay.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/Link.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/overlays/LinkTypeOverlay.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/tests/overlays/__snapshots__/LinkTypeOverlay.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Link/types.js
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Component/Content/Tests/Unit/Types/LinkTest.php
  src/Sulu/Component/Content/Types/Link.php
Labels: Feature

#6682 Add possibility to use translation keys in template meta information
  src/Sulu/Bundle/PageBundle/Resources/config/structure.xml
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
  tests/Resources/DataFixtures/Page/template_with_localizations.xml
Labels: Feature

#6697 Fix relogin after logout
  src/Sulu/Bundle/AdminBundle/Resources/js/services/initializer/initializer.js
Labels: Bug

#6698 Add configurable two factor email and fix blocktoolbar styling for nested blocks
  src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockToolbar/blockToolbar.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Application/application.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/TwoFactorForm.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Login/tests/__snapshots__/TwoFactorForm.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/BackupCodeInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/EmailInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/EmailTrait.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/GoogleInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/PreferredProviderInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/TotpInterface.php
  src/Sulu/Bundle/SecurityBundle/Entity/TwoFactor/TrustedDeviceInterface.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/2fa_email.xml
  src/Sulu/Bundle/SecurityBundle/Resources/views/mail_templates/two_factor.html.twig
  src/Sulu/Bundle/SecurityBundle/Resources/views/mail_templates/two_factor.txt.twig
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/TwoFactor/AuthCodeMailerTest.php
  src/Sulu/Bundle/SecurityBundle/TwoFactor/AuthCodeMailer.php
  src/Sulu/Bundle/SecurityBundle/TwoFactor/AuthCodeMailerInterface.php
Labels: Feature

#6701 Update code style
  public/index.php
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Navigation/NavigationItemTest.php
  src/Sulu/Bundle/CategoryBundle/Category/KeywordManager.php
  src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Slugifier/Urlizer.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Functional/BaseTestCase.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/PageBundle/Teaser/PageTeaserProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Content/PageSelectionContainerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Command/SnippetLocaleCopyCommandTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Domain/Event/TagRemovedEventTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Tag/TagManagerTest.php
  src/Sulu/Component/Content/Document/Subscriber/ShadowLocaleSubscriber.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
  src/Sulu/Component/Hash/Tests/RequestHashCheckerTest.php
  src/Sulu/Component/Media/SmartContent/MediaDataItem.php
  src/Sulu/Component/PHPCR/PathCleanup.php
  src/Sulu/Component/PHPCR/SessionManager/SessionManager.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
  src/Sulu/Component/SmartContent/ContentType.php
  src/Sulu/Component/Webspace/Tests/Unit/EnvironmentTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Settings/SettingsManagerTest.php
Labels: DX

#6700 Fix missing translations
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/AdminBundle/Resources/translations/admin.en.json
Labels: Bug

#6691 Upgrade stylelint and stylelint recommended package
  package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/components/ImageFocusPoint/imageFocusPointCell.scss
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/public-preview.scss
  stylelint.config.js
Labels: DX

#6715 Add better error handling to the block property for non array values
  src/Sulu/Component/Content/Compat/Block/BlockProperty.php
  src/Sulu/Component/Content/Tests/Unit/Block/BlockPropertyTest.php
Labels: DX

#6719 Badge component test migrations
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/tests/Badge.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Badge/tests/__snapshots__/Badge.test.js.snap
Labels: DX

#6726 Migrate enzyme ButtonGroup tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/tests/ButtonGroup.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/ButtonGroup/tests/__snapshots__/ButtonGroup.test.js.snap
Labels: DX

#6727 Migrate enzyme Card & CardCollection tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Card/tests/Card.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Card/tests/__snapshots__/Card.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CardCollection/tests/CardCollection.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CardCollection/tests/__snapshots__/CardCollection.test.js.snap
Labels: DX

#6721 Migrate enzyme Button tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/Button.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Button/tests/__snapshots__/Button.test.js.snap
Labels: DX

#6729 Fix ImageMap with custom admin path
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/ImageMap/ImageRenderer.js
Labels: Bug

#6732 Migrate enzyme Chip tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/Chip.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Chip/tests/__snapshots__/Chip.test.js.snap
Labels: DX

#6731 Migrate enzyme Checkbox & CheckboxGroup tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/Checkbox.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/CheckboxGroup.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/__snapshots__/Checkbox.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Checkbox/tests/__snapshots__/CheckboxGroup.test.js.snap
Labels: DX

#6735 Migrate enzyme CroppedText tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/tests/CroppedText.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CroppedText/tests/__snapshots__/CroppedText.test.js.snap
Labels: DX

#6725 Migrate enzyme Breadcrumb tests to React Testing Library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Breadcrumb/tests/Breadcrumb.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Breadcrumb/tests/__snapshots__/Breadcrumb.test.js.snap
Labels: DX
