Repository sulu/sulu, pull requests merged in 2023-02, with the labels that each got.

#6989 Check if security->getUser() is instance of UserInterface
  src/Sulu/Bundle/TrashBundle/Infrastructure/Doctrine/Repository/TrashItemRepository.php
Labels: Bug

#6991 Fix phpstan baseline by set FlattenExceptionNormalizer return type
  phpstan-baseline.neon
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
Labels: DX

#6998 Include categories and tags in the account/contact export
  composer.json
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/accounts.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/lists/contacts.xml
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
Labels: Feature

#7005 Catch MediaNotFoundException in MediaRedirectController
  src/Sulu/Bundle/MediaBundle/Controller/MediaRedirectController.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaRedirectControllerTest.php
Labels: Bug

#7007 Backport skip if webspace unavailable in deleteUnavailableLocales
  phpstan-baseline.neon
  src/Sulu/Component/Content/Document/Subscriber/WebspaceSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/WebspaceSubscriberTest.php
Labels: DX

#7004 Remove reference to LiipThemeBundle and dispatch event instead
  UPGRADE.md
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
  src/Sulu/Bundle/PageBundle/Resources/config/command.xml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ValidateWebspacesCommandTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Command/ValidateWebspacesCommandTest.php
Labels: Feature

#7008 Use php-cs-fixer shim
  .github/workflows/test-application.yaml
  composer.json
Labels: DX

#7009 Allow newer version of doctrine/annotations
  composer.json
Labels: DX

#7012 Add media data provider datetime sorting
  src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
Labels: Feature

#7014 Change query for find custom-url by page to improve performance
  src/Sulu/Component/CustomUrl/Manager/CustomUrlManager.php
Labels: Performance

#6962 [DX] Adding types for list metadata configuration
  phpstan-baseline.neon
  src/Sulu/Component/Rest/ListBuilder/Metadata/AbstractPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/CasePropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ConcatenationPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/CountPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/GroupConcatPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/IdentityPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/JoinMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ListMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ListXmlLoader.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/SinglePropertyMetadata.php
  src/Sulu/Component/Util/XmlUtil.php
Labels: DX
