Repository sulu/sulu, pull requests merged in 2023-08, with the labels that each got.

#7128 Conflict incompatible version 2.16.0 of doctrine/orm
  composer.json
Labels: Bug

#7127 Upgrade phpstan baseline
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/RoleSettingRepository.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
  src/Sulu/Component/Cache/MemoizeTwigExtensionTrait.php
  src/Sulu/Component/Content/ContentTypeManager.php
Labels: DX

#7135 Fixing workflow badge
  README.md
Labels: DX

#7141 Expand conflicting versions for doctrine/orm
  composer.json
Labels: Bug

#7146 Fix dynamic property issues in phpstan via rector
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/CoreBundle/Tests/Unit/Cache/StructureWarmerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/InitializeCommandTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/DataFixtures/DocumentExecutorTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Initialalizer/WorkspaceInitializerTest.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/DependencyInjection/SuluHttpCacheExtensionTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/GeolocatorResponseTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaWebsiteControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Search/Subscriber/MediaSearchSubscriberTest.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201511240843.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/ResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Markup/LinkTagTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/GroupControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Export/SnippetTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/EventListener/SegmentSubscriberTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapGeneratorTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapProviderPoolTest.php
  src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTwigExtensionTraitTest.php
  src/Sulu/Component/Content/Tests/Unit/ContentTypeManagerTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ChildrenCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/QueryResultCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ReferrerCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/DocumentAccessorTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/DocumentHelperTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/DocumentInspectorTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/DocumentRegistryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/NamespaceRegistryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Query/QueryTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Behavior/Mapping/LocaleSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Behavior/Mapping/UuidSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Core/InstantiatorSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/FindSubscriberTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Phpcr/RemoveSubscriberTest.php
  src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/TimestampableSubscriberTest.php
  src/Sulu/Component/Rest/Tests/Functional/ListBuilder/Metadata/FieldDescriptorFactoryTest.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalInformationTest.php
Labels: DX

#7148 Fix incompatibility to Symfony 6.4 renderBlock method
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/Controller/WebsiteController.php
Labels: Bug, DX

#7151 Remove support for Node 12 in sulu admins
  .github/workflows/test-application.yaml
  UPGRADE.md
Labels: Bug
