Repository sulu/sulu, pull requests merged in 2023-11, with the labels that each got.

#7206 Add experimental support for bun
  preinstall.js
Labels: Feature, DX

#7209 Fix parameter type of portal
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Admin/MediaAdminTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Admin/PageAdminTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Build/NodeOrderBuilderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Command/MaintainResourceLocatorCommandTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/DefaultSnippetManagerTest.php
  src/Sulu/Component/Webspace/Manager/WebspaceCollection.php
  src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionBuilderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionTest.php
Labels: DX

#7186 Fixed deprecation happening when content type is checked in AppendAnalyticsListener
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/EventListener/AppendAnalyticsListener.php
Labels: Bug

#7164 Fix link content type return old file version
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
Labels: Bug

#7163 Fix categories menu permissions
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Admin/CategoryAdminTest.php
Labels: Bug
