Repository sulu/sulu, pull requests merged in 2023-03, with the labels that each got.

#7024 remove snippet mention from export base class
  src/Sulu/Component/Export/Export.php
Labels: DX

#7020 Change google tag manager and google analytics templates for JS and iframes to always use https
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/google/head-close.html.twig
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/google_tag_manager/body-open.html.twig
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/google_tag_manager/head-open.html.twig
Labels: Feature

#7029 Fix unexpected jackalope behaviour by making phpcr sessions lazy
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
Labels: Bug

#7034 Run tests against php 8.2
  .github/workflows/test-application.yaml
Labels: DX

#7039 Fix pre and postinstall parameters for custom admin build
  symlink-vendor-directory.js
Labels: Bug

#7050 Replace string class with Object::class
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/RuleCollectionTest.php
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/CoreBundle/Tests/Unit/Cache/StructureWarmerTest.php
  src/Sulu/Bundle/CoreBundle/Tests/Unit/DependencyInjection/SuluCoreExtensionTest.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/DependencyInjection/Compiler/InitializerPassTest.php
  src/Sulu/Bundle/LocationBundle/DependencyInjection/SuluLocationExtension.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/GeolocatorResponseTest.php
  src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/SearchIntegration/SearchIntegrationTest.php
  src/Sulu/Bundle/PageBundle/Form/Type/HomeDocumentType.php
  src/Sulu/Bundle/PageBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Mapper/ContentMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
  src/Sulu/Bundle/PersistenceBundle/DependencyInjection/PersistenceExtensionTrait.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationEntryPointTest.php
  src/Sulu/Bundle/SnippetBundle/Form/SnippetType.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Compiler/RouteProviderCompilerPass.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/RequestAnalyzerResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/StructureResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapGeneratorTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
  src/Sulu/Component/Content/Tests/Unit/Compat/StructureManagerTest.php
  src/Sulu/Component/Content/Tests/Unit/ContentTypeManagerTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ChildrenCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/QueryResultCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Collection/ReferrerCollectionTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Metadata/BaseMetadataFactoryTest.php
  src/Sulu/Component/Localization/Tests/Unit/Manager/LocalizationManagerTest.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/TimestampableSubscriber.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
  src/Sulu/Component/Rest/Tests/Unit/DoctrineRestHelperTest.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Expression/Doctrine/DoctrineAndExpressionTest.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Expression/Doctrine/DoctrineBetweenExpressionTest.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Expression/Doctrine/DoctrineInExpressionTest.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Expression/Doctrine/DoctrineOrExpressionTest.php
  src/Sulu/Component/Rest/Tests/Unit/RequestParametersTraitTest.php
  src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionBuilderTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalInformationTest.php
Labels: DX
