Repository sulu/sulu, pull requests merged in 2023-06, with the labels that each got.

#7099 Fix React-Styleguidist to ~13.0.0 for React 17 support
  package.json
Labels: Bug

#7100 Fix some phpstan and php-cs-fixer issues
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Api/Category.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
  src/Sulu/Bundle/MediaBundle/Api/Media.php
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Media/FileValidator/FileValidator.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
  src/Sulu/Bundle/PageBundle/Controller/TeaserController.php
  src/Sulu/Bundle/PageBundle/Repository/NodeRepository.php
  src/Sulu/Bundle/RouteBundle/Manager/RouteManagerInterface.php
  src/Sulu/Bundle/SecurityBundle/Controller/GroupController.php
  src/Sulu/Bundle/SecurityBundle/Serializer/Subscriber/SecuritySubscriber.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/BaseFunctionalTestCase.php
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
  src/Sulu/Bundle/WebsiteBundle/Analytics/AnalyticsManagerInterface.php
  src/Sulu/Bundle/WebsiteBundle/EventSubscriber/AnalyticsSerializeEventSubscriber.php
  src/Sulu/Component/Content/Compat/Structure.php
  src/Sulu/Component/Content/Compat/Structure/LegacyPropertyFactory.php
  src/Sulu/Component/Content/Mapper/ContentMapperInterface.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
Labels: DX

#7101 Fix session ini_set issue with Symfony 6.3
  src/Sulu/Bundle/TestBundle/Resources/app/config/security-5-4.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/security-6.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/symfony-5-4.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/symfony-6.yml
Labels: Bug

#7089 Fix Symfony deprecation for not declaring getSupportedTypes on FlattenExceptionNormalizer
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
Labels: DX

#7077 Fix trash action failure with null security context
  phpstan-baseline.neon
  src/Sulu/Bundle/TrashBundle/Tests/Functional/UserInterface/Controller/Admin/TrashItemControllerTest.php
  src/Sulu/Bundle/TrashBundle/UserInterface/Controller/Admin/TrashItemController.php
Labels: Bug

#7053 Removing deprecated functions
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/localizationStore/tests/LocalizationStore.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/localizationStore/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/tests/userStore.test.js
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/RoleAssignment.test.js
  src/Sulu/Bundle/SecurityBundle/Resources/js/containers/RoleAssignments/tests/RoleAssignments.test.js
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/XmlSitemapRendererTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/MetaTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/Seo/SeoTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php
  src/Sulu/Component/Localization/Localization.php
  src/Sulu/Component/Localization/Tests/Unit/LocalizationTest.php
  src/Sulu/Component/Security/Event/PermissionUpdateEvent.php
  src/Sulu/Component/Webspace/Loader/XmlFileLoader10.php
  src/Sulu/Component/Webspace/Portal.php
  src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
  src/Sulu/Component/Webspace/Tests/Unit/Loader/XmlFileLoader11Test.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalTest.php
  src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
  src/Sulu/Component/Webspace/Webspace.php
  tests/Resources/DataFixtures/Webspace/xdefault/sulu.io_no_xdefault_locale.xml
  tests/Resources/DataFixtures/Webspace/xdefault/sulu.io_xdefault_locale.xml
Labels: DX

#7054 Using constructor property promotion for better types
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Admin/Navigation/NavigationItem.php
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php
  src/Sulu/Bundle/ContactBundle/Tests/Unit/CustomerIdConverterTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Unit/IndexComparatorTest.php
  src/Sulu/Bundle/ContactBundle/Twig/ContactTwigExtension.php
  src/Sulu/Bundle/MarkupBundle/Markup/Link/ProviderNotFoundException.php
  src/Sulu/Bundle/MarkupBundle/Tag/TagNotFoundException.php
  src/Sulu/Bundle/SnippetBundle/Snippet/SnippetNotFoundException.php
  src/Sulu/Component/Content/ComplexContentType.php
  src/Sulu/Component/Content/Exception/InvalidBlockDefaultTypeException.php
  src/Sulu/Component/Content/Exception/InvalidOrderPositionException.php
  src/Sulu/Component/Content/Exception/NoSuchPropertyException.php
  src/Sulu/Component/Content/Exception/ReservedPropertyNameException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorAlreadyExistsException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorGeneratorException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorMovedException.php
  src/Sulu/Component/Content/Exception/ResourceLocatorNotValidException.php
  src/Sulu/Component/Content/Exception/StateNotFoundException.php
  src/Sulu/Component/Content/Exception/StateTransitionException.php
  src/Sulu/Component/Content/Exception/TranslatedNodeNotFoundException.php
  src/Sulu/Component/Content/Exception/UnexpectedPropertyType.php
  src/Sulu/Component/Content/Template/Exception/InvalidXmlException.php
  src/Sulu/Component/Content/Template/Exception/RequiredPropertyNameNotFoundException.php
  src/Sulu/Component/Content/Template/Exception/ReservedPropertyNameException.php
  src/Sulu/Component/Content/Template/Exception/TemplateException.php
  src/Sulu/Component/Content/Template/Exception/TemplateNotFoundException.php
  src/Sulu/Component/Content/Types/ResourceLocator/Strategy/ResourceLocatorStrategyNotFoundException.php
  src/Sulu/Component/Rest/Csv/ObjectNotSupportedException.php
  src/Sulu/Component/Rest/Exception/ConstraintViolationException.php
  src/Sulu/Component/Rest/Exception/EntityIdAlreadySetException.php
  src/Sulu/Component/Rest/Exception/EntityNotFoundException.php
  src/Sulu/Component/Rest/Exception/InsufficientDescendantPermissionsException.php
  src/Sulu/Component/Rest/Exception/InvalidArgumentException.php
  src/Sulu/Component/Rest/Exception/InvalidHashException.php
  src/Sulu/Component/Rest/Exception/MissingArgumentException.php
  src/Sulu/Component/Rest/Exception/MissingParameterChoiceException.php
  src/Sulu/Component/Rest/Exception/MissingParameterException.php
  src/Sulu/Component/Rest/Exception/ParameterDataTypeException.php
  src/Sulu/Component/Rest/Exception/ReferencingResourcesFoundException.php
  src/Sulu/Component/Rest/Exception/RestException.php
  src/Sulu/Component/Rest/Exception/SearchFieldNotFoundException.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Exception/InsufficientExpressionsException.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Exception/InvalidExpressionArgumentException.php
  src/Sulu/Component/Rest/ListBuilder/Filter/FilterTypeNotFoundException.php
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Manager/WebspaceManagerInterface.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/PortalInformationTest.php
  src/Sulu/Component/Webspace/Webspace.php
Labels: DX

#7070 Add a seralization group to reduce the config when serializing
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/PageBundle/Resources/js/views/PageList/PageList.js
Labels: Feature, Performance

#7104 Remove sulu-link tags completely if they are invalid
  src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/LinkTagTest.php
Labels: Feature

#6973 Add "AsCommand" annotation for deprecated "$defaultName" for all commands
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
  src/Sulu/Bundle/AdminBundle/Command/DownloadLanguageCommand.php
  src/Sulu/Bundle/AdminBundle/Command/InfoCommand.php
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
  src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
  src/Sulu/Bundle/CoreBundle/CommandOptional/SuluBuildCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
  src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
  src/Sulu/Bundle/MediaBundle/Command/InitCommand.php
  src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
  src/Sulu/Bundle/PageBundle/Command/CleanupHistoryCommand.php
  src/Sulu/Bundle/PageBundle/Command/ContentLocaleCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/ContentTypesDumpCommand.php
  src/Sulu/Bundle/PageBundle/Command/MaintainResourceLocatorCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidatePagesCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceExportCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceImportCommand.php
  src/Sulu/Bundle/RouteBundle/Command/MovePageTreeCommand.php
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/SyncPhpcrPermissionsCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetExportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php
  src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
Labels: DX

#7105 Fix code style
  src/Sulu/Bundle/AdminBundle/Command/DownloadBuildCommand.php
  src/Sulu/Bundle/AdminBundle/Command/DownloadLanguageCommand.php
  src/Sulu/Bundle/AdminBundle/Command/InfoCommand.php
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
  src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
  src/Sulu/Bundle/CoreBundle/CommandOptional/SuluBuildCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
  src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
  src/Sulu/Bundle/MediaBundle/Command/InitCommand.php
  src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
  src/Sulu/Bundle/PageBundle/Command/CleanupHistoryCommand.php
  src/Sulu/Bundle/PageBundle/Command/ContentLocaleCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/ContentTypesDumpCommand.php
  src/Sulu/Bundle/PageBundle/Command/MaintainResourceLocatorCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidatePagesCommand.php
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceExportCommand.php
  src/Sulu/Bundle/PageBundle/Command/WebspaceImportCommand.php
  src/Sulu/Bundle/RouteBundle/Command/MovePageTreeCommand.php
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/SyncPhpcrPermissionsCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetExportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php
  src/Sulu/Bundle/WebsiteBundle/Command/DumpSitemapCommand.php
Labels: DX

#7098 Add DetailViewItemAction
  UPGRADE.md
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/ResourceRequester.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/registries/resourceRouteRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/ResourceRequester.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/ResourceRequester/tests/registries/resourceRouteRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/Router.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/registries/resourceViewRegistry.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/tests/registries/resourceViewRegistry.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/services/Router/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/itemActions/DetailLinkItemAction.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/List.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/itemActions/DetailLinkAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/ExportToolbarAction.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/ExportToolbarAction.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/MediaUploadStore.js
  src/Sulu/Bundle/MediaBundle/Resources/js/stores/MediaUploadStore/tests/MediaUploadStore.test.js
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/SuluSnippetExtension.php
  webpack.config.js
Labels: Feature

#7106 Fix clearing destination webspace with nested children in copy webspace command
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Command/WebspaceCopyCommand.php
Labels: Bug

#7107 Fix prophecy error for SuluSecurityListenerTest
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/EventListener/SuluSecurityListenerTest.php
Labels: Bug

#7111 Fix warning optional parameter defined before required
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
Labels: Bug, DX

#7112 Add field transformer for translation
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldTransformers/TranslationFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/index.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldTransformers/TranslationFieldTransformer.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Feature
