Repository sulu/sulu, pull requests merged in 2024-06, with the labels that each got.

#7452 Add support for FosHttpCache 3.0 and FosHttpCacheBundle 3.0
  composer.json
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
Labels: DX

#7453 Fix some more type errors with phpstan
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Rule/TargetGroupEvaluatorTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/EventListener/SegmentCacheListenerTest.php
  src/Sulu/Component/Content/Query/ContentQueryBuilderInterface.php
  src/Sulu/Component/Content/Tests/Unit/Extension/ExtensionManagerTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/DataProviderPoolTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Settings/SettingsManagerTest.php
Labels: DX

#7455 Add better detection for Symfony Security Bundle Version
  phpstan-baseline.neon
  src/Sulu/Bundle/TestBundle/Resources/app/config/config.php
Labels: Bug

#7437 [Webspace] Making `EnvironmentTest` more explicit
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Component/Webspace/Tests/Unit/EnvironmentTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionTest.php
Labels: DX

#7457 [Core] Constructor Property Promotion
  src/Sulu/Bundle/CoreBundle/Build/FixturesBuilder.php
  src/Sulu/Bundle/CoreBundle/Build/PhpcrMigrationsBuilder.php
  src/Sulu/Bundle/CoreBundle/Cache/StructureWarmer.php
  src/Sulu/Bundle/CoreBundle/Controller/LocalizationController.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/ReplacersCompilerPass.php
  src/Sulu/Bundle/CoreBundle/ExpressionLanguage/ContainerExpressionLanguageProvider.php
Labels: DX

#7435 Use constructor property promotion for ContactBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Admin/ContactAdmin.php
  src/Sulu/Bundle/ContactBundle/Command/AccountRecoverCommand.php
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Contact/AccountFactory.php
  src/Sulu/Bundle/ContactBundle/Contact/AccountManager.php
  src/Sulu/Bundle/ContactBundle/Contact/ContactManager.php
  src/Sulu/Bundle/ContactBundle/Content/Types/AccountSelection.php
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactAccountSelection.php
  src/Sulu/Bundle/ContactBundle/Content/Types/ContactSelection.php
  src/Sulu/Bundle/ContactBundle/Content/Types/SingleAccountSelection.php
  src/Sulu/Bundle/ContactBundle/Content/Types/SingleContactSelection.php
  src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactTitleController.php
  src/Sulu/Bundle/ContactBundle/Controller/PositionController.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountContactAddedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountContactRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountCreatedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountMediaAddedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountMediaRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountModifiedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/AccountRestoredEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactCreatedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactMediaAddedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactMediaRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactModifiedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactPositionCreatedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactPositionModifiedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactPositionRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactRestoredEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactTitleCreatedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactTitleModifiedEvent.php
  src/Sulu/Bundle/ContactBundle/Domain/Event/ContactTitleRemovedEvent.php
  src/Sulu/Bundle/ContactBundle/EventListener/CacheInvalidationListener.php
  src/Sulu/Bundle/ContactBundle/Provider/FormOfAddressProvider.php
  src/Sulu/Bundle/ContactBundle/Trash/AccountTrashItemHandler.php
  src/Sulu/Bundle/ContactBundle/Trash/ContactTrashItemHandler.php
  src/Sulu/Bundle/ContactBundle/Twig/ContactTwigExtension.php
Labels: DX

#7463 Fix unexpected single sign on definitions from SecurityBundle services.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
Labels: Bug

#7461 Fix reference command for unpublished articles
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php
  src/Sulu/Bundle/PageBundle/Document/BasePageDocument.php
  src/Sulu/Bundle/PageBundle/Reference/Refresh/PageReferenceRefresher.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Provider/PageReferenceProviderTest.php
  src/Sulu/Bundle/SnippetBundle/Document/SnippetDocument.php
  src/Sulu/Bundle/SnippetBundle/Trash/SnippetTrashItemHandler.php
  src/Sulu/Component/Content/Document/Behavior/StructureBehavior.php
  src/Sulu/Component/Content/Document/Subscriber/ExtensionSubscriber.php
  src/Sulu/Component/Content/Export/WebspaceExport.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Snippet/Import/SnippetImport.php
Labels: Bug

#7459 Reindex moved documents so that the URL is updated
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Search/EventSubscriber/StructureSubscriber.php
Labels: Bug

#7462 Add Constructor Property promotion to DocumentManagerBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php
  src/Sulu/Bundle/DocumentManagerBundle/Bridge/Serializer/Subscriber/ChildrenSubscriber.php
  src/Sulu/Bundle/DocumentManagerBundle/Bridge/Serializer/Subscriber/DocumentSubscriber.php
  src/Sulu/Bundle/DocumentManagerBundle/Collector/DocumentDomainEventCollectorSubscriber.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/FixturesLoadCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/InitializeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/SubscriberDebugCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/DataFixtures/DocumentExecutor.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Compiler/RegisterListenersPass.php
  src/Sulu/Bundle/DocumentManagerBundle/Document/Subscriber/SecuritySubscriber.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/Initializer.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/RootPathPurgeInitializer.php
  src/Sulu/Bundle/DocumentManagerBundle/Initializer/WorkspaceInitializer.php
  src/Sulu/Bundle/DocumentManagerBundle/Routing/Loader/VersionRouteLoader.php
  src/Sulu/Bundle/DocumentManagerBundle/Session/Session.php
  src/Sulu/Bundle/DocumentManagerBundle/Session/SessionManager.php
  src/Sulu/Bundle/SecurityBundle/Serializer/Subscriber/SecuritySubscriber.php
Labels: DX

#7432 Remove SymfonyTestsListener configuration
  phpunit.xml.dist
  src/Sulu/Bundle/ActivityBundle/phpunit.xml.dist
  src/Sulu/Bundle/AdminBundle/phpunit.xml.dist
  src/Sulu/Bundle/AudienceTargetingBundle/phpunit.xml.dist
  src/Sulu/Bundle/CategoryBundle/phpunit.xml.dist
  src/Sulu/Bundle/ContactBundle/phpunit.xml.dist
  src/Sulu/Bundle/CoreBundle/phpunit.xml.dist
  src/Sulu/Bundle/CustomUrlBundle/phpunit.xml.dist
  src/Sulu/Bundle/DocumentManagerBundle/phpunit.xml.dist
  src/Sulu/Bundle/HttpCacheBundle/phpunit.xml.dist
  src/Sulu/Bundle/LocationBundle/phpunit.xml.dist
  src/Sulu/Bundle/MarkupBundle/phpunit.xml.dist
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerWebsiteSecuredTest.php
  src/Sulu/Bundle/MediaBundle/phpunit.xml.dist
  src/Sulu/Bundle/PageBundle/phpunit.xml.dist
  src/Sulu/Bundle/PersistenceBundle/phpunit.xml.dist
  src/Sulu/Bundle/PreviewBundle/phpunit.xml.dist
  src/Sulu/Bundle/RouteBundle/phpunit.xml.dist
  src/Sulu/Bundle/SearchBundle/phpunit.xml.dist
  src/Sulu/Bundle/SecurityBundle/phpunit.xml.dist
  src/Sulu/Bundle/SnippetBundle/phpunit.xml.dist
  src/Sulu/Bundle/TagBundle/phpunit.xml.dist
  src/Sulu/Bundle/TrashBundle/phpunit.xml.dist
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/EventListener/SecurityListenerTest.php
  src/Sulu/Bundle/WebsiteBundle/phpunit.xml.dist
Labels: DX

#7464 Add Constructor Property promotion to HttpCacheBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/HttpCacheBundle/Cache/CacheManager.php
  src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeEnhancer.php
  src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeRequestStore.php
  src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php
  src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/TagsSubscriber.php
Labels: DX

#7465 Add Constructor property promotion to LocationBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/LocationBundle/Controller/GeolocatorController.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/GoogleGeolocator.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/NominatimGeolocator.php
Labels: DX

#7466 Add constructor property promotion in MarkupBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/MarkupBundle/Listener/MailerListener.php
  src/Sulu/Bundle/MarkupBundle/Listener/MarkupListener.php
  src/Sulu/Bundle/MarkupBundle/Listener/SwiftMailerListener.php
  src/Sulu/Bundle/MarkupBundle/Markup/DelegatingTagExtractor.php
  src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php
  src/Sulu/Bundle/MarkupBundle/Markup/HtmlTagExtractor.php
  src/Sulu/Bundle/MarkupBundle/Markup/LinkTag.php
  src/Sulu/Bundle/MarkupBundle/Markup/TagMatchGroup.php
  src/Sulu/Bundle/MarkupBundle/Tag/TagRegistry.php
Labels: DX

#7468 Add constructor property promotion in MediaBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Admin/MediaAdmin.php
  src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
  src/Sulu/Bundle/MediaBundle/Command/ClearCacheCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheCleanupCommand.php
  src/Sulu/Bundle/MediaBundle/Command/FormatCacheRegenerateCommand.php
  src/Sulu/Bundle/MediaBundle/Command/InitCommand.php
  src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
  src/Sulu/Bundle/MediaBundle/Content/Types/CollectionSelection.php
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
  src/Sulu/Bundle/MediaBundle/Content/Types/SingleCollectionSelection.php
  src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/FormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaRedirectController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionCreatedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionModifiedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionMovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionRemovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionRestoredEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/CollectionTranslationAddedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaCreatedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaCropModifiedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaCropRemovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaModifiedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaMovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaPreviewImageModifiedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaPreviewImageRemovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaRemovedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaRestoredEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaTranslationAddedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaVersionAddedEvent.php
  src/Sulu/Bundle/MediaBundle/Domain/Event/MediaVersionRemovedEvent.php
  src/Sulu/Bundle/MediaBundle/EventListener/CacheInvalidationListener.php
  src/Sulu/Bundle/MediaBundle/Markup/Link/MediaLinkProvider.php
  src/Sulu/Bundle/MediaBundle/Media/DispositionType/DispositionTypeResolver.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/CacheNotFoundException.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
Labels: DX

#7472 Add Global blocks definitions for the FormMetadata
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
  src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php
Labels: Feature

#7475 Add Rector with PHPUnit DataProviders update
  .github/workflows/test-application.yaml
  composer.json
  rector.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
Labels: DX

#7474 Add constructor property promotion to MediaBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Entity/MediaDataProviderRepository.php
  src/Sulu/Bundle/MediaBundle/Media/FormatOptions/FormatOptionsManager.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/MediaImageExtractor.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Transformation/PasteTransformation.php
  src/Sulu/Bundle/MediaBundle/Media/ListBuilderFactory/MediaListBuilderFactory.php
  src/Sulu/Bundle/MediaBundle/Media/ListRepresentationFactory/MediaListRepresentationFactory.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Media/PropertiesProvider/ImagePropertiesProvider.php
  src/Sulu/Bundle/MediaBundle/Media/PropertiesProvider/VideoPropertiesProvider.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/AzureBlobStorage.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php
  src/Sulu/Bundle/MediaBundle/Media/TypeManager/TypeManager.php
  src/Sulu/Bundle/MediaBundle/Search/EventListener/PermissionListener.php
  src/Sulu/Bundle/MediaBundle/Search/Subscriber/MediaSearchSubscriber.php
  src/Sulu/Bundle/MediaBundle/Search/Subscriber/StructureMediaSearchSubscriber.php
  src/Sulu/Bundle/MediaBundle/Serializer/Subscriber/MediaPermissionsSubscriber.php
  src/Sulu/Bundle/MediaBundle/Trash/CollectionTrashItemHandler.php
  src/Sulu/Bundle/MediaBundle/Trash/MediaTrashItemHandler.php
  src/Sulu/Bundle/MediaBundle/Twig/MediaTwigExtension.php
Labels: DX

#7478 Avoid __toString() return null error on Doctrine Exceptions
  src/Sulu/Bundle/SecurityBundle/Entity/Permission.php
  src/Sulu/Bundle/TagBundle/Entity/Tag.php
Labels: Bug

#7477 Fix PHPUnit data providers
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/MapquestGeolocatorTest.php
  src/Sulu/Bundle/MediaBundle/Command/MediaTypeUpdateCommand.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaDataProviderRepositoryTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/ImagineImageConverterTest.php
  src/Sulu/Bundle/ReferenceBundle/Tests/Functional/Infrastructure/Doctrine/Repository/ReferenceRepositoryTest.php
  src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
Labels: DX

#7481 Increase locale length
  UPGRADE.md
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Category.orm.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryMeta.orm.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/Keyword.orm.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/CollectionMeta.orm.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionContentLanguage.orm.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionMeta.orm.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersionPublishLanguage.orm.xml
  src/Sulu/Bundle/ReferenceBundle/Resources/config/doctrine/Reference.orm.xml
  src/Sulu/Bundle/RouteBundle/Resources/config/doctrine/Route.orm.xml
Labels: Bug

#7456 Fix empty phone/email/url/fax error on contact and accounts
  src/Sulu/Bundle/ContactBundle/Contact/AbstractContactManager.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
Labels: Bug

#7488 Add constructor property promotion to the PreviewBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php
  src/Sulu/Bundle/PreviewBundle/Application/Manager/PreviewLinkManager.php
  src/Sulu/Bundle/PreviewBundle/Domain/Event/PreviewLinkGeneratedEvent.php
  src/Sulu/Bundle/PreviewBundle/Domain/Event/PreviewLinkRevokedEvent.php
  src/Sulu/Bundle/PreviewBundle/Domain/Model/PreviewLink.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Doctrine/Repository/PreviewLinkRepository.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/EventSubscriber/CacheCommandSubscriber.php
  src/Sulu/Bundle/PreviewBundle/Preview/Events/PreRenderEvent.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/PreviewRendererException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/ProviderNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/RouteDefaultsProviderNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Exception/TokenNotFoundException.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderRegistry.php
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewCache.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewCacheItem.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewLinkController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PublicPreviewController.php
Labels: DX

#7484 Fix media version file not found error
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
Labels: Bug

#7489 Fix deprecation message of PHPUnit 9
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/CollaborationControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/PropertyMetadataMinMaxValueResolverTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/CategoryBundle/Tests/Functional/Controller/CategoryControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountMediaControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactMediaControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaFormatControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/AdminControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/AdminControllerTest.php
Labels: DX

#7490 Add constructor property promotion in RouteBundle classes
  phpstan-baseline.neon
  src/Sulu/Bundle/RouteBundle/Command/MovePageTreeCommand.php
  src/Sulu/Bundle/RouteBundle/Command/UpdateRouteCommand.php
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
  src/Sulu/Bundle/RouteBundle/Document/Subscriber/PageTreeRouteSubscriber.php
  src/Sulu/Bundle/RouteBundle/Document/Subscriber/RoutableSubscriber.php
  src/Sulu/Bundle/RouteBundle/Domain/Event/RouteRemovedEvent.php
  src/Sulu/Bundle/RouteBundle/Exception/MissingClassMappingConfigurationException.php
  src/Sulu/Bundle/RouteBundle/Exception/RouteIsNotUniqueException.php
  src/Sulu/Bundle/RouteBundle/Generator/CannotEvaluateTokenException.php
  src/Sulu/Bundle/RouteBundle/Generator/ChainRouteGenerator.php
  src/Sulu/Bundle/RouteBundle/Generator/RouteGenerator.php
  src/Sulu/Bundle/RouteBundle/Generator/TranslatorWrapper.php
  src/Sulu/Bundle/RouteBundle/Manager/AutoIncrementConflictResolver.php
  src/Sulu/Bundle/RouteBundle/Manager/RouteManager.php
  src/Sulu/Bundle/RouteBundle/Manager/RouteNotCreatedException.php
  src/Sulu/Bundle/RouteBundle/PageTree/PageTreeRepository.php
  src/Sulu/Bundle/RouteBundle/Routing/Defaults/RouteDefaultsProvider.php
  src/Sulu/Bundle/RouteBundle/Routing/RouteProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/ChainRouteGeneratorTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Manager/RouteManagerTest.php
Labels: DX

#7487 Remove hardcoded order bys in metadata
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryTranslation.php
  src/Sulu/Bundle/CategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Account.orm.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/doctrine/Contact.orm.xml
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/ContactControllerTest.php
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/Collection.orm.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/doctrine/FileVersion.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/doctrine/Analytics.orm.xml
Labels: Performance

#7493 Add support for guzzle promises 2.0
  composer.json
Labels: DX

#7156 Allow Symfony 7 versions of packages
  composer.json
  config/packages/security.yaml
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/AppCache.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/DataFixtures/fixtures/ContainerFixture.php
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/config_secured.yml
  src/Sulu/Bundle/ReferenceBundle/UserInterface/Command/RefreshCommand.php
  src/Sulu/Bundle/RouteBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/TestBundle/Resources/app/config/security-5-4.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/AppCache.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/config_with_security-5-4.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/config_with_security.yml
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
Labels: Feature, DX
