Repository sulu/sulu, pull requests merged in 2024-01, with the labels that each got.

#7249 Adapt indexing of blocks to remove hidden or scheduled blocks
  UPGRADE.md
  composer.json
  src/Sulu/Bundle/PageBundle/Search/Metadata/StructureProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Search/SaveDocumentTest.php
Labels: Bug

#7244 Add routeAttributes to preview conditions
  src/Sulu/Bundle/AdminBundle/Resources/js/views/PreviewForm/PreviewForm.js
Labels: DX

#7248 Fix php-cs issues and update phpstan baseline
  .php-cs-fixer.dist.php
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRepository.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
  src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManager.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Search/SaveDocumentTest.php
  src/Sulu/Bundle/RouteBundle/Entity/RouteRepository.php
  src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
  src/Sulu/Bundle/SecurityBundle/Entity/AccessControlRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/UserRepository.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Admin/SnippetAdminTest.php
  src/Sulu/Bundle/TagBundle/Tag/TagManager.php
  src/Sulu/Component/Content/Compat/Serializer/PageBridgeHandler.php
  src/Sulu/Component/Content/Tests/Unit/Compat/Serializer/PageBridgeHandlerTest.php
  src/Sulu/Component/Rest/ListBuilder/Event/ListBuilderCreateEvent.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineWhereExpression.php
  src/Sulu/Component/Security/Authentication/RoleRepositoryInterface.php
  src/Sulu/Component/Security/Authentication/UserRepositoryInterface.php
  src/Sulu/Component/Webspace/Loader/XmlFileLoader10.php
  src/Sulu/Component/Webspace/Portal.php
Labels: DX

#7253 Fix conflict to old and newer scheb packages
  composer.json
Labels: Bug

#7234 Fix LinkType warning when provider is not defined
  src/Sulu/Component/Content/Types/Link.php
Labels: Bug

#7238 Add lastModified field to page settings
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/behaviors.xml
  src/Sulu/Bundle/PageBundle/Document/BasePageDocument.php
  src/Sulu/Bundle/PageBundle/Form/Type/BasePageDocumentType.php
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
  src/Sulu/Bundle/PageBundle/Resources/config/serializer/Document.BasePageDocument.xml
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.de.json
  src/Sulu/Bundle/PageBundle/Resources/translations/admin.en.json
  src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/StructureResolverTest.php
  src/Sulu/Component/Content/Compat/DataNormalizer.php
  src/Sulu/Component/Content/Document/Behavior/LastModifiedBehavior.php
  src/Sulu/Component/Content/Document/Behavior/LocalizedLastModifiedBehavior.php
  src/Sulu/Component/Content/Document/Subscriber/LastModifiedSubscriber.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
Labels: Feature

#7255 Allow doctrine orm 2.17.3
  composer.json
Labels: DX
