Repository sulu/sulu, pull requests merged in 2024-02, with the labels that each got.

#7260 Fix current phpstan and phpcs issues
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Admin/View/ListViewBuilderInterface.php
  src/Sulu/Bundle/AdminBundle/Entity/CollaborationRepository.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
Labels: DX

#7233 Fix deprecations on bundle classes methods and mark them as `@internal`
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
  src/Sulu/Bundle/AudienceTargetingBundle/SuluAudienceTargetingBundle.php
  src/Sulu/Bundle/CategoryBundle/SuluCategoryBundle.php
  src/Sulu/Bundle/ContactBundle/SuluContactBundle.php
  src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php
  src/Sulu/Bundle/CustomUrlBundle/SuluCustomUrlBundle.php
  src/Sulu/Bundle/DocumentManagerBundle/SuluDocumentManagerBundle.php
  src/Sulu/Bundle/MarkupBundle/SuluMarkupBundle.php
  src/Sulu/Bundle/MediaBundle/SuluMediaBundle.php
  src/Sulu/Bundle/PageBundle/SuluPageBundle.php
  src/Sulu/Bundle/PersistenceBundle/SuluPersistenceBundle.php
  src/Sulu/Bundle/PreviewBundle/SuluPreviewBundle.php
  src/Sulu/Bundle/RouteBundle/SuluRouteBundle.php
  src/Sulu/Bundle/SecurityBundle/SuluSecurityBundle.php
  src/Sulu/Bundle/SnippetBundle/SuluSnippetBundle.php
  src/Sulu/Bundle/TagBundle/SuluTagBundle.php
  src/Sulu/Bundle/TestBundle/SuluTestBundle.php
  src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
Labels: DX

#7247 Fix DebugEventDispatcher - Fix method naming and add a check if an event should be stoppable
  phpstan-baseline.neon
  src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
  src/Sulu/Component/DocumentManager/Tests/Unit/EventDispatcher/DebugEventDispatcherTest.php
Labels: Bug

#7259 Optimize loading of media for download media action
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepositoryInterface.php
Labels: Performance

#7235 Replace `merge` with `persist` in `TargetGroupRepository` and `TargetGroupRuleRepository`
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Controller/TargetGroupController.php
  src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRepository.php
  src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRuleRepository.php
  src/Sulu/Bundle/AudienceTargetingBundle/Entity/TargetGroupRuleRepositoryInterface.php
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/lists/target_groups.xml
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Functional/CachingTest.php
Labels: DX

#7263 Fix Article restore bug with pageTreeRoute if parent page is null by adding a fallback
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Content/PageTreeRouteContentTypeTest.php
Labels: Bug

#6643 Allow doctrine/persistence 3.0 and doctrine/collections 2.0
  composer.json
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/Entity/Analytics.php
Labels: DX

#7264 Fix suggestions test case and code style
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/Suggestion.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/__snapshots__/AutoCompletePopover.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/components/AutoCompletePopover/tests/__snapshots__/Suggestion.test.js.snap
Labels: Bug

#7268 Add focus for search fields
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/Search.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/__snapshots__/Search.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/SearchField.js
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/tests/__snapshots__/SearchField.test.js.snap
Labels: Bug

#7275 Fix compatibility to php 7.2
  composer.json
  src/Sulu/Bundle/RouteBundle/Generator/SymfonyExpressionTokenProvider.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Controller/RouteControllerTest.php
  src/Sulu/Component/DocumentManager/EventDispatcher/CallListenersTrait.php
  src/Sulu/Component/DocumentManager/EventDispatcher/DebugEventDispatcher.php
Labels: Bug

#7273 Fix Postgres DoctrineDbal tests and Refactor CI tasks
  .editorconfig
  .github/workflows/test-application.yaml
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/ContentRepositoryTest.php
  src/Sulu/Component/Content/Export/WebspaceExport.php
  tests/docker/docker-compose.jackrabbit.yml
  tests/docker/docker-compose.mysql-57.yml
  tests/docker/docker-compose.mysql-80.yml
  tests/docker/docker-compose.postgres-14.yml
Labels: Bug, DX

#7277 Add missing prophecy trait to CategoryAdminTest
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Admin/CategoryAdminTest.php
Labels: DX

#7278 Fix flaky postgres snippet export test
  src/Sulu/Component/Snippet/Export/SnippetExport.php
Labels: Bug

#7172 Fix nominatim location
  src/Sulu/Bundle/LocationBundle/DependencyInjection/Configuration.php
Labels: Bug, hacktoberfest-accepted

#7177 Add cache invalidation for snippet areas
  phpstan-baseline.neon
  src/Sulu/Bundle/SnippetBundle/Content/SingleSnippetSelection.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php
  src/Sulu/Bundle/SnippetBundle/EventListener/CacheInvalidationSubscriber.php
  src/Sulu/Bundle/SnippetBundle/Resources/config/content.xml
  src/Sulu/Bundle/SnippetBundle/Resources/config/snippet.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SingleSnippetSelectionTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetContentTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/DependencyInjection/Compiler/SnippetAreaCompilerPassTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/EventListener/CacheInvalidationSubscriberTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Twig/SnippetAreaTwigExtensionTest.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetAreaTwigExtension.php
  src/Sulu/Component/Content/Metadata/Loader/AbstractLoader.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
Labels: Feature

#7281 Location support for mapquestapi
  src/Sulu/Bundle/LocationBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/LocationBundle/DependencyInjection/SuluLocationExtension.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/MapquestGeolocator.php
  src/Sulu/Bundle/LocationBundle/Resources/config/geolocator.xml
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/MapquestGeolocatorTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/mapquest-responses/56aa868fba3d9d372349222530358157.json
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/responses/56aa868fba3d9d372349222530358157.json
Labels: Feature

#7229 Add global block types
  config/templates/blocks/text_block.xml
  config/templates/pages/example.xml
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/IfThenElseMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/RefSchemaMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/SchemaMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/metadataStore.js
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/RefSchemaMetadataTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/SchemaMetadataTest.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/ImageMapContentTypeTest.php
  src/Sulu/Bundle/PageBundle/Resources/config/compat.xml
  src/Sulu/Component/Content/Compat/Structure/LegacyPropertyFactory.php
  src/Sulu/Component/Content/Metadata/ItemMetadata.php
  src/Sulu/Component/Content/Metadata/Loader/schema/properties-1.0.xsd
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/Content/Metadata/PropertyMetadata.php
  src/Sulu/Component/Content/Tests/Unit/Compat/Structure/LegacyPropertyFactoryTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/ItemMetadataCase.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/StructureMetdataTest.php
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
  src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php
  src/Sulu/Component/Export/Export.php
  tests/Resources/DataFixtures/Page/template_with_global_blocks.xml
  tests/Resources/DataFixtures/Page/template_with_global_blocks_invalid_no_ref_or_name.xml
  tests/Resources/DataFixtures/Page/template_with_global_blocks_invalid_ref_and_name.xml
Labels: Feature
