Repository sulu/sulu, pull requests merged in 2024-04, with the labels that each got.

#7340 Add refresh command for website context to UPGRADE file
  UPGRADE.md
Labels: DX

#7341 Add test case for page and snippet reference refresher
  src/Sulu/Bundle/PageBundle/Reference/Refresh/PageReferenceRefresher.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Reference/Refresh/PageReferenceRefresherTest.php
  src/Sulu/Bundle/SnippetBundle/Reference/Refresh/SnippetReferenceRefresher.php
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/templates/snippets/car.xml
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Reference/Refresh/SnippetReferenceRefresherTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Twig/SnippetTwigExtensionTest.php
Labels: Bug

#6834 Add support for jackalope 2.0 and doctrine phpcr bundle 3.0
  .github/workflows/test-application.yaml
  UPGRADE.md
  composer.json
  config/packages/sulu_document_manager.yaml
  phpstan-baseline.neon
  src/Sulu/Bundle/CustomUrlBundle/Resources/phpcr-migrations/Version201904110902.php
  src/Sulu/Bundle/PageBundle/Command/WorkspaceImportCommand.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201504271608.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201504281842.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201507231648.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201507281529.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201510210733.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201511171538.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201511240843.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201511240844.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201607181533.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201702021447.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201903271333.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version201905071542.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202005191116.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202005250917.php
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202105311447.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Export/WebspaceExportTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Mapper/ContentMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/QueryBuilderTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Command/CleanupHistoryCommandTest.php
  src/Sulu/Component/Content/Repository/Content.php
  src/Sulu/Component/Content/Repository/ContentRepository.php
  src/Sulu/Component/Content/Tests/Unit/Repository/ContentRepositoryTest.php
  src/Sulu/Component/CustomUrl/Document/Subscriber/InvalidationSubscriber.php
  src/Sulu/Component/CustomUrl/Repository/CustomUrlRepository.php
  src/Sulu/Component/DocumentManager/Tests/Unit/NodeHelperTest.php
  src/Sulu/Component/DocumentManager/Tests/Unit/Subscriber/Behavior/VersionSubscriberTest.php
  src/Sulu/Component/Util/SuluNodeHelper.php
  src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
Labels: Feature, DX

#7353 Add missing return type and container check for PHPCR Migration
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202404051600.php
Labels: DX

#7347 Prepare compatibility to Symfony 7
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/ActivityBundle/Application/Subscriber/SetDomainEventUserSubscriber.php
  src/Sulu/Bundle/ActivityBundle/Tests/Unit/Application/Subscriber/SetDomainEventUserSubscriberTest.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/XmlFormMetadataLoader.php
  src/Sulu/Bundle/CoreBundle/Cache/StructureWarmer.php
  src/Sulu/Bundle/CoreBundle/DataFixtures/ReplacerXmlLoader.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Compiler/RegisterListenersPass.php
  src/Sulu/Bundle/MediaBundle/Media/FormatLoader/BaseXmlFormatLoader.php
  src/Sulu/Bundle/MediaBundle/Media/FormatLoader/XmlFormatLoader10.php
  src/Sulu/Bundle/PageBundle/EventListener/PageRemoveSubscriber.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/ReferenceBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/ReferenceBundle/UserInterface/Command/RefreshCommand.php
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
  src/Sulu/Bundle/SecurityBundle/Metadata/TwoFactorFormMetadataVisitor.php
  src/Sulu/Bundle/SecurityBundle/Security/AuthenticationEntryPoint.php
  src/Sulu/Bundle/SecurityBundle/Security/AuthenticationHandler.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationHandlerTest.php
  src/Sulu/Bundle/SecurityBundle/User/UserProvider.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Bundle/TestBundle/Testing/TestUserProvider.php
  src/Sulu/Bundle/TestBundle/Testing/TestVoter.php
  src/Sulu/Bundle/TrashBundle/Infrastructure/Doctrine/Repository/TrashItemRepository.php
  src/Sulu/Bundle/WebsiteBundle/Routing/PortalLoader.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/AppCache.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Metadata/Loader/AbstractLoader.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/Orm/BaseDataProviderTest.php
  src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
  src/Sulu/Component/PHPCR/PathCleanup.php
  src/Sulu/Component/PHPCR/Tests/Unit/PathCleanupTest.php
  src/Sulu/Component/Rest/ContextAwareNormalizerInterface.php
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/Security/Authorization/SecurityContextVoter.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/AccessControlManagerTest.php
  src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
  src/Sulu/Component/Webspace/Loader/BaseXmlFileLoader.php
  src/Sulu/Component/Webspace/Loader/XmlFileLoader10.php
Labels: Feature

#7356 Fix prepend website cache class with preview
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPass.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Infrastructure/Symfony/DependencyInjection/Compiler/RegisterPreviewWebspaceClassPassTest.php
Labels: Bug

#7359 Add Symfony 7 compatibility to VersionRouteLoader and ContainerExpressionLanguageProvider
  UPGRADE.md
  src/Sulu/Bundle/CoreBundle/ExpressionLanguage/ContainerExpressionLanguageProvider.php
  src/Sulu/Bundle/DocumentManagerBundle/Routing/Loader/VersionRouteLoader.php
Labels: DX

#7357 Remove requirements to Symfony\Component\DependencyInjection\ContainerAwareTrait
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Component/Content/Compat/StructureManager.php
  src/Sulu/Component/Content/Compat/StructureManagerInterface.php
Labels: DX

#7342 Tests should crash on non zero exit code
  bin/runtests
Labels: Bug

#7361 Update phpstan baseline to remove latest not longer ignored errors
  phpstan-baseline.neon
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Component/Rest/ListBuilder/Filter/FilterTypeRegistry.php
Labels: DX

#7362 Fix shadow migration with multiple locales
  UPGRADE.md
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202404051600.php
Labels: Bug

#7352 Preview update on extensions (Seo / Excerpt) changes
  src/Sulu/Bundle/PageBundle/Preview/PageObjectProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Preview/PageObjectProviderTest.php
Labels: Bug

#7368 Add Symfony 7 compatibility to FieldDescriptorFactory
  phpstan-baseline.neon
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
Labels: DX

#7366 Fix TextEditor in 2.6 Edit and Remove of Links do not work and buttons jumps
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/ExternalLinkPlugin/ExternalLinkPlugin.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/InternalLinkPlugin.js
Labels: Bug

#7343 Fix copy shadow properties
  src/Sulu/Bundle/PageBundle/Resources/config/forms/page_settings.xml
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202404051700.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
  src/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
Labels: Bug

#7367 Add language package for ckeditor
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
Labels: Feature, Design required

#7369 Fix PreviewKernel and RefreshCommand compatibility
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupCommand.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/ReferenceBundle/UserInterface/Command/RefreshCommand.php
Labels: DX

#7371 Add compatibility to Symfony 7 to ActivateResolveTargetEntityResolverPass
  src/Sulu/Bundle/PersistenceBundle/DependencyInjection/Compiler/ActivateResolveTargetEntityResolverPass.php
Labels: DX

#7374 Refactor doctrine.event_subscriber to doctrine.event_listener for Symfony 7 compatibility
  UPGRADE.md
  src/Sulu/Bundle/ActivityBundle/Infrastructure/Doctrine/Subscriber/DomainEventCollectorSubscriber.php
  src/Sulu/Bundle/ActivityBundle/Resources/config/services.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/doctrine.xml
  src/Sulu/Bundle/MediaBundle/EventListener/MediaAudienceTargetingSubscriber.php
  src/Sulu/Bundle/MediaBundle/Resources/config/audience_targeting.xml
  src/Sulu/Bundle/PersistenceBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/EventListener/ForceTwoFactorSubscriber.php
  src/Sulu/Bundle/SecurityBundle/EventListener/PermissionInheritanceSubscriber.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/2fa_force.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Component/Doctrine/ReferencesOption.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/MetadataSubscriber.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/TimestampableSubscriber.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
Labels: DX

#7375 Refactor SuluBuilder to be compatible with MassiveBuild ContainerAwareInterface for Symfony 7
  composer.json
  src/Sulu/Bundle/CoreBundle/Build/SuluBuilder.php
Labels: DX

#7379 Fix condition provider crashing of the admin when no parent is found
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/conditionDataProviders/parentConditionDataProvider.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/conditionDataProviders/parentConditionDataProvider.test.js
Labels: Bug

#7382 Refactor ParameterBag in InputBag in Core Tests
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Twig/CategoryTwigExtensionTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Twig/TagTwigExtensionTest.php
  src/Sulu/Component/Category/Tests/Unit/Request/CategoryRequestHandlerTest.php
  src/Sulu/Component/Tag/Tests/Unit/Request/TagRequestHandlerTest.php
  src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
Labels: DX

#6395 Fix preserving scroll-position in preview
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/tests/Preview.test.js
Labels: Bug, UX

#7220 Add more types to media controllers
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Collection/Manager/CollectionManagerInterface.php
  src/Sulu/Bundle/MediaBundle/Controller/AbstractMediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/FormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaFormatController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaPreviewController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManager.php
  src/Sulu/Bundle/MediaBundle/Media/Manager/MediaManagerInterface.php
  src/Sulu/Component/Rest/RestControllerTrait.php
Labels: DX

#7228 Add pagination to admin search
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/Pagination.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/pagination.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Pagination/tests/__snapshots__/Pagination.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/FolderAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/adapters/__snapshots__/TableAdapter.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/__snapshots__/List.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/views/MediaOverview/tests/__snapshots__/MediaOverview.test.js.snap
  src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/Search.js
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/searchResult.scss
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/stores/searchStore.js
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/tests/Search.test.js
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/tests/__snapshots__/Search.test.js.snap
  src/Sulu/Bundle/SearchBundle/Resources/js/containers/Search/tests/stores/SearchStore.test.js
  src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/SearchControllerTest.php
Labels: Feature

#7377 Fixes ReactCircularProgressbar props
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CircularProgressbar/CircularProgressbar.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/CircularProgressbar/tests/__snapshots__/CircularProgressbar.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
Labels: Bug
