Repository sulu/sulu, pull requests merged in 2024-05, with the labels that each got.

#7231 Add anchor-field to MediaLinkTypeOverlay
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Link/overlays/MediaLinkTypeOverlay.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Link/tests/overlays/MediaLinkTypeOverlay.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/Link/tests/overlays/__snapshots__/MediaLinkTypeOverlay.test.js.snap
Labels: Feature

#7386 Rename SSO user role setting to default role key
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapterFactory.php
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/SingleSignOnAdapterFactory.php
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/SingleSignOnAdapterFactoryInterface.php
Labels: DX

#7378 Fix webspace view if no permissions for first webspace
  src/Sulu/Bundle/PageBundle/Admin/PageAdmin.php
Labels: Bug

#7387 Add hint about changes in Kernel registerContainerConfiguration
  UPGRADE.md
Labels: DX

#7204 Add sorting for snippet area / default snippets by title instead of key
  phpstan-baseline.neon
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Component/Util/SortUtils.php
  src/Sulu/Component/Util/Tests/Unit/SortUtilsTest.php
Labels: UX

#6982 Add support for Accept Language in Geolocators
  UPGRADE.md
  src/Sulu/Bundle/LocationBundle/Controller/GeolocatorController.php
  src/Sulu/Bundle/LocationBundle/Geolocator/GeolocatorInterface.php
  src/Sulu/Bundle/LocationBundle/Geolocator/GeolocatorOptions.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/GoogleGeolocator.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/MapquestGeolocator.php
  src/Sulu/Bundle/LocationBundle/Geolocator/Service/NominatimGeolocator.php
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Form/fields/Location.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/Location.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/LocationOverlay.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/Location.test.js
  src/Sulu/Bundle/LocationBundle/Resources/js/containers/Location/tests/LocationOverlay.test.js
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Controller/GeolocatorControllerTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/GoogleGeolocatorTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/MapquestGeolocatorTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/Service/NominatimGeolocatorTest.php
Labels: Feature

#7125 Add support of noop proxy client in sulu http cache
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
Labels: Feature, DX

#7188 Add support for translation keys in snippet areas meta
  phpstan-baseline.neon
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/Compiler/SnippetAreaCompilerPass.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/DependencyInjection/Compiler/SnippetAreaCompilerPassTest.php
Labels: Bug

#7390 Refactor ParameterBag to HeaderBag in Core Tests
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Controller/RedirectControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/EventListener/AppendAnalyticsListenerTest.php
Labels: DX

#7391 Refactor AdminBundle Exception and Metadata to use constructor property promotion
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Exception/InvalidRootTagException.php
  src/Sulu/Bundle/AdminBundle/Exception/MetadataNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/MetadataProviderNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/NavigationItemNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/ParentViewNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/PropertyMetadataMapperNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/ResourceNotFoundException.php
  src/Sulu/Bundle/AdminBundle/Exception/ViewNotFoundException.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/ExpressionFormMetadataVisitor.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Validation/ChainFieldMetadataValidator.php
Labels: DX

#7393 Fix Typo in SQL for references migration
  UPGRADE.md
Labels: Bug, DX

#7392 Fix some false mocking inside various tests
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Command/FixturesLoadCommandTest.php
  src/Sulu/Bundle/DocumentManagerBundle/Tests/Unit/Routing/Loader/VersionRouteLoaderTest.php
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/MarkupListenerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Security/AuthenticationHandlerTest.php
Labels: Bug, DX

#7398 Constructor Property Promotion Category Bundle (part 1)
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Admin/CategoryAdmin.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
  src/Sulu/Bundle/CategoryBundle/Category/KeywordManager.php
  src/Sulu/Bundle/CategoryBundle/Command/RecoverCommand.php
  src/Sulu/Bundle/CategoryBundle/Content/Types/CategorySelection.php
  src/Sulu/Bundle/CategoryBundle/Content/Types/SingleCategorySelection.php
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/CategoryBundle/Controller/KeywordController.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryCreatedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordAddedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordModifiedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryKeywordRemovedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryModifiedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryMovedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryRemovedEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryRestoredEvent.php
  src/Sulu/Bundle/CategoryBundle/Domain/Event/CategoryTranslationAddedEvent.php
Labels: DX

#7400 Fix correct return self in the CacheManagerTest
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/Cache/CacheManagerTest.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/CacheLifetime/CacheLifetimeEnhancerTest.php
Labels: DX

#7401 Remove unnecessary test that checks if resource is seekable
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/MediaImageExtractorTest.php
Labels: DX

#7408 Fix shadow migration with multiple locales
  src/Sulu/Bundle/PageBundle/Resources/phpcr-migrations/Version202404051700.php
Labels: Bug

#7411 Add section to upgrade about new reserved directory
  UPGRADE.md
Labels: Bug

#7412 Replacing the mocks in phpunit dataproviders with actual objects
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Controller/TargetGroupEvaluationControllerTest.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
  src/Sulu/Component/Contact/Tests/Unit/SmartContent/AccountDataProviderTest.php
  src/Sulu/Component/Contact/Tests/Unit/SmartContent/ContactDataProviderTest.php
  src/Sulu/Component/Content/Tests/Unit/Extension/ExtensionManagerTest.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
Labels: DX

#7420 Update PHPStan baseline
  phpstan-baseline.neon
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
Labels: DX

#7417 Cancel CI tasks after 30 minutes
  .github/workflows/crowdin-upload.yaml
  .github/workflows/test-application.yaml
  .github/workflows/trigger-styleguide-build.yaml
Labels: DX

#7421 Fix domain with dash in single sign on configuration
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
Labels: Bug

#7419 Refactor phpunit dataprovider to be static
  phpstan-baseline.neon
  src/Sulu/Bundle/ActivityBundle/Tests/Functional/UserInterface/Controller/ActivityControllerTest.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/PHPCR/SuluNodeTest.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/AccessControl/DoctrineAccessControlProviderTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/DataProviderPoolTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/EnvironmentTest.php
Labels: DX

#7423 Fix nested global blocks
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/SectionMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/stores/metadataStore.js
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/blocks/text_block.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/blocks/text_block2.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/blocks/text_block3.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/default.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/overview.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
  src/Sulu/Bundle/RouteBundle/Resources/js/index.js
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
  src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php
Labels: Bug

#7425 Use interface for WebspaceManager in PHPCRCleanupCommand
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupCommand.php
Labels: DX

#7427 Upgrade github actions versions
  .github/workflows/test-application.yaml
Labels: DX

#7431 Fix matchMedia compatibility to jest
  tests/js/testSetup.config.js
Labels: Bug

#7442 Use php-cs-fixer shim to avoid conflicts
  .github/workflows/test-application.yaml
  .php-cs-fixer.dist.php
  composer.json
Labels: DX
