Repository sulu/sulu, pull requests merged in 2024-03, with the labels that each got.

#7276 Using the `Localization` constructor
  phpstan-baseline.neon
  src/Sulu/Bundle/SearchBundle/Tests/Unit/Controller/WebsiteSearchControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/RequestAnalyzerResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/ContentRouteProviderTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/PortalLoaderTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/RedirectExceptionSubscriberTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapGeneratorTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/MetaTwigExtensionTest.php
  src/Sulu/Component/CustomUrl/Tests/Functional/Generator/GeneratorTest.php
  src/Sulu/Component/Localization/Localization.php
  src/Sulu/Component/Localization/Provider/LocalizationProvider.php
  src/Sulu/Component/Localization/Tests/Unit/Manager/LocalizationManagerTest.php
  src/Sulu/Component/Webspace/Loader/XmlFileLoader10.php
  src/Sulu/Component/Webspace/Resources/skeleton/WebspaceCollectionClass.php.twig
  src/Sulu/Component/Webspace/Tests/Functional/Analyzer/RequestAnalyzerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/PortalInformationRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/Attributes/WebsiteRequestProcessorTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Document/Initializer/WebspaceInitializerTest.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceCollectionTest.php
  src/Sulu/Component/Webspace/Tests/Unit/WebspaceTest.php
Labels: DX

#7295 Fix new appeared PHPStan issues
  phpstan-baseline.neon
  src/Sulu/Bundle/ActivityBundle/Tests/Functional/Infrastructure/Doctrine/Repository/ActivityRepositoryTest.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/CollectionRepository.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
Labels: DX

#7297 Fix code style in new SystemRequestProcessor
  src/Sulu/Component/Webspace/Analyzer/Attributes/SystemRequestProcessor.php
Labels: Bug

#7298 Fix new Website Test Kernel methods
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/Kernel.php
Labels: Bug

#7306 Upgrade PHP requirement to PHP 8.2
  .github/workflows/test-application.yaml
  UPGRADE.md
  composer.json
  phpstan-baseline.neon
  phpstan.neon
Labels: DX

#7308 Add some more phpdoc to smart content and use PHP 8.3 for linting
  .github/workflows/test-application.yaml
  phpstan-baseline.neon
  phpstan.neon
  src/Sulu/Component/SmartContent/DataProviderInterface.php
  src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryInterface.php
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
Labels: DX

#7291 Add phpcr cleanup command
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupSingleNodeCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Resources/config/command.xml
  src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
  src/Sulu/Bundle/PageBundle/Document/Subscriber/PublishSubscriber.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Content/PageTreeRouteContentTypeTest.php
  src/Sulu/Component/Content/Document/Subscriber/PHPCR/CleanupNode.php
  src/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
Labels: Feature

#7286 Add support for NPM 8, 9, 10 and PNPM 8, remove support for NPM 6
  .github/workflows/test-application.yaml
  .npmrc
  UPGRADE.md
  preinstall.js
  src/Sulu/Bundle/AdminBundle/Command/UpdateBuildCommand.php
Labels: Feature

#7310 Fix shadow-copy subscriber to only copy properties to real shadows
  src/Sulu/Component/Content/Document/Subscriber/ShadowCopyPropertiesSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ShadowCopyPropertiesSubscriberTest.php
Labels: Bug

#7294 S3 storage with cdn url
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/S3Storage.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services_storage_s3.xml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/S3StorageTest.php
Labels: Feature

#7257 Add a logger in the ResettingController
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
Labels: Feature

#7311 Fix routepath on language copy if the parent page only exist in one l…
  src/Sulu/Component/Content/Document/Subscriber/CopyLocaleSubscriber.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/CopyLocaleSubscriberTest.php
Labels: Bug

#7309 Fix page_tree_route suffix
  phpstan-baseline.neon
  src/Sulu/Bundle/RouteBundle/Document/Subscriber/RoutableSubscriber.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php
Labels: Bug

#7316 Fix php-cs-fixer errors
  phpstan-baseline.neon
  public/maintenance.php
  src/Sulu/Bundle/CustomUrlBundle/Admin/CustomUrlAdmin.php
  src/Sulu/Bundle/MediaBundle/Media/FileValidator/FileValidator.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/ImageConverter/Transformations/CropTransformationTest.php
  src/Sulu/Bundle/SecurityBundle/Build/UserBuilder.php
Labels: DX

#7317 Fix php-cs issues
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Compiler/RegisterListenersPass.php
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Markup/LinkTagTest.php
  src/Sulu/Bundle/PageBundle/Command/ValidateWebspacesCommand.php
Labels: DX

#7315 Restart preview always when the locale is changed
  src/Sulu/Bundle/PreviewBundle/Resources/js/containers/Preview/Preview.js
Labels: Bug

#7072 Fix group by statement for sorted queries
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
  src/Sulu/Component/Rest/Tests/Unit/ListBuilder/Doctrine/DoctrineListBuilderTest.php
Labels: Bug

#7321 Allow ^5.0 version of JMS Serializer Bundle
  composer.json
  src/Sulu/Bundle/CoreBundle/DependencyInjection/Compiler/JmsObjectConstructorCompilerPass.php
  src/Sulu/Bundle/CoreBundle/SuluCoreBundle.php
Labels: DX

#7322 Move from dantleech/phpcr-migrations-bundle to the phpcr/phpcr-migration-bundle
  UPGRADE.md
  composer.json
  config/bundles.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
Labels: DX

#7313 Add last modified field value to sitemap when exists
  src/Sulu/Bundle/PageBundle/Sitemap/PagesSitemapProvider.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Sitemap/PagesSitemapProviderTest.php
Labels: Feature

#7326 Upgrade CKEditor to latest version 41.2
  .eslintrc.json
  UPGRADE.md
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  webpack.config.js
Labels: Feature

#7283 Add View Debug Command for SuluAdmin
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Command/ViewDebugCommand.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
Labels: Feature

#7327 Configuration of CKEditor 5 powered by and fix some small UI issues
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/ckeditor5.scss
Labels: Design required

#7328 Upgrade some JS dependencies
  UPGRADE.md
  package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Select/tests/DisplayValue.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toggler/tests/Toggler.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Toolbar/tests/Button.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/js/package.json
  src/Sulu/Bundle/ContactBundle/Resources/js/package.json
  src/Sulu/Bundle/CustomUrlBundle/Resources/js/package.json
  src/Sulu/Bundle/LocationBundle/Resources/js/package.json
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/PageBundle/Resources/js/package.json
  src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
  src/Sulu/Bundle/RouteBundle/Resources/js/package.json
  src/Sulu/Bundle/SearchBundle/Resources/js/package.json
  src/Sulu/Bundle/SecurityBundle/Resources/js/package.json
  src/Sulu/Bundle/SnippetBundle/Resources/js/package.json
  src/Sulu/Bundle/TrashBundle/Resources/js/package.json
  src/Sulu/Bundle/WebsiteBundle/Resources/js/package.json
Labels: DX

#7329 Upgrade css loader package and use webpack assets modules
  README.md
  UPGRADE.md
  package.json
  webpack.config.js
Labels: DX

#7330 Update debounce and react-dropzone js library
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/FileUploadButton.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/tests/__snapshots__/FileUploadButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/package.json
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/__snapshots__/UploadToolbarAction.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/toolbarActions/UploadToolbarAction.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/SingleMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/SingleMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/__snapshots__/MediaVersionUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/MultiMediaDropzone.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/MultiMediaDropzone.test.js
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/__snapshots__/MultiMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/__snapshots__/SingleMediaUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/package.json
  src/Sulu/Bundle/PreviewBundle/Resources/js/package.json
Labels: DX

#7331 Change some sorting in UPGRADE file
  UPGRADE.md
Labels: DX

#7334 Remove unused parameter from ReferenceProvider
  src/Sulu/Bundle/DocumentManagerBundle/Reference/Provider/AbstractDocumentReferenceProvider.php
  src/Sulu/Bundle/PageBundle/Reference/Provider/PageReferenceProvider.php
  src/Sulu/Bundle/SnippetBundle/Reference/Provider/SnippetReferenceProvider.php
Labels: DX

#7324 Replace switch with match where possible
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Rule/DeviceTypeRule.php
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeResolver.php
  src/Sulu/Bundle/MediaBundle/Content/MediaSelectionContainer.php
  src/Sulu/Bundle/MediaBundle/Controller/CollectionController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/Focus/Focus.php
  src/Sulu/Bundle/PageBundle/Controller/ResourcelocatorController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewController.php
  src/Sulu/Bundle/RouteBundle/Controller/RouteController.php
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/TestBundle/Testing/PhpCrInitTrait.php
  src/Sulu/Bundle/TrashBundle/UserInterface/Controller/Admin/TrashItemController.php
  src/Sulu/Bundle/WebsiteBundle/Controller/AnalyticsController.php
  src/Sulu/Component/Content/Import/WebspaceImport.php
  src/Sulu/Component/Content/Metadata/Parser/PropertiesXmlParser.php
  src/Sulu/Component/DocumentManager/PropertyEncoder.php
  src/Sulu/Component/DocumentManager/Subscriber/Core/MappingSubscriber.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineWhereExpression.php
  src/Sulu/Component/Rest/ListBuilder/Filter/NumberFilterType.php
  src/Sulu/Component/Rest/ListBuilder/Filter/TextFilterType.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ListXmlLoader.php
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
Labels: DX

#7335 Fix usage Api Contact Model to support ContactInterface
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Api/Contact.php
Labels: Bug

#7287 Add field exclusion strategy for SnippetController
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/CoreBundle/Serializer/Exclusion/FieldsExclusionStrategy.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
Labels: Feature

#7336 Add missing upgrade lines for file version changes
  UPGRADE.md
Labels: Bug

#7337 Add missing upgrade for reference table
  UPGRADE.md
Labels: Bug

#7338 Add stricter checks for correct types in reference handling
  src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
  src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/MediaSelectionContentTypeTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/SingleMediaSelectionTest.php
  src/Sulu/Bundle/SnippetBundle/Content/SingleSnippetSelection.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
Labels: Bug
