Repository sulu/sulu, pull requests merged in 2024-11, with the labels that each got.

#7633 Fix OpenIdSingleSignOnAdapter for custom class overrides using userRepository
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapterTest.php
Labels: Bug

#7639 Fix build of admin js by exclude fos/jsrouting-bundle from babel loader in the webpack config
  webpack.config.js
Labels: Bug

#7641 Fix file inspector tests namespace
  src/Sulu/Bundle/MediaBundle/Tests/Unit/FileInspector/SvgFileInspectorTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/FileInspector/UploadFileSubscriberTest.php
Labels: DX

#7642 Fix failing search tests with unencode url at the end
  phpstan-baseline.neon
  src/Sulu/Bundle/SearchBundle/Tests/Functional/Controller/WebsiteSearchControllerTest.php
Labels: Bug

#7607 Fix nested file inspection
  src/Sulu/Bundle/MediaBundle/FileInspector/UploadFileSubscriber.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/FileInspector/SvgFileInspectorTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/FileInspector/UploadFileSubscriberTest.php
Labels: Bug

#7643 Fix failing upload test snapshots
  src/Sulu/Bundle/AdminBundle/Resources/js/components/FileUploadButton/tests/__snapshots__/FileUploadButton.test.js.snap
  src/Sulu/Bundle/AdminBundle/Resources/js/views/List/tests/toolbarActions/__snapshots__/UploadToolbarAction.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/components/SingleMediaDropzone/tests/__snapshots__/SingleMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaCollection/tests/__snapshots__/MediaCollection.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaSelectionOverlay/tests/__snapshots__/MediaSelectionOverlay.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MediaVersionUpload/tests/__snapshots__/MediaVersionUpload.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/MultiMediaDropzone/tests/__snapshots__/MultiMediaDropzone.test.js.snap
  src/Sulu/Bundle/MediaBundle/Resources/js/containers/SingleMediaUpload/tests/__snapshots__/SingleMediaUpload.test.js.snap
Labels: Bug

#7647 Add default empty schema to form metadata
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/default.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/overview.json
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
Labels: Bug

#7648 Add default empty schema to form metadata
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
Labels: Bug

#7654 Fix issue with backmerge 2.5 in 2.6 duplicated __construct method
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
Labels: Bug

#7656 Remove integration of swiftmailer
  .env
  .github/workflows/test-application.yaml
  UPGRADE.md
  composer.json
  phpstan.neon
  src/Sulu/Bundle/MarkupBundle/DependencyInjection/SuluMarkupExtension.php
  src/Sulu/Bundle/MarkupBundle/Listener/SwiftMailerListener.php
  src/Sulu/Bundle/MarkupBundle/Resources/config/swiftmailer.xml
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/SwiftMailerListenerTest.php
  src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/LegacyResettingControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/ResettingControllerTest.php
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/config.php
  src/Sulu/Bundle/TestBundle/Resources/app/config/swiftmailer.yml
Labels: DX

#7657 Set min version of Symfony to ^6.4 || ^7.1 for using AbstractBundle class
  composer.json
Labels: DX

#7651 Fix using vips without the vips php extension
  phpstan-baseline.neon
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Compiler/DocumentFixturePass.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
Labels: Bug

#7658 Add Sulu 3.0 var directories to gitignore for better DX
  .gitignore
Labels: DX

#7667 Add a conflict to the doctrine bundle 2.13.1 version
  composer.json
  phpstan-baseline.neon
Labels: Bug

#7644 Add PHP 8.4 to Sulu CI
  .github/workflows/test-application.yaml
  src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTest.php
Labels: Feature

#7669 Fix local test running with max connection error
  docker-compose.override.yml
Labels: Bug

#7632 Fix admin frontend initialization after login with 2FA
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/userStore/userStore.js
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
  test.svg
Labels: Bug

#7665 Upgrade doctrine cache to 2
  .github/workflows/test-application.yaml
  composer.json
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Twig/CategoryTwigExtensionTest.php
  src/Sulu/Bundle/ContactBundle/Resources/config/services.xml
  src/Sulu/Bundle/ContactBundle/Tests/Unit/ContactTwigExtensionTest.php
  src/Sulu/Bundle/CoreBundle/Resources/config/cache.xml
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewCacheTest.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Twig/UserTwigExtensionTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Twig/TagTwigExtensionTest.php
  src/Sulu/Component/Cache/Memoize.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Webspace/Tests/Unit/StructureProvider/WebspaceStructureProviderTest.php
Labels: DX

#7670 Add animate support for webp
  src/Sulu/Bundle/MediaBundle/Media/ImageConverter/ImagineImageConverter.php
Labels: Feature

#7671 Define support rokka vips imagine adapter versions
  composer.json
Labels: DX

#7676 Remove check for content bundle package instead check for Bundle
  composer.json
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/SuluContactExtension.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/SuluMediaExtension.php
  src/Sulu/Bundle/TagBundle/DependencyInjection/SuluTagExtension.php
Labels: DX

#7677 Increase version of FOSHttpCache
  composer.json
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/SuluHttpCacheExtension.php
Labels: DX

#7620 Remove deprecated ListingRestHelpers
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Component/Rest/Listing/ListQueryBuilder.php
  src/Sulu/Component/Rest/Listing/ListRepository.php
  src/Sulu/Component/Rest/Listing/ListRestHelper.php
  src/Sulu/Component/Rest/Tests/Unit/Listing/ListQueryBuilderTest.php
  src/Sulu/Component/Rest/Tests/Unit/Listing/ListRestHelperTest.php
Labels: Technical Debt, DX

#7600 Remove deprecated `Urlizer`
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/CustomUrlBundle/Tests/Functional/Controller/CustomUrlControllerTest.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/SuluDocumentManagerExtension.php
  src/Sulu/Bundle/DocumentManagerBundle/Slugifier/Urlizer.php
  src/Sulu/Bundle/PreviewBundle/Tests/Functional/UserInterface/Controller/PreviewLinkControllerTest.php
Labels: DX

#7681 Fix npm lint issue in webpack.config.js
  webpack.config.js
Labels: Technical Debt

#7683 Fix npm lint by exclude content and article bundle test setup
  .eslintignore
  .flowconfig
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/SuluCategoryExtension.php
Labels: Technical Debt

#7680 Replace ramsey uuid package with symfony uid package and v4 to v7 Uuid
  composer.json
  packages/article/src/Domain/Model/Article.php
  src/Sulu/Bundle/HttpCacheBundle/Cache/CacheManager.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/TagsSubscriberTest.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Doctrine/Repository/PreviewLinkRepository.php
  src/Sulu/Bundle/ReferenceBundle/Tests/Functional/Infrastructure/Doctrine/Repository/ReferenceRepositoryTest.php
  src/Sulu/Bundle/ReferenceBundle/Tests/Unit/Domain/Model/ReferenceTest.php
  src/Sulu/Bundle/SecurityBundle/EventListener/AuhenticationFailureListener.php
  src/Sulu/Bundle/SecurityBundle/SingleSignOn/Adapter/OpenId/OpenIdSingleSignOnAdapter.php
Labels: DX

#7688 Fix custom admin build on windows machines
  webpack.config.js
Labels: Bug

#7685 Add mariadb to test matrix
  .github/workflows/test-application.yaml
  packages/content/tests/Functional/Integration/ExampleControllerAvailableAndShadowLocalesTest.php
  tests/docker/docker-compose.mariadb-114.yml
Labels: DX

#7693 Replace piwik with matomo analytic templates
  UPGRADE.md
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/matomo/body-open.html.twig
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Analytics/matomo/head-close.html.twig
Labels: Feature

#7689 Update deprecated babel proposal
  babel.config.json
  package.json
Labels: Technical Debt
