Repository sulu/sulu, pull requests merged in 2024-08, with the labels that each got.

#7556 Fix loading of website bundle config in admin context
  src/Sulu/Component/HttpKernel/SuluKernel.php
Labels: Bug

#7557 Fix portalInformaton handling in RequestListener when UserBasedContext is active
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/Routing/RequestListener.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Routing/RequestListenerTest.php
Labels: Bug

#7559 Throw exception on missing file in LocalStorage
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/LocalStorageTest.php
Labels: DX

#7563 Fix php deprecations for string and int types given as null
  phpstan-baseline.neon
  src/Sulu/Component/Content/Types/ResourceLocator/Mapper/PhpcrMapper.php
  src/Sulu/Component/DocumentManager/NodeManager.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/EncodeAliasTrait.php
  src/Sulu/Component/Util/SortUtils.php
Labels: DX

#7565 Marking twig function as deprecated
  .php-cs-fixer.dist.php
  src/Sulu/Bundle/SnippetBundle/Twig/DefaultSnippetTwigExtension.php
Labels: DX

#7575 Fix ENOENT: no such file or directory, open 'node:stream' by downgrad cheerio to 1.0.0-rc.12
  package.json
Labels: Bug

#7576 Fix some new phpstan issues with media count and logger message
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
  src/Sulu/Component/DocumentManager/Tests/Unit/EventDispatcher/DebugEventDispatcherTest.php
Labels: DX

#7577 Fix debug:translation --only-missing command
  composer.json
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_localizations.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Admin/Navigation/NavigationRegistryTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/ListMetadata/XmlListMetadataLoaderTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Unit/Generator/SymfonyExpressionTokenProviderTest.php
  src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
  src/Sulu/Bundle/SecurityBundle/Resources/views/mail_templates/reset_password.html.twig
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
  src/Sulu/Component/Rest/Tests/Unit/FlattenExceptionNormalizerTest.php
  tests/Resources/DataFixtures/Page/template_with_localizations.xml
Labels: Bug

#7578 Fix debug:translation --only-missing command for 2.6
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/DependencyInjection/Compiler/SnippetAreaCompilerPassTest.php
Labels: Bug

#7573 Introduce sulu.focus event on text_area, text_line and text_editor
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/tests/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/Input/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/TextArea.js
  src/Sulu/Bundle/AdminBundle/Resources/js/components/TextArea/tests/TextArea.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/CKEditor5/tests/CKEditor5.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/Field.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/Input.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/TextArea.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/fields/TextEditor.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/Field.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/Input.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/TextArea.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/tests/fields/TextEditor.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/Form/types.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/adapters/CKEditor5.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/TextEditor/types.js
Labels: Feature, DX
