Repository sulu/sulu, pull requests merged in 2024-07, with the labels that each got.

#7500 Improve error message on not found data-config attribute
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: DX

#7504 Fix compatibility to Node 14 and 16 and NPM 6
  symlink-vendor-directory.js
Labels: Bug

#7506 Backport test type changes to 2.5
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/EventListener/TargetGroupSubscriberTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Component/Contact/Tests/Unit/SmartContent/AccountDataProviderTest.php
Labels: DX

#7510 Replacing `will` method with more specific methods
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Content/Types/LocationContentTypeTest.php
  src/Sulu/Bundle/LocationBundle/Tests/Unit/Geolocator/GeolocatorResponseTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/MediaSelectionContentTypeTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Content/SnippetContentTest.php
  src/Sulu/Bundle/TagBundle/Tests/Unit/Tag/TagManagerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapGeneratorTest.php
  src/Sulu/Component/Rest/Tests/Unit/RestHelperTest.php
  src/Sulu/Component/SmartContent/Tests/Unit/ContentTypeTest.php
  src/Sulu/Component/Util/Tests/Unit/SuluNodeHelperTest.php
Labels: DX

#7520 Fix security check for snippet references tab
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
Labels: Bug

#7508 Finish upgrade to PHPUnit 10
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/ContactBundle/Tests/Functional/Controller/AccountControllerTest.php
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/InvalidationSubscriberTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/TagBundle/Tests/Functional/Controller/TagControllerTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/EventListener/SecurityListenerTest.php
Labels: DX

#7529 Remove many-to-many joins in smart content functions.
  src/Sulu/Bundle/ContactBundle/Entity/AccountRepository.php
  src/Sulu/Bundle/ContactBundle/Entity/ContactRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaDataProviderRepository.php
  src/Sulu/Bundle/MediaBundle/Entity/MediaRepository.php
Labels: Performance

#7534 Add forcing direct matching for media image format urls
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManagerInterface.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
Labels: Performance

#7535 Add forcing direct matching for media download urls
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
Labels: Performance

#7536 Fix cachelifetime configuration for sitemap
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Controller/SitemapControllerTest.php
Labels: Bug

#7538 Fix deprecation message on HitListener rtrim function call
  src/Sulu/Component/Webspace/Analyzer/RequestAnalyzer.php
  src/Sulu/Component/Webspace/Tests/Unit/Analyzer/RequestAnalyzerTest.php
Labels: Bug

#7537 Allow to debug SuluHttpCache without Kernel Debug enabled
  src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php
Labels: Feature

#7540 Disable fallback to smaxage for our symfony http cache customttllistener handling
  UPGRADE.md
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/Controller/TemplateController.php
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/config_website.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_website.yml
  src/Sulu/Bundle/HttpCacheBundle/Cache/SuluHttpCache.php
Labels: Bug

#7491 Use constructor property promotion in SearchBundle
  phpstan-baseline.neon
  src/Sulu/Bundle/SearchBundle/Admin/SearchAdmin.php
  src/Sulu/Bundle/SearchBundle/Controller/SearchController.php
  src/Sulu/Bundle/SearchBundle/Controller/WebsiteSearchController.php
  src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfiguration.php
  src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfigurationProvider.php
  src/Sulu/Bundle/SearchBundle/Search/Configuration/IndexConfigurationProviderInterface.php
  src/Sulu/Bundle/SearchBundle/Search/Configuration/Route.php
  src/Sulu/Bundle/SearchBundle/Search/Converter/StructureConverter.php
  src/Sulu/Bundle/SearchBundle/Search/Event/StructureMetadataLoadEvent.php
  src/Sulu/Bundle/SearchBundle/Tests/Resources/TestBundle/Controller/SearchController.php
Labels: DX

#7495 Use constructor property promotion in the SnippetBundle
  phpstan-baseline.neon
  src/Sulu/Bundle/SnippetBundle/Admin/SnippetAdmin.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetExportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetImportCommand.php
  src/Sulu/Bundle/SnippetBundle/Command/SnippetLocaleCopyCommand.php
  src/Sulu/Bundle/SnippetBundle/Content/SingleSnippetSelection.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetContent.php
  src/Sulu/Bundle/SnippetBundle/Content/SnippetDataProvider.php
  src/Sulu/Bundle/SnippetBundle/Controller/LanguageController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetAreaController.php
  src/Sulu/Bundle/SnippetBundle/Controller/SnippetController.php
  src/Sulu/Bundle/SnippetBundle/Document/SnippetInitializer.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetCopiedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetCreatedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetModifiedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetRemovedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetRestoredEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetTranslationAddedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetTranslationCopiedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/SnippetTranslationRemovedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/WebspaceDefaultSnippetModifiedEvent.php
  src/Sulu/Bundle/SnippetBundle/Domain/Event/WebspaceDefaultSnippetRemovedEvent.php
  src/Sulu/Bundle/SnippetBundle/EventListener/DomainEventSubscriber.php
  src/Sulu/Bundle/SnippetBundle/EventListener/SnippetTrashSubscriber.php
  src/Sulu/Bundle/SnippetBundle/Snippet/DefaultSnippetManager.php
  src/Sulu/Bundle/SnippetBundle/Snippet/SnippetRepository.php
  src/Sulu/Bundle/SnippetBundle/Snippet/SnippetResolver.php
  src/Sulu/Bundle/SnippetBundle/Snippet/WrongSnippetTypeException.php
  src/Sulu/Bundle/SnippetBundle/Trash/SnippetTrashItemHandler.php
  src/Sulu/Bundle/SnippetBundle/Twig/DefaultSnippetTwigExtension.php
  src/Sulu/Bundle/SnippetBundle/Twig/MemoizedSnippetTwigExtension.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetAreaTwigExtension.php
  src/Sulu/Bundle/SnippetBundle/Twig/SnippetTwigExtension.php
Labels: DX

#7496 Use constructor property promotion in TagBundle
  phpstan-baseline.neon
  src/Sulu/Bundle/TagBundle/Admin/TagAdmin.php
  src/Sulu/Bundle/TagBundle/Content/Types/TagSelection.php
  src/Sulu/Bundle/TagBundle/Controller/Exception/ConstraintViolationException.php
  src/Sulu/Bundle/TagBundle/Controller/TagController.php
  src/Sulu/Bundle/TagBundle/Domain/Event/TagCreatedEvent.php
  src/Sulu/Bundle/TagBundle/Domain/Event/TagMergedEvent.php
  src/Sulu/Bundle/TagBundle/Domain/Event/TagModifiedEvent.php
  src/Sulu/Bundle/TagBundle/Domain/Event/TagRemovedEvent.php
  src/Sulu/Bundle/TagBundle/Domain/Event/TagRestoredEvent.php
  src/Sulu/Bundle/TagBundle/Event/TagDeleteEvent.php
  src/Sulu/Bundle/TagBundle/Event/TagMergeEvent.php
  src/Sulu/Bundle/TagBundle/Search/TagsConverter.php
  src/Sulu/Bundle/TagBundle/Tag/Exception/TagAlreadyExistsException.php
  src/Sulu/Bundle/TagBundle/Tag/Exception/TagNotFoundException.php
  src/Sulu/Bundle/TagBundle/Tag/TagManager.php
  src/Sulu/Bundle/TagBundle/Trash/TagTrashItemHandler.php
  src/Sulu/Bundle/TagBundle/Twig/TagTwigExtension.php
Labels: DX

#7497 Using constructor property promotion in TrashBundle
  phpstan-baseline.neon
  src/Sulu/Bundle/TrashBundle/Application/DoctrineRestoreHelper/DoctrineRestoreHelper.php
  src/Sulu/Bundle/TrashBundle/Application/TrashManager/TrashManager.php
  src/Sulu/Bundle/TrashBundle/Domain/Event/TrashItemRemovedEvent.php
  src/Sulu/Bundle/TrashBundle/Domain/Exception/RestoreTrashItemHandlerNotFoundException.php
  src/Sulu/Bundle/TrashBundle/Domain/Exception/StoreTrashItemHandlerNotFoundException.php
  src/Sulu/Bundle/TrashBundle/Domain/Exception/TrashItemNotFoundException.php
  src/Sulu/Bundle/TrashBundle/Infrastructure/Doctrine/Repository/TrashItemRepository.php
  src/Sulu/Bundle/TrashBundle/Infrastructure/Sulu/Admin/TrashAdmin.php
  src/Sulu/Bundle/TrashBundle/Tests/Application/Trash/TestTrashItemHandler.php
  src/Sulu/Bundle/TrashBundle/UserInterface/Controller/Admin/TrashItemController.php
Labels: DX

#7492 Using constructor property promotion in the SecurityBundle
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/AccessControl/AccessControlQueryEnhancer.php
  src/Sulu/Bundle/SecurityBundle/Admin/Helper/SecuritySystemsSelect.php
  src/Sulu/Bundle/SecurityBundle/Admin/Helper/SystemLanguageSelect.php
  src/Sulu/Bundle/SecurityBundle/Admin/SecurityAdmin.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateRoleCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/CreateUserCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/InitCommand.php
  src/Sulu/Bundle/SecurityBundle/Command/SyncPhpcrPermissionsCommand.php
  src/Sulu/Bundle/SecurityBundle/Controller/ContextsController.php
  src/Sulu/Bundle/SecurityBundle/Controller/GroupController.php
  src/Sulu/Bundle/SecurityBundle/Controller/PermissionController.php
  src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php
  src/Sulu/Bundle/SecurityBundle/Controller/ResettingController.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/Controller/RoleSettingController.php
  src/Sulu/Bundle/SecurityBundle/Controller/UserController.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/RoleCreatedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/RoleModifiedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/RoleRemovedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserCreatedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserEnabledEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserLockedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserModifiedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserPasswordResettedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserRemovedEvent.php
  src/Sulu/Bundle/SecurityBundle/Domain/Event/UserUnlockedEvent.php
  src/Sulu/Bundle/SecurityBundle/EventListener/AuhenticationFailureListener.php
  src/Sulu/Bundle/SecurityBundle/EventListener/ForceTwoFactorSubscriber.php
  src/Sulu/Bundle/SecurityBundle/EventListener/LastLoginListener.php
  src/Sulu/Bundle/SecurityBundle/EventListener/LogoutEventSubscriber.php
  src/Sulu/Bundle/SecurityBundle/EventListener/PermissionInheritanceSubscriber.php
  src/Sulu/Bundle/SecurityBundle/EventListener/PhpcrSecuritySubscriber.php
  src/Sulu/Bundle/SecurityBundle/EventListener/SuluSecurityListener.php
  src/Sulu/Bundle/SecurityBundle/EventListener/SystemListener.php
  src/Sulu/Bundle/SecurityBundle/EventListener/UserLocaleListener.php
  src/Sulu/Bundle/SecurityBundle/Exception/RoleKeyAlreadyExistsException.php
  src/Sulu/Bundle/SecurityBundle/Exception/RoleNameAlreadyExistsException.php
  src/Sulu/Bundle/SecurityBundle/Exception/UserNotInSystemException.php
  src/Sulu/Bundle/SecurityBundle/Metadata/PasswordPolicyFormMetadataVisitor.php
  src/Sulu/Bundle/SecurityBundle/Metadata/TwoFactorFormMetadataVisitor.php
  src/Sulu/Bundle/SecurityBundle/Security/AuthenticationHandler.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/EmailNotUniqueException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/EmailTemplateException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/InvalidTokenException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/TokenAlreadyRequestedException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/TokenEmailsLimitReachedException.php
  src/Sulu/Bundle/SecurityBundle/Security/Exception/UsernameNotUniqueException.php
  src/Sulu/Bundle/SecurityBundle/Security/LogoutSuccessHandler.php
  src/Sulu/Bundle/SecurityBundle/System/SystemStore.php
  src/Sulu/Bundle/SecurityBundle/Twig/UserTwigExtension.php
  src/Sulu/Bundle/SecurityBundle/User/UserProvider.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
Labels: DX

#7542 Replacing deprecated `getMockForTrait` phpunit function
  phpstan-baseline.neon
  src/Sulu/Component/Cache/MemoizeTwigExtensionTrait.php
  src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTwigExtensionTraitTest.php
  src/Sulu/Component/SmartContent/Orm/DataProviderRepositoryTrait.php
  src/Sulu/Component/SmartContent/Tests/Unit/Orm/DataProviderRepositoryTraitTest.php
Labels: DX

#7543 Fix whitespace handling in URLs of media file names
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/LocalFormatCache.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/LocalFormatCacheTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatCache/LocalFormatCacheTest.php
Labels: Bug

#7546 More property promotion in bundles
  phpstan-baseline.neon
  src/Sulu/Component/Export/Export.php
  src/Sulu/Component/Export/Manager/ExportManager.php
  src/Sulu/Component/Hash/RequestHashChecker.php
  src/Sulu/Component/Hash/Serializer/Subscriber/HashSerializeEventSubscriber.php
  src/Sulu/Component/Import/Import.php
  src/Sulu/Component/Import/Manager/ImportManager.php
  src/Sulu/Component/Localization/Provider/LocalizationProvider.php
  src/Sulu/Component/Media/SmartContent/MediaDataItem.php
  src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
  src/Sulu/Component/Media/SystemCollections/SystemCollectionBuilder.php
  src/Sulu/Component/Media/SystemCollections/SystemCollectionManager.php
  src/Sulu/Component/PHPCR/SessionManager/SessionManager.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/MetadataSubscriber.php
  src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php
  src/Sulu/Component/Rest/AbstractRestController.php
  src/Sulu/Component/Rest/Csv/CsvHandler.php
  src/Sulu/Component/Rest/FlattenExceptionNormalizer.php
  src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilder.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/DoctrineListBuilderFactory.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCaseFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineConcatenationFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineCountFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineGroupConcatFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineIdentityFieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Doctrine/FieldDescriptor/DoctrineJoinDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineBetweenExpression.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineConjunctionExpression.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineInExpression.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineNotExpression.php
  src/Sulu/Component/Rest/ListBuilder/Expression/Doctrine/DoctrineWhereExpression.php
  src/Sulu/Component/Rest/ListBuilder/FieldDescriptor.php
  src/Sulu/Component/Rest/ListBuilder/ListRepresentation.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/AbstractPropertyMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldMetadata.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/ListXmlLoader.php
  src/Sulu/Component/Rest/Listing/ListQueryBuilder.php
  src/Sulu/Component/Rest/Listing/ListRepository.php
  src/Sulu/Component/Rest/RestHelper.php
  src/Sulu/Component/Route/RouteDefaultOptionsCompilerPass.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/Security/Authorization/AccessControl/DoctrineAccessControlProvider.php
  src/Sulu/Component/Security/Authorization/AccessControl/PhpcrAccessControlProvider.php
  src/Sulu/Component/Security/Authorization/MaskConverter.php
  src/Sulu/Component/Security/Authorization/SecurityChecker.php
  src/Sulu/Component/Security/Authorization/SecurityCondition.php
  src/Sulu/Component/Security/Authorization/SecurityContextVoter.php
  src/Sulu/Component/Security/Event/PermissionUpdateEvent.php
  src/Sulu/Component/Security/Serializer/Subscriber/SecuredEntitySubscriber.php
Labels: DX

#7549 Backport PHPStan stype fixes from 2.6
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Tests/Functional/SmartContent/QueryBuilderTest.php
  src/Sulu/Component/Contact/SmartContent/AccountDataItem.php
  src/Sulu/Component/Contact/SmartContent/ContactDataItem.php
  src/Sulu/Component/Content/Compat/Block/BlockPropertyWrapper.php
  src/Sulu/Component/Content/Compat/Property.php
  src/Sulu/Component/Content/Compat/PropertyInterface.php
  src/Sulu/Component/Content/Compat/Section/SectionProperty.php
  src/Sulu/Component/Content/Mapper/Translation/TranslatedProperty.php
  src/Sulu/Component/Content/SmartContent/ContentDataItem.php
  src/Sulu/Component/Content/SmartContent/PageDataProvider.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  src/Sulu/Component/Content/Types/ResourceLocator/ResourceLocatorInformation.php
  src/Sulu/Component/Media/SmartContent/MediaDataItem.php
  src/Sulu/Component/Media/SmartContent/MediaDataProvider.php
  src/Sulu/Component/Rest/ListBuilder/Metadata/FieldDescriptorFactory.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/SmartContent/ArrayAccessItem.php
  src/Sulu/Component/SmartContent/DataProviderInterface.php
  src/Sulu/Component/SmartContent/DatasourceItem.php
  src/Sulu/Component/SmartContent/DatasourceItemInterface.php
  src/Sulu/Component/SmartContent/ItemInterface.php
  src/Sulu/Component/SmartContent/Orm/BaseDataProvider.php
  src/Sulu/Component/SmartContent/ResourceItemInterface.php
  src/Sulu/Component/Util/Tests/Unit/SortUtilsTest.php
Labels: DX

#7550 Fix block property call
  phpstan-baseline.neon
  src/Sulu/Component/Content/Compat/Block/BlockProperty.php
Labels: Bug
