Repository sulu/sulu, pull requests merged in 2025-04, with the labels that each got.

#7874 Add findBy to RouteRepository for Localization switcher
  packages/route/src/Domain/Repository/RouteRepositoryInterface.php
  packages/route/src/Infrastructure/Doctrine/Repository/RouteRepository.php
  packages/route/tests/Functional/Infrastructure/Doctrine/Repository/RouteRepositoryTest.php
Labels: Feature

#7875 Add service layers to support old and new routing bundle
  config/bundles.php
  packages/article/tests/Application/Kernel.php
  packages/route/config/deprecated_service_bridge.xml
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/tests/Functional/Infrastructure/Doctrine/Repository/RouteRepositoryTest.php
  phpstan.dist.neon
  src/Sulu/Bundle/TestBundle/Kernel/SuluTestKernel.php
Labels: DX

#7882 Fix RouteBundle issues and disable Show History button
  packages/page/src/Infrastructure/Sulu/Route/WebspaceSiteRouteGenerator.php
  packages/route/src/Application/Routing/Generator/RouteGenerator.php
  packages/route/src/Application/Routing/Matcher/RouteHistoryDefaultsProvider.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/tests/Unit/Application/Generator/RouteGeneratorTest.php
  packages/route/tests/Unit/Application/Matcher/RouteHistoryDefaultsProviderTest.php
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/ResourceLocatorHistory.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/ResourceLocatorHistory.test.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/ResourceLocatorHistory/tests/__snapshots__/ResourceLocatorHistory.test.js.snap
  src/Sulu/Component/Webspace/Analyzer/Attributes/AdminRequestProcessor.php
Labels: Bug

#7885 Add published/draft indicator to page/article/snippet list + fix homepage routing issue
  packages/article/config/lists/articles.xml
  packages/article/src/UserInterface/Controller/Admin/ArticleController.php
  packages/article/tests/Functional/Integration/responses/article_cget.json
  packages/content/src/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php
  packages/content/src/Application/ContentResolver/ContentResolver.php
  packages/content/tests/Unit/Content/Application/ContentResolver/ContentResolverTest.php
  packages/page/config/lists/pages.xml
  packages/page/src/UserInterface/Controller/Admin/PageController.php
  packages/page/tests/Functional/Integration/responses/page_cget.json
  packages/page/tests/Functional/Integration/responses/page_post_after_order_list.json
  packages/page/tests/Functional/Integration/responses/page_post_before_order_list.json
  packages/route/src/Application/Routing/Matcher/RouteCollectionForRequestRouteLoader.php
  packages/snippet/config/lists/snippets.xml
  packages/snippet/src/Infrastructure/Sulu/Admin/SnippetAdmin.php
  packages/snippet/src/UserInterface/Controller/Admin/SnippetController.php
  packages/snippet/tests/Functional/Integration/responses/snippet_cget.json
Labels: Bug

#7881 Bugfix for non-int page value
  src/Sulu/Component/SmartContent/ContentType.php
Labels: Bug

#7890 Fix translations for changer and creator
  packages/article/config/lists/articles.xml
  packages/page/config/lists/pages.xml
  packages/snippet/config/lists/snippets.xml
Labels: Bug

#7894 Split PHPCR 3.0 upgrade steps in more steps
  UPGRADE-3.x.md
Labels: DX

#7903 Fix unused variables in tests
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/CollectionControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/FormatControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaWebsiteControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/TypeManager/TypeManagerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Command/ValidateWebspacesCommandTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/PageResourcelocatorControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Controller/SmartContentItemControllerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Export/WebspaceExportTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Mapper/ContentMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/Repository/NodeRepositoryTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/Mapper/PhpcrMapperTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/ResourceLocatorTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/Strategy/TreeFullEditStrategyTest.php
  src/Sulu/Bundle/PageBundle/Tests/Functional/ResourceLocator/Strategy/TreeLeafEditStrategyTest.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Entity/RouteRepositoryTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Controller/SnippetControllerTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Functional/Export/SnippetTest.php
Labels: Technical Debt

#7905 Enable new bundles in core Kernel for better validation
  config/bundles.php
  config/routes/sulu_admin.yaml
  config/templates/articles/article.xml
  config/templates/pages/example.xml
  config/templates/pages/homepage.xml
  packages/snippet/translations/admin.de.json
  packages/snippet/translations/admin.en.json
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/DependencyInjection/Compiler/SuluNextPageCompilerPass.php
  templates/articles/article.html.twig
Labels: Technical Debt

#7907 Add article property resolver / resource loader
  packages/article/src/Infrastructure/Sulu/Content/ArticleSelectionContentType.php
  packages/article/src/Infrastructure/Sulu/Content/PropertyResolver/ArticleSelectionPropertyResolver.php
  packages/article/src/Infrastructure/Sulu/Content/PropertyResolver/SingleArticleSelectionPropertyResolver.php
  packages/article/src/Infrastructure/Sulu/Content/ResourceLoader/ArticleResourceLoader.php
  packages/article/src/Infrastructure/Sulu/Content/SingleArticleSelectionContentType.php
  packages/article/src/Infrastructure/Symfony/HttpKernel/SuluArticleBundle.php
  packages/article/tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/ArticleSelectionPropertyResolverTest.php
  packages/article/tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/SingleArticleSelectionPropertyResolverTest.php
  packages/article/tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/ArticleResourceLoaderTest.php
  packages/snippet/src/Infrastructure/Symfony/HttpKernel/SuluSnippetBundle.php
Labels: Feature

#7911 Add auto-configuration of resource-loader and property-resolver
  packages/content/config/resource-loader.xml
  packages/content/src/Infrastructure/Symfony/HttpKernel/Compiler/ResourceLoaderCacheCompilerPass.php
  packages/content/src/Infrastructure/Symfony/HttpKernel/SuluContentBundle.php
  src/Sulu/Bundle/CategoryBundle/Resources/config/services_content.xml
  src/Sulu/Bundle/ContactBundle/Resources/config/services_content.xml
  src/Sulu/Bundle/MediaBundle/Resources/config/services_content.xml
  src/Sulu/Bundle/TagBundle/Resources/config/services_content.xml
Labels: DX

#7912 Readd handling for route defaults options utf8 true
  packages/route/src/Infrastructure/Symfony/DependencyInjection/RouteDefaultsOptionsCompilerPass.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/src/Infrastructure/SymfonyCmf/Routing/CmfRouteProvider.php
  packages/route/tests/Functional/Infrastructure/SymfonyCmf/Routing/CmfRouteProviderTest.php
  src/Sulu/Bundle/CustomUrlBundle/SuluCustomUrlBundle.php
  src/Sulu/Bundle/RouteBundle/SuluRouteBundle.php
  src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
  src/Sulu/Component/Route/RouteDefaultOptionsCompilerPass.php
Labels: Feature

#7916 Move expression language service from core to admin bundle
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/ExpressionLanguage/ContainerExpressionLanguageProvider.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/ExpressionLanguage/ContainerExpressionLanguageProviderTest.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/CoreBundle/Resources/config/expression_language.xml
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu_document_manager.yml
Labels: Technical Debt, DX

#7915 Remove sulu website twig attributes configuration
  UPGRADE-3.x.md
  config/packages/sulu_website.yaml
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Content/PageSelectionContainer.php
  src/Sulu/Bundle/PageBundle/Content/Types/PageSelection.php
  src/Sulu/Bundle/PageBundle/Resources/config/content_types.xml
  src/Sulu/Bundle/PageBundle/Resources/config/smart_content.xml
  src/Sulu/Bundle/TestBundle/Resources/app/config/sulu.yml
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/SuluWebsiteExtension.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationMapper.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/ParameterResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/StructureResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resolver/TemplateAttributeResolver.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Navigation/NavigationMapperTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/ParameterResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/StructureResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Resolver/TemplateAttributeResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Twig/ContentTwigExtensionTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Content/ContentTwigExtension.php
  src/Sulu/Component/Content/SmartContent/PageDataProvider.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
Labels: Technical Debt, DX

#7921 Add some more hints to the 3.0 upgrade and move data migration down
  UPGRADE-3.x.md
Labels: DX

#7922 Fix return empty array if teaser selection property resolver data not matching
  packages/content/src/Application/PropertyResolver/Resolver/TeaserSelectionPropertyResolver.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/Resolver/TeaserSelectionPropertyResolverTest.php
Labels: Bug

#7929 Add Multilingual to new property metadata
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/default.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/overview.json
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
Labels: Technical Debt

#7932 Remove old content upgrade file
  packages/content/UPGRADE.md
Labels: DX

#7930 Make new metadata locale independent to contain all data
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Controller/AdminController.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/ItemMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/OptionMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Visitor/LocalesOptionFormMetadataVisitor.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Serializer/Subscriber/MetadataSubscriber.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/default.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/overview.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/SecurityBundle/Metadata/PasswordPolicyFormMetadataVisitor.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/Metadata/PasswordPolicyFormMetadataVisitorTest.php
  src/Sulu/Component/Content/SmartContent/PageDataProvider.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
  src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php
Labels: Technical Debt

#7926 Add a hint that article bundle removal may remove the template files
  UPGRADE-3.x.md
Labels: DX

#7931 Replace old metadata usage in new content bundle
  packages/article/src/Infrastructure/Sulu/Content/ArticleTeaserProvider.php
  packages/article/src/Infrastructure/Symfony/HttpKernel/SuluArticleBundle.php
  packages/content/config/data-mapper.xml
  packages/content/src/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php
  packages/content/src/Application/ContentDataMapper/DataMapper/TemplateDataMapper.php
  packages/content/src/Infrastructure/Sulu/Link/ContentLinkProvider.php
  packages/content/src/Infrastructure/Sulu/Teaser/ContentTeaserProvider.php
  packages/content/src/Infrastructure/Sulu/Traits/ResolveContentDimensionUrlTrait.php
  packages/content/tests/Application/ExampleTestBundle/Link/ExampleLinkProvider.php
  packages/content/tests/Application/ExampleTestBundle/Resources/config/services.yaml
  packages/content/tests/Application/ExampleTestBundle/Teaser/ExampleTeaserProvider.php
  packages/content/tests/Unit/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapperTest.php
  packages/content/tests/Unit/Content/Application/ContentDataMapper/DataMapper/TemplateDataMapperTest.php
  packages/page/src/Infrastructure/Sulu/Content/PageTeaserProvider.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/SectionMetadata.php
Labels: Technical Debt

#7925 Remove reference handling of tags in properties parser
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/PropertiesXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/SchemaXmlParser.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
Labels: Technical Debt
