Repository sulu/sulu, pull requests merged in 2025-02, with the labels that each got.

#7762 Fix PHP 8.4 deprecation call on SecurityVoter without a type
  phpstan-baseline.neon
  src/Sulu/Bundle/CategoryBundle/Controller/CategoryController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Bundle/MediaBundle/Controller/MediaController.php
  src/Sulu/Bundle/PageBundle/Controller/PageController.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManager.php
  src/Sulu/Component/Security/Authorization/AccessControl/AccessControlManagerInterface.php
Labels: Bug

#7729 Add DatePropertyResolver and DateTimePropertyResolver
  packages/content/config/resolvers.xml
  packages/content/src/Application/PropertyResolver/Resolver/DatePropertyResolver.php
  packages/content/src/Application/PropertyResolver/Resolver/DateTimePropertyResolver.php
  packages/content/tests/Functional/Application/ContentResolver/ContentResolverTest.php
Labels: Feature

#7774 Add SettingsResolver
  packages/article/src/UserInterface/Controller/Admin/ArticleController.php
  packages/content/config/resolvers.xml
  packages/content/src/Application/ContentResolver/ContentResolver.php
  packages/content/src/Application/ContentResolver/Resolver/ExcerptResolver.php
  packages/content/src/Application/ContentResolver/Resolver/SeoResolver.php
  packages/content/src/Application/ContentResolver/Resolver/SettingsResolver.php
  packages/content/src/Application/ContentResolver/Resolver/TemplateResolver.php
  packages/content/tests/Application/ExampleTestBundle/Entity/ExampleDimensionContent.php
  packages/content/tests/Functional/Application/ContentResolver/ContentResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/ExcerptResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/SettingsResolverTest.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services_content.xml
Labels: Feature

#7751 Fix block response for minOccurs=1 / maxOccurs=1
  packages/content/src/Application/ContentResolver/ContentResolver.php
  packages/content/src/Application/PropertyResolver/Resolver/BlockPropertyResolver.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/Resolver/BlockPropertyResolverTest.php
Labels: Bug

#7780 Allow bigger title for Dimension Content Entities
  packages/article/config/doctrine/Article/ArticleDimensionContent.orm.xml
  packages/content/tests/Application/ExampleTestBundle/Resources/config/doctrine/ExampleDimensionContent.orm.xml
  packages/snippet/config/doctrine/Snippet/SnippetDimensionContent.orm.xml
Labels: Feature

#7786 Deprecate `Permissions::$modules`
  UPGRADE.md
  src/Sulu/Bundle/SecurityBundle/Entity/Permission.php
Labels: DX

#7790 Fix some styling issues in writing_assistant and initialization bug
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/WritingAssistant/loader.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/WritingAssistant/message.scss
  src/Sulu/Bundle/AdminBundle/Resources/js/index.js
Labels: Bug

#7702 Fix DateTimeImmutable in CSV Export be formatted correctly
  src/Sulu/Component/Rest/Csv/CsvHandler.php
Labels: Bug

#7746 Fix: purge search index on build
  phpstan-baseline.neon
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
  src/Sulu/Bundle/SearchBundle/Build/InitBuilder.php
  src/Sulu/Bundle/SearchBundle/Resources/config/build.xml
Labels: Bug

#7787 Add excerpt to Snippets and add tests
  packages/snippet/src/Domain/Model/SnippetDimensionContent.php
  packages/snippet/src/Domain/Model/SnippetDimensionContentInterface.php
  packages/snippet/src/Infrastructure/Sulu/Content/PropertyResolver/SingleSnippetSelectionPropertyResolver.php
  packages/snippet/src/Infrastructure/Sulu/Content/PropertyResolver/SnippetSelectionPropertyResolver.php
  packages/snippet/src/Infrastructure/Symfony/HttpKernel/SuluSnippetBundle.php
  packages/snippet/tests/Application/Kernel.php
  packages/snippet/tests/Application/config/templates/snippets/snippet.xml
  packages/snippet/tests/Functional/Integration/SnippetControllerTest.php
  packages/snippet/tests/Functional/Integration/responses/snippet_cget.json
  packages/snippet/tests/Functional/Integration/responses/snippet_get.json
  packages/snippet/tests/Functional/Integration/responses/snippet_get_ghost_locale.json
  packages/snippet/tests/Functional/Integration/responses/snippet_post.json
  packages/snippet/tests/Functional/Integration/responses/snippet_post_publish.json
  packages/snippet/tests/Functional/Integration/responses/snippet_post_trigger_copy_locale.json
  packages/snippet/tests/Functional/Integration/responses/snippet_post_trigger_unpublish.json
  packages/snippet/tests/Functional/Integration/responses/snippet_put.json
  packages/snippet/tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/SingleSnippetSelectionPropertyResolverTest.php
  packages/snippet/tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/SnippetSelectionPropertyResolverTest.php
  packages/snippet/tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/SnippetResourceLoaderTest.php
  src/Sulu/Bundle/CategoryBundle/Infrastructure/Sulu/Content/PropertyResolver/SingleCategorySelectionPropertyResolver.php
  src/Sulu/Bundle/CategoryBundle/Tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/SingleCategorySelectionPropertyResolverTest.php
Labels: Feature

#7801 Update phpstan baseline
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Tests/Unit/Search/Reindex/StructureProviderTest.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/FallbackLocalizationSubscriberTest.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/TimestampableSubscriberTest.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/UserBlameSubscriberTest.php
Labels: DX

#7806 Requiring correct http methods on `AdminController`
  src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
Labels: DX

#7817 Make the property resolver provider final and internal provide an interface for extendability
  packages/content/config/resolvers.xml
  packages/content/src/Application/MetadataResolver/MetadataResolver.php
  packages/content/src/Application/PropertyResolver/PropertyResolverProvider.php
  packages/content/src/Application/PropertyResolver/PropertyResolverProviderInterface.php
Labels: DX

#7805 Add error output to the phpcr cleanup command
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupCommand.php
  src/Sulu/Bundle/DocumentManagerBundle/Command/PHPCRCleanupSingleNodeCommand.php
Labels: DX

#7818 Add homepage initialization builder command
  packages/content/src/Application/ContentDataMapper/DataMapper/RoutableDataMapper.php
  packages/content/tests/Unit/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapperTest.php
  packages/page/src/Application/MessageHandler/CreatePageMessageHandler.php
  packages/page/src/Infrastructure/Doctrine/Repository/PageRepository.php
  packages/page/src/Infrastructure/Sulu/Build/HomepageBuilder.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/src/UserInterface/Command/InitializeHomepageCommand.php
  packages/page/tests/Functional/UserInterface/Command/InitializeHomepageCommandTest.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
Labels: Feature

#7826 Add global blocks to Sulu 3.0
  packages/content/config/resolvers.xml
  packages/content/src/Application/PropertyResolver/Resolver/BlockPropertyResolver.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/PropertyResolverProviderTest.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/Resolver/BlockPropertyResolverTest.php
  src/Sulu/Bundle/MediaBundle/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolver.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services_content.xml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolverTest.php
Labels: Feature
