Repository sulu/sulu, pull requests merged in 2025-07, with the labels that each got.

#7747 Mark `AliasForSecurityEncoderCompilerPass` as internal
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Compiler/AliasForSecurityEncoderCompilerPass.php
Labels: Technical Debt, DX

#8046 Add page move/copy messages
  packages/page/src/Application/Message/CopyPageMessage.php
  packages/page/src/Application/Message/MovePageMessage.php
  packages/page/src/Application/MessageHandler/CopyPageMessageHandler.php
  packages/page/src/Application/MessageHandler/MovePageMessageHandler.php
  packages/page/src/Application/Normalizer/PageNormalizer.php
  packages/page/src/Domain/Repository/PageRepositoryInterface.php
  packages/page/src/Infrastructure/Doctrine/Repository/PageRepository.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/src/UserInterface/Controller/Admin/PageController.php
  packages/page/tests/Functional/Integration/PageControllerTest.php
  packages/page/tests/Functional/Integration/responses/page_cget_after_copy.json
  packages/page/tests/Functional/Integration/responses/page_cget_after_move.json
  packages/page/tests/Functional/Integration/responses/page_get.json
  packages/page/tests/Functional/Integration/responses/page_get_ghost_locale.json
  packages/page/tests/Functional/Integration/responses/page_post.json
  packages/page/tests/Functional/Integration/responses/page_post_copy.json
  packages/page/tests/Functional/Integration/responses/page_post_move.json
  packages/page/tests/Functional/Integration/responses/page_post_order.json
  packages/page/tests/Functional/Integration/responses/page_post_publish.json
  packages/page/tests/Functional/Integration/responses/page_post_publish_blog.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_copy_locale.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_unpublish.json
  packages/page/tests/Functional/Integration/responses/page_put.json
Labels: Feature

#8048 Fix and ignore some errors with strictness of optionsmetadata values
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/ExpressionFormMetadataVisitor.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/OptionMetadata.php
  src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
Labels: DX

#7999 Fix profiler tab with new content structure
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/DataCollector/SuluCollector.php
  src/Sulu/Bundle/WebsiteBundle/Resources/views/Profiler/layout.html.twig
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/DataCollector/SuluCollectorTest.php
Labels: Bug

#8049 Remove duplicated pagination
  packages/article/src/Infrastructure/Sulu/Content/ArticleSmartContentProvider.php
  packages/content/src/Infrastructure/Doctrine/DimensionContentQueryEnhancer.php
  packages/page/src/Infrastructure/Sulu/Content/PageSmartContentProvider.php
  packages/snippet/src/Infrastructure/Sulu/Content/SnippetSmartContentProvider.php
Labels: Bug

#8023 Using property types for the `DomainEvent`
  src/Sulu/Bundle/ActivityBundle/Domain/Event/DomainEvent.php
Labels: Technical Debt, DX

#8053 Move navigation content based service to Sulu Content Infrastructure integration
  packages/page/src/Infrastructure/Sulu/Content/DataMapper/NavigationContextDataMapper.php
  packages/page/src/Infrastructure/Sulu/Content/Merger/NavigationContextMerger.php
  packages/page/src/Infrastructure/Sulu/Content/Normalizer/PageNormalizer.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/tests/Unit/Infrastructure/Sulu/Content/DataMapper/NavigationContextDataMapperTest.php
  packages/page/tests/Unit/Infrastructure/Sulu/Content/Merger/NavigationContextMergerTest.php
Labels: DX

#8060 Add timestamp support to DateTimeFieldTransformer
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/fieldTransformers/DateTimeFieldTransformer.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/fieldTransformers/DateTimeFieldTransformer.test.js
Labels: Feature

#8064 Remove old route services in content bundle
  packages/content/config/services.xml
  packages/content/src/Infrastructure/Doctrine/RouteRemover.php
  packages/content/tests/Traits/CreateExampleTrait.php
  packages/content/tests/Unit/Content/Infrastructure/Doctrine/RouteRemoverTest.php
Labels: DX

#8069 Fix deprecation in Route Bundle build method by add return type
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
Labels: DX

#8071 Remove usage of old route repository in page and article controller tests
  packages/article/tests/Functional/Integration/ArticleControllerTest.php
  packages/page/tests/Functional/Integration/PageControllerTest.php
Labels: DX

#8075 Remove not longer require search init and search index builders
  src/Sulu/Bundle/CoreBundle/DependencyInjection/SuluCoreExtension.php
Labels: DX
