Repository sulu/sulu, pull requests merged in 2025-08, with the labels that each got.

#8092 Fix ImageMapPropertyResolver consistency
  packages/content/tests/Application/config/templates/examples/full-content.xml
  packages/content/tests/Functional/Application/ContentResolver/ContentResolverTest.php
  src/Sulu/Bundle/MediaBundle/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolver.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolverTest.php
Labels: Bug

#8100 Remove Navigation Mapper and Query services
  UPGRADE-3.x.md
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationItem.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationMapper.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationMapperInterface.php
  src/Sulu/Bundle/WebsiteBundle/Navigation/NavigationQueryBuilder.php
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Navigation/NavigationMapperTest.php
Labels: DX

#8101 Remove PHPCR related Sitemap Services
  src/Sulu/Bundle/WebsiteBundle/Resources/config/services.xml
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapContentQueryBuilder.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGenerator.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapGeneratorInterface.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapGeneratorTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/MemoizedSitemapTwigExtension.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/SitemapTwigExtension.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/SitemapTwigExtensionInterface.php
Labels: DX

#8105 Move Sulu Version CompilerPass to AdminBundle to avoid depending on WebsiteBundle parameters
  .gitignore
  UPGRADE-3.x.md
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Compiler/SuluVersionPass.php
  src/Sulu/Bundle/AdminBundle/SuluAdminBundle.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/Resources/VersionPass/composer.json
  src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/Resources/VersionPass/composer.lock
  src/Sulu/Bundle/AdminBundle/Tests/Unit/DependencyInjection/Compiler/SuluVersionPassTest.php
  src/Sulu/Bundle/WebsiteBundle/SuluWebsiteBundle.php
Labels: DX

#8114 Remove Page Bundle usage from Preview Tests
  src/Sulu/Bundle/PreviewBundle/Application/Manager/PreviewLinkManager.php
  src/Sulu/Bundle/PreviewBundle/Tests/Application/ExamplePreviewDefaultsProvider.php
  src/Sulu/Bundle/PreviewBundle/Tests/Application/Kernel.php
  src/Sulu/Bundle/PreviewBundle/Tests/Application/PreviewKernel.php
  src/Sulu/Bundle/PreviewBundle/Tests/Application/PreviewKernelFactory.php
  src/Sulu/Bundle/PreviewBundle/Tests/Application/config/config.yml
  src/Sulu/Bundle/PreviewBundle/Tests/Application/templates/example.html.twig
  src/Sulu/Bundle/PreviewBundle/Tests/Functional/UserInterface/Controller/PreviewLinkControllerTest.php
Labels: DX

#7764 Remove deprecated `FullLoadingStrategy`
  UPGRADE-3.x.md
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/loadingStrategies/FullLoadingStrategy.js
  src/Sulu/Bundle/AdminBundle/Resources/js/containers/List/tests/loadingStrategies/FullLoadingStrategy.test.js
Labels: Technical Debt, DX

#7785 Clean up optional argument in `AccountMediaController`
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Controller/AbstractMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/AccountMediaController.php
  src/Sulu/Bundle/ContactBundle/Controller/ContactMediaController.php
Labels: Technical Debt, DX

#7763 Remove deprecated `webspaceStore` and `localizationStore` functions
  UPGRADE-3.x.md
  packages/page/assets/js/stores/webspaceStore/tests/webspaceStore.test.js
  packages/page/assets/js/stores/webspaceStore/webspaceStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/localizationStore/localizationStore.js
  src/Sulu/Bundle/AdminBundle/Resources/js/stores/localizationStore/tests/LocalizationStore.test.js
Labels: Technical Debt, DX

#7572 Removing deprecated category functions in 3.0
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Admin/View/FormOverlayListViewBuilder.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManager.php
  src/Sulu/Bundle/CategoryBundle/Category/CategoryManagerInterface.php
  src/Sulu/Bundle/CategoryBundle/Entity/Category.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryInterface.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepository.php
  src/Sulu/Bundle/CategoryBundle/Entity/CategoryRepositoryInterface.php
Labels: Technical Debt, DX

#7752 Remove deprecated methods in `ListBuilderInterface`
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/ContactBundle/Controller/AccountController.php
  src/Sulu/Component/Rest/ListBuilder/AbstractListBuilder.php
  src/Sulu/Component/Rest/ListBuilder/ListBuilderInterface.php
Labels: Technical Debt, DX
