Repository sulu/sulu, pull requests merged in 2025-03, with the labels that each got.

#7726 Add new route implementation
  composer.json
  packages/route/.gitattributes
  packages/route/.gitignore
  packages/route/.php-cs-fixer.dist.php
  packages/route/config/doctrine/Route/Route.orm.xml
  packages/route/phpstan.neon.dist
  packages/route/phpunit.xml.dist
  packages/route/src/Domain/Model/Route.php
  packages/route/src/Domain/Repository/RouteRepositoryInterface.php
  packages/route/src/Infrastructure/Doctrine/EventListener/RouteChangedUpdater.php
  packages/route/src/Infrastructure/Doctrine/Repository/RouteRepository.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/tests/Application/.env
  packages/route/tests/Application/Kernel.php
  packages/route/tests/Application/bin/adminconsole
  packages/route/tests/Application/bin/console.php
  packages/route/tests/Application/bin/websiteconsole
  packages/route/tests/Application/config/bootstrap.php
  packages/route/tests/Application/config/config.yml
  packages/route/tests/Application/config/routing.yml
  packages/route/tests/Application/config/templates/pages/default.xml
  packages/route/tests/Application/config/templates/pages/overview.xml
  packages/route/tests/Application/config/webspaces/sulu.io.xml
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
  packages/route/tests/Functional/Infrastructure/Doctrine/Metadata/MetadataTest.php
  packages/route/tests/Unit/Domain/Model/RouteTest.php
  packages/route/tests/test-bootstrap.php
  phpstan.dist.neon
  src/Sulu/Bundle/SecurityBundle/Entity/AccessControlRepository.php
Labels: Feature, DX

#7828 Fix Sitemap generation with multiple webspaces
  phpstan-baseline.neon
  src/Sulu/Bundle/WebsiteBundle/Resources/config/sitemap.xml
  src/Sulu/Bundle/WebsiteBundle/Sitemap/Sitemap.php
  src/Sulu/Bundle/WebsiteBundle/Sitemap/SitemapProviderPool.php
  src/Sulu/Bundle/WebsiteBundle/Tests/Unit/Sitemap/SitemapProviderPoolTest.php
Labels: Bug

#7822 Enforce phpunit attributes with rector rule
  rector.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/FileInspector/SvgFileInspectorTest.php
Labels: DX

#7825 Add more details to exception messages in FormatManager
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/FormatManager/FormatManagerTest.php
Labels: DX

#7832 Fix return type for getBlock on BlockPropertyWrapper method
  phpstan-baseline.neon
  src/Sulu/Component/Content/Compat/Block/BlockPropertyWrapper.php
Labels: DX

#7831 Add additonal tests for multi locale and multi site in route update changer
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
Labels: DX

#7833 Revert unintentional list change in SuluPageExtension
  packages/page/config/lists/pages.xml
  packages/page/src/UserInterface/Controller/Admin/PageController.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
Labels: Bug

#7834 Add test for route update for cross site changes
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
Labels: Bug, DX

#7836 Add test about same starting url for route update changer
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
Labels: DX

#7841 Add test about naming methods of ContentController which extends AbstractController
  packages/content/tests/Unit/Content/UserInterface/Controller/Website/ContentControllerTest.php
Labels: DX

#7840 Add example to content controller about extending
  packages/content/src/UserInterface/Controller/Website/ContentController.php
Labels: DX

#7789 Mark all Sulu Configuration Classes as `final` and `@internal`
  src/Sulu/Bundle/ActivityBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AudienceTargetingBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/CategoryBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/ContactBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/CoreBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/DocumentManagerBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/LocationBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MarkupBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PersistenceBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/ReferenceBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/RouteBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SearchBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SnippetBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/TagBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/TestBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/TrashBundle/Infrastructure/Symfony/DependencyInjection/Configuration.php
  src/Sulu/Bundle/WebsiteBundle/DependencyInjection/Configuration.php
Labels: DX

#7770 Mark deprecated twig functions
  src/Sulu/Bundle/WebsiteBundle/Twig/Core/UtilTwigExtension.php
Labels: Technical Debt, DX

#7842 Fix mandatory condition for page tree route
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/Resources/config/services.xml
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Content/PageTreeRouteContentTypeTest.php
Labels: Bug

#7839 Add navigation context to SuluPageBundle 3.0
  packages/content/src/UserInterface/Controller/Website/ContentController.php
  packages/content/translations/admin.de.json
  packages/content/translations/admin.en.json
  packages/page/config/doctrine/Page/PageDimensionContent.orm.xml
  packages/page/config/doctrine/Page/PageDimensionContentNavigationContext.orm.xml
  packages/page/config/forms/content_settings_page_settings.xml
  packages/page/src/Application/DataMapper/NavigationContextDataMapper.php
  packages/page/src/Application/Merger/NavigationContextMerger.php
  packages/page/src/Domain/Model/PageDimensionContent.php
  packages/page/src/Domain/Model/PageDimensionContentInterface.php
  packages/page/src/Domain/Model/PageDimensionContentNavigationContext.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/tests/Functional/Integration/PageControllerTest.php
  packages/page/tests/Functional/Integration/responses/page_get.json
  packages/page/tests/Functional/Integration/responses/page_get_ghost_locale.json
  packages/page/tests/Functional/Integration/responses/page_post.json
  packages/page/tests/Functional/Integration/responses/page_post_order.json
  packages/page/tests/Functional/Integration/responses/page_post_publish.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_copy_locale.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_unpublish.json
  packages/page/tests/Functional/Integration/responses/page_put.json
  packages/page/tests/Unit/Application/DataMapper/NavigationContextDataMapperTest.php
  packages/page/tests/Unit/Application/Merger/NavigationContextMergerTest.php
Labels: Feature

#7844 Remove webspace from PageDimensionContent
  packages/page/src/Application/Normalizer/PageNormalizer.php
  packages/page/src/Domain/Model/PageDimensionContent.php
  packages/page/src/Domain/Model/PageDimensionContentInterface.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/tests/Functional/Integration/responses/page_get.json
  packages/page/tests/Functional/Integration/responses/page_get_ghost_locale.json
  packages/page/tests/Functional/Integration/responses/page_post.json
  packages/page/tests/Functional/Integration/responses/page_post_order.json
  packages/page/tests/Functional/Integration/responses/page_post_publish.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_copy_locale.json
  packages/page/tests/Functional/Integration/responses/page_post_trigger_unpublish.json
  packages/page/tests/Functional/Integration/responses/page_put.json
Labels: Bug

#7788 Remove `module` property of permissions
  UPGRADE.md
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/Entity/Permission.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Permission.orm.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
Labels: Technical Debt, DX

#7759 Remove deprecated `SecurityType`
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/SecurityBundle/Controller/RoleController.php
  src/Sulu/Bundle/SecurityBundle/DataFixtures/ORM/LoadSecurityTypes.php
  src/Sulu/Bundle/SecurityBundle/DataFixtures/security-types.xml
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/SecurityBundle/DependencyInjection/SuluSecurityExtension.php
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Bundle/SecurityBundle/Entity/RoleRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/SecurityType.php
  src/Sulu/Bundle/SecurityBundle/Entity/SecurityTypeRepository.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/SecurityType.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
Labels: Technical Debt, DX

#7753 Remove deprecated `memoize` function
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Component/Cache/Memoize.php
  src/Sulu/Component/Cache/MemoizeInterface.php
  src/Sulu/Component/Cache/Tests/Unit/Cache/MemoizeTest.php
Labels: Technical Debt, DX

#7750 Remove deprecated `UserGroup` feature
  UPGRADE.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/FOSJSRoutingControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Controller/GroupController.php
  src/Sulu/Bundle/SecurityBundle/Entity/Group.php
  src/Sulu/Bundle/SecurityBundle/Entity/GroupRepository.php
  src/Sulu/Bundle/SecurityBundle/Entity/Role.php
  src/Sulu/Bundle/SecurityBundle/Entity/User.php
  src/Sulu/Bundle/SecurityBundle/Entity/UserGroup.php
  src/Sulu/Bundle/SecurityBundle/Entity/UserRepository.php
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Group.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/Role.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/User.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/doctrine/UserGroup.orm.xml
  src/Sulu/Bundle/SecurityBundle/Resources/config/routing_api.yml
  src/Sulu/Bundle/SecurityBundle/Resources/config/services.xml
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/GroupControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/UserControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/Entity/UserRepositoryTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/UserManager/UserManagerTest.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
  src/Sulu/Component/Security/Authentication/RoleInterface.php
  src/Sulu/Component/Security/Tests/Unit/Authorization/SecurityContextVoterTest.php
Labels: Technical Debt, DX

#7853 Fix false unexception error logs in image proxy functionality
  phpstan-baseline.neon
  phpstan.neon
  src/Sulu/Bundle/MediaBundle/Controller/MediaStreamController.php
  src/Sulu/Bundle/MediaBundle/Entity/FileVersion.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/ImageProxyException.php
  src/Sulu/Bundle/MediaBundle/Media/Exception/InvalidMimeTypeForPreviewException.php
  src/Sulu/Bundle/MediaBundle/Media/FormatCache/FormatCacheInterface.php
  src/Sulu/Bundle/MediaBundle/Media/FormatManager/FormatManager.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php
  src/Sulu/Bundle/MediaBundle/Media/Storage/LocalStorage.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaRedirectControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/MediaStreamControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Entity/MediaRepositoryTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/AzureBlobStorageTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/GoogleCloudStorageTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/S3StorageTest.php
Labels: Bug

#7855 Skip ContentRouteProvider in Sulu Page 3.0
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/DependencyInjection/SuluPageExtension.php
  src/Sulu/Bundle/PageBundle/Resources/config/services.xml
  src/Sulu/Bundle/PageBundle/Routing/DecoratedContentRouteProvider.php
Labels: DX

#7835 Add handling for tree_full_edit to disconnect route from parent
  packages/route/src/Infrastructure/Doctrine/EventListener/RouteChangedUpdater.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
  packages/route/tests/Unit/Domain/Model/RouteTest.php
Labels: Feature

#7850 Add compiler pass to decorate ResourceLoaders with an in memory cache
  composer.json
  packages/content/src/Application/ResourceLoader/Loader/CachedResourceLoader.php
  packages/content/src/Infrastructure/Symfony/HttpKernel/Compiler/ResourceLoaderCacheCompilerPass.php
  packages/content/src/Infrastructure/Symfony/HttpKernel/SuluContentBundle.php
  packages/content/tests/Unit/Content/Application/ResourceLoader/CachedResourceLoaderTest.php
  packages/content/tests/Unit/Infrastructure/Symfony/HttpKernel/Compiler/ResourceLoaderCacheCompilerPassTest.php
  packages/content/tests/Unit/Infrastructure/Symfony/HttpKernel/SuluContentBundleTest.php
Labels: Feature, Performance

#7859 Add support using Route Entity for Entities with AutoIncrement Id
  packages/route/src/Domain/Model/Route.php
  packages/route/src/Infrastructure/Doctrine/EventListener/RouteChangedUpdater.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/tests/Functional/Infrastructure/Doctrine/EventListener/RouteChangedUpdaterTest.php
  packages/route/tests/Unit/Domain/Model/RouteTest.php
Labels: Feature, DX

#7863 Remove getId method from preview provider
  packages/content/src/Infrastructure/Sulu/Preview/ContentObjectProvider.php
  packages/content/tests/Unit/Content/Infrastructure/Sulu/Preview/ContentObjectProviderTest.php
  phpstan-baseline.neon
  src/Sulu/Bundle/PageBundle/Preview/PageObjectProvider.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderInterface.php
Labels: DX

#7864 Fix some return type phpstan issues in Behaviours
  phpstan-baseline.neon
  src/Sulu/Component/Content/Document/Behavior/NavigationContextBehavior.php
  src/Sulu/Component/Content/Document/Behavior/WebspaceBehavior.php
Labels: DX

#7865 Fix ObjectProphecy definitions and Sitemap return types
  phpstan-baseline.neon
  src/Sulu/Bundle/HttpCacheBundle/Tests/Unit/EventSubscriber/TagsSubscriberTest.php
  src/Sulu/Bundle/MarkupBundle/Tests/Unit/Listener/SwiftMailerListenerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Manager/MediaManagerTest.php
  src/Sulu/Bundle/PageBundle/Tests/Unit/Document/Subscriber/PublishSubscriberTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Content/SnippetDataProviderTest.php
  src/Sulu/Bundle/SnippetBundle/Tests/Unit/Snippet/SnippetResolverTest.php
  src/Sulu/Bundle/WebsiteBundle/Twig/Sitemap/SitemapTwigExtensionInterface.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/CopyLocaleSubscriberTest.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/ResourceSegmentSubscriberTest.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
  src/Sulu/Component/Media/Tests/Unit/SmartContent/MediaDataProviderTest.php
  src/Sulu/Component/Persistence/Tests/Unit/EventSubscriber/ORM/MetadataSubscriberTest.php
Labels: DX

#7860 Add custom Symfony CMF Dynamic Router / Route Provider to new Route Bundle
  packages/route/src/Application/Routing/Generator/RouteGenerator.php
  packages/route/src/Application/Routing/Generator/RouteGeneratorInterface.php
  packages/route/src/Application/Routing/Generator/SiteRouteGeneratorInterface.php
  packages/route/src/Application/Routing/Matcher/RouteCollectionForRequestLoaderInterface.php
  packages/route/src/Application/Routing/Matcher/RouteCollectionForRequestRouteLoader.php
  packages/route/src/Application/Routing/Matcher/RouteDefaultsProviderInterface.php
  packages/route/src/Application/Routing/Matcher/RouteHistoryDefaultsProvider.php
  packages/route/src/Domain/Exception/MissingRequestContextParameterException.php
  packages/route/src/Domain/Model/Route.php
  packages/route/src/Domain/Value/RequestAttributeEnum.php
  packages/route/src/Infrastructure/Symfony/HttpKernel/SuluRouteBundle.php
  packages/route/src/Infrastructure/SymfonyCmf/Routing/CmfRouteProvider.php
  packages/route/tests/Application/ExampleSiteRouteGenerator.php
  packages/route/tests/Application/Kernel.php
  packages/route/tests/Application/config/config.yml
  packages/route/tests/Application/templates/.gitignore
  packages/route/tests/Functional/Infrastructure/Doctrine/Repository/RouteRepositoryTest.php
  packages/route/tests/Functional/Infrastructure/Symfony/HttpKernel/SuluRouteBundleTest.php
  packages/route/tests/Functional/Infrastructure/SymfonyCmf/Routing/CmfRouteProviderTest.php
  packages/route/tests/Unit/Application/Generator/RouteGeneratorTest.php
  packages/route/tests/Unit/Application/Matcher/RouteCollectionForRequestRouteLoaderTest.php
  packages/route/tests/Unit/Application/Matcher/RouteHistoryDefaultsProviderTest.php
  packages/route/tests/Unit/Domain/Model/RouteTest.php
Labels: Feature

#7868 Update settings resolver to correctly resolve localization urls
  packages/content/config/resolvers.xml
  packages/content/src/Application/ContentResolver/Resolver/SettingsResolver.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/SettingsResolverTest.php
Labels: Feature

#7849 Refactor content resolver to resolve recursively
  packages/content/config/resolvers.xml
  packages/content/src/Application/ContentResolver/ContentResolver.php
  packages/content/src/Application/ContentResolver/ContentResolverInterface.php
  packages/content/src/Application/ContentResolver/Resolver/ExcerptResolver.php
  packages/content/src/Application/ContentResolver/Resolver/ResolverInterface.php
  packages/content/src/Application/ContentResolver/Resolver/SeoResolver.php
  packages/content/src/Application/ContentResolver/Resolver/SettingsResolver.php
  packages/content/src/Application/ContentResolver/Resolver/TemplateResolver.php
  packages/content/src/Application/ContentResolver/Value/ContentView.php
  packages/content/src/Application/ContentResolver/Value/ResolvableResource.php
  packages/content/src/Application/PropertyResolver/Resolver/LinkPropertyResolver.php
  packages/content/src/Application/PropertyResolver/Resolver/TeaserSelectionPropertyResolver.php
  packages/content/src/Application/ResourceLoader/Loader/CachedResourceLoader.php
  packages/content/src/Infrastructure/Sulu/Traits/ResolveContentDimensionUrlTrait.php
  packages/content/tests/Application/config/templates/pages/default_with_page_selection.xml
  packages/content/tests/Unit/Content/Application/ContentResolver/ContentResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/ExcerptResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/SeoResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/SettingsResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Resolver/TemplateResolverTest.php
  packages/content/tests/Unit/Content/Application/ContentResolver/Value/ResolvableResourceTest.php
  packages/page/src/Infrastructure/Sulu/Content/PropertyResolver/PageSelectionPropertyResolver.php
  packages/page/src/Infrastructure/Sulu/Content/PropertyResolver/SinglePageSelectionPropertyResolver.php
  packages/page/src/Infrastructure/Sulu/Content/ResourceLoader/PageResourceLoader.php
  packages/page/tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/PageResourceLoaderTest.php
  packages/snippet/src/Infrastructure/Sulu/Content/PropertyResolver/SingleSnippetSelectionPropertyResolver.php
  packages/snippet/src/Infrastructure/Sulu/Content/PropertyResolver/SnippetSelectionPropertyResolver.php
  packages/snippet/src/Infrastructure/Sulu/Content/ResourceLoader/SnippetResourceLoader.php
  packages/snippet/tests/Unit/Infrastructure/Sulu/Content/ResourceLoader/SnippetResourceLoaderTest.php
  phpstan-baseline.neon
  phpstan.dist.neon
  src/Sulu/Bundle/ContactBundle/Infrastructure/Sulu/Content/PropertyResolver/ContactAccountSelectionPropertyResolver.php
  src/Sulu/Bundle/MediaBundle/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolver.php
  src/Sulu/Bundle/MediaBundle/Infrastructure/Sulu/Content/PropertyResolver/MediaSelectionPropertyResolver.php
  src/Sulu/Bundle/MediaBundle/Infrastructure/Sulu/Content/PropertyResolver/SingleMediaSelectionPropertyResolver.php
Labels: Feature

#7869 Add navigation twig extension for Sulu 3.0
  packages/page/src/Domain/Model/Page.php
  packages/page/src/Domain/Repository/NavigationRepositoryInterface.php
  packages/page/src/Domain/Repository/PageRepositoryInterface.php
  packages/page/src/Infrastructure/Doctrine/Repository/NavigationRepository.php
  packages/page/src/Infrastructure/Doctrine/Repository/PageRepository.php
  packages/page/src/Infrastructure/Sulu/Admin/PageAdmin.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/src/Infrastructure/Symfony/Twig/Extension/NavigationTwigExtension.php
  src/Sulu/Bundle/PageBundle/DependencyInjection/Compiler/SuluNextPageCompilerPass.php
  src/Sulu/Bundle/PageBundle/SuluPageBundle.php
Labels: Feature

#7872 Fix UserProvider PHPStan Generic update for PasswordUpgraderInterface
  src/Sulu/Bundle/SecurityBundle/User/UserProvider.php
Labels: DX

#7871 Mark most preview specific service as internal
  UPGRADE.md
  packages/content/tests/Application/PreviewKernelFactory.php
  packages/content/tests/Application/config/config_admin.yml
  phpstan-baseline.neon
  src/Sulu/Bundle/PreviewBundle/Admin/PreviewAdmin.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/DependencyInjection/SuluPreviewExtension.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/EventSubscriber/CacheCommandSubscriber.php
  src/Sulu/Bundle/PreviewBundle/Infrastructure/Symfony/Security/PreviewVoter.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderRegistry.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderRegistryInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewCacheItem.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/KernelFactoryInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewKernel.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRendererInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/WebsiteKernelFactory.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Infrastructure/Symfony/EventSubscriber/CacheCommandSubscriberTest.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/Renderer/PreviewRendererTest.php
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/UserInterface/Controller/PreviewControllerTest.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewLinkController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PublicPreviewController.php
Labels: DX

#7867 Prepare Preview for new Route Bundle implemention
  packages/content/tests/Unit/Content/Infrastructure/Sulu/Admin/ContentViewBuilderFactoryTest.php
  phpstan-baseline.neon
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderRegistry.php
  src/Sulu/Bundle/PreviewBundle/Preview/Object/PreviewObjectProviderRegistryInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Preview.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewCacheItem.php
  src/Sulu/Bundle/PreviewBundle/Preview/PreviewContext.php
  src/Sulu/Bundle/PreviewBundle/Preview/Provider/PreviewDefaultsProviderInterface.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRenderer.php
  src/Sulu/Bundle/PreviewBundle/Preview/Renderer/PreviewRendererInterface.php
  src/Sulu/Bundle/PreviewBundle/Resources/config/services.xml
  src/Sulu/Bundle/PreviewBundle/Tests/Unit/Preview/PreviewTest.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PreviewController.php
  src/Sulu/Bundle/PreviewBundle/UserInterface/Controller/PublicPreviewController.php
Labels: Feature

#7873 Remove old Content Sitemap Provider services
  packages/article/src/Infrastructure/Sulu/Content/ArticleSitemapProvider.php
  packages/article/src/Infrastructure/Symfony/HttpKernel/SuluArticleBundle.php
  packages/content/src/Infrastructure/Sulu/Sitemap/ContentSitemapProvider.php
  packages/content/tests/Application/ExampleTestBundle/Resources/config/services.yaml
  packages/content/tests/Functional/Infrastructure/Sulu/Sitemap/ContentSitemapProviderTest.php
  packages/content/tests/Functional/Infrastructure/Sulu/Sitemap/snapshots/sitemap.json
  packages/page/src/Infrastructure/Sulu/Content/PageSitemapProvider.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
Labels: DX
