Repository sulu/sulu, pull requests merged in 2025-06, with the labels that each got.

#7984 Replace form metadata name property with key property
  UPGRADE-3.x.md
  packages/content/tests/Unit/Content/Application/ContentDataMapper/DataMapper/RoutableDataMapperTest.php
  packages/content/tests/Unit/Content/Application/ContentDataMapper/DataMapper/TemplateDataMapperTest.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/Resolver/BlockPropertyResolverTest.php
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/PropertiesXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/default.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Controller/fixtures/overview.json
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Validation/BlockFieldMetadataValidatorTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Validation/TypesPropertyFieldMetadataValidatorTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/collection_details.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/media_details.json
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/ImageMapContentTypeTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/ImageMapPropertyResolverTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Metadata/ImageMapFieldMetadataValidatorTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/snapshots/role_details.json
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/snapshots/user_details.json
  src/Sulu/Component/Content/SmartContent/PageDataProvider.php
  src/Sulu/Component/Content/Tests/Unit/SmartContent/PageDataProviderTest.php
  src/Sulu/Component/Content/Tests/Unit/Types/Metadata/GlobalBlocksTypedFormMetadataVisitorTest.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  src/Sulu/Component/Content/Types/Metadata/GlobalBlocksTypedFormMetadataVisitor.php
Labels: Technical Debt

#7985 Fix block visitors settings access
  packages/content/src/Application/PropertyResolver/BlockVisitor/HiddenBlockVisitor.php
  packages/content/src/Application/PropertyResolver/BlockVisitor/ScheduleBlockVisitor.php
  packages/page/src/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/SegmentBlockVisitor.php
  src/Sulu/Bundle/AudienceTargetingBundle/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/TargetGroupBlockVisitor.php
Labels: Bug

#7987 Add parsing of template metadata
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/TemplateXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/SchemaXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/TemplateXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TemplateMetadata.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/overview.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Loader/TemplateXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Parser/TemplateXmlParserTest.php
Labels: Technical Debt

#7989 Use new metadata for Preview ContentObjectProvider
  packages/article/src/Infrastructure/Symfony/HttpKernel/SuluArticleBundle.php
  packages/content/src/Infrastructure/Sulu/Preview/ContentObjectProvider.php
  packages/content/tests/Application/ExampleTestBundle/Resources/config/services.yaml
  packages/content/tests/Unit/Content/Infrastructure/Sulu/Admin/ContentViewBuilderFactoryTest.php
  packages/content/tests/Unit/Content/Infrastructure/Sulu/Preview/ContentObjectProviderTest.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
Labels: Technical Debt

#7993 Remove old compat structure node events
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Bundle/PageBundle/Resources/config/document.xml
  src/Sulu/Component/Content/Document/Subscriber/Compat/ContentMapperSubscriber.php
  src/Sulu/Component/Content/Mapper/ContentEvents.php
  src/Sulu/Component/Content/Mapper/ContentMapper.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeDeleteEvent.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeEvent.php
  src/Sulu/Component/Content/Mapper/Event/ContentNodeOrderEvent.php
  src/Sulu/Component/Content/Tests/Unit/Document/Subscriber/Compat/ContentMapperSubscriberTest.php
Labels: Technical Debt

#7994 Remove old metadata usage in webspace manager service
  UPGRADE-3.x.md
  src/Sulu/Bundle/CoreBundle/Resources/config/webspace.xml
  src/Sulu/Component/Webspace/Manager/WebspaceManager.php
  src/Sulu/Component/Webspace/Tests/Unit/Manager/WebspaceManagerTest.php
Labels: Technical Debt

#7512 Migrate rest routings to default symfony routing files of AdminBundle
  config/routes/sulu_admin.yaml
  src/Sulu/Bundle/AdminBundle/Resources/config/routing.yaml
  src/Sulu/Bundle/AdminBundle/Resources/config/routing.yml
  src/Sulu/Bundle/AdminBundle/Resources/config/routing_api.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/CategoryBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/TagBundle/Tests/Application/config/routing.yml
Labels: DX

#7514 Migrate rest routings to default symfony routing files of TrashBundle
  config/routes/sulu_admin.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/TrashBundle/Resources/config/routing_api.yaml
  src/Sulu/Bundle/TrashBundle/Tests/Application/config/routing.yml
Labels: DX

#7516 Migrate rest routings to default symfony routing files of SearchBundle
  config/routes/sulu_admin.yaml
  config/routes/sulu_website.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_website.yml
  src/Sulu/Bundle/SearchBundle/Resources/config/routing.yaml
  src/Sulu/Bundle/SearchBundle/Resources/config/routing_website.yaml
  src/Sulu/Bundle/SearchBundle/Tests/Application/config/routing.yml
Labels: DX

#7526 Migrate rest routings to default symfony routing files of PreviewBundle
  config/routes/sulu_admin.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/PreviewBundle/Resources/config/routing.yaml
  src/Sulu/Bundle/PreviewBundle/Resources/config/routing_api.yaml
  src/Sulu/Bundle/PreviewBundle/Resources/config/routing_public.yaml
  src/Sulu/Bundle/PreviewBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
Labels: DX

#8001 Migrate rest routings to default symfony routing files of ContactBundle
  config/routes/sulu_admin.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/ContactBundle/Resources/config/routing_api.yaml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
Labels: Technical Debt

#8004 Migrate rest routings to default symfony routing files of MediaBundle
  config/routes/sulu_admin.yaml
  config/routes/sulu_website.yaml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing.yaml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_api.yaml
  src/Sulu/Bundle/MediaBundle/Resources/config/routing_website.yaml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_website.yml
  src/Sulu/Bundle/PageBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SearchBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SecurityBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/SnippetBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/routing_website.yml
Labels: Technical Debt

#8016 Remove missed rest route definitions
  config/routes/sulu_admin.yaml
  src/Sulu/Bundle/ContactBundle/Tests/Application/config/routing.yml
  src/Sulu/Bundle/MediaBundle/Tests/Application/config/routing_admin.yml
  src/Sulu/Bundle/ReferenceBundle/Tests/Application/config/routing.yml
Labels: Technical Debt
