Repository sulu/sulu, pull requests merged in 2025-05, with the labels that each got.

#7934 Add template metadata to form metadata
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/CacheLifetimeMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TemplateMetadata.php
Labels: Technical Debt

#7908 Move sulu core structure config to sulu admin config
  packages/article/src/Infrastructure/Symfony/HttpKernel/SuluArticleBundle.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/snippet/src/Infrastructure/Symfony/HttpKernel/SuluSnippetBundle.php
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/DependencyInjection/Configuration.php
  src/Sulu/Bundle/AdminBundle/DependencyInjection/SuluAdminExtension.php
Labels: Technical Debt

#7935 Remove usage of LocalizedFormMetadataCollection
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/LocalizedFormMetadataCollection.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/XmlFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Component/Content/Metadata/Loader/AbstractLoader.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
Labels: Technical Debt

#7937 Move FormXmlLoader to new metadata namespace
  packages/content/src/Infrastructure/Symfony/HttpKernel/Compiler/SettingsFormPass.php
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/XmlFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Loader/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Validation/BlockFieldMetadataValidatorTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Validation/ChainFieldMetadataValidatorTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Validation/TypesPropertyFieldMetadataValidatorTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/data/form_invalid_root_tag.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/dummy-forms/dummy-form.xml
Labels: Technical Debt

#7938 Add resources to new form metadata
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/FormXmlLoader.php
Labels: Technical Debt

#7939 Rename PropertiesXmlParser to DeprecatedPropertiesXmlParser
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/DeprecatedPropertiesXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/XmlParserTrait.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Loader/FormXmlLoaderTest.php
  src/Sulu/Bundle/PageBundle/Resources/config/structure.xml
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Factory/StructureMetadataFactoryTest.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
Labels: Technical Debt

#7900 Fix passing null to non-nullable argument in UserManager
  src/Sulu/Bundle/SecurityBundle/Tests/Unit/UserManager/UserManagerTest.php
  src/Sulu/Bundle/SecurityBundle/UserManager/UserManager.php
Labels: Bug

#7959 Update phpstan baseline
  phpstan-baseline.neon
Labels: Technical Debt

#7877 Add block visitors for new content storage
  packages/content/config/resolvers.xml
  packages/content/src/Application/PropertyResolver/BlockVisitor/BlockVisitorInterface.php
  packages/content/src/Application/PropertyResolver/BlockVisitor/HiddenBlockVisitor.php
  packages/content/src/Application/PropertyResolver/BlockVisitor/ScheduleBlockVisitor.php
  packages/content/src/Application/PropertyResolver/Resolver/BlockPropertyResolver.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/BlockVisitor/HiddenBlockVisitorTest.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/BlockVisitor/ScheduleBlockVisitorTest.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/PropertyResolverProviderTest.php
  packages/content/tests/Unit/Content/Application/PropertyResolver/Resolver/BlockPropertyResolverTest.php
  packages/page/src/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/SegmentBlockVisitor.php
  packages/page/src/Infrastructure/Symfony/HttpKernel/SuluPageBundle.php
  packages/page/tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/SegmentBlockVisitorTest.php
  phpstan-baseline.neon
  src/Sulu/Bundle/AudienceTargetingBundle/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/TargetGroupBlockVisitor.php
  src/Sulu/Bundle/AudienceTargetingBundle/Resources/config/services.xml
  src/Sulu/Bundle/AudienceTargetingBundle/Tests/Unit/Infrastructure/Sulu/Content/PropertyResolver/BlockVisitor/TargetGroupBlockVisitorTest.php
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
Labels: Feature

#7963 Use snapshots for security and media metadata tests
  phpstan-baseline.neon
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/AdminControllerTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/collection_details.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/form_image.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/form_images.json
  src/Sulu/Bundle/MediaBundle/Tests/Functional/Controller/snapshots/media_details.json
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/AdminControllerTest.php
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/snapshots/role_details.json
  src/Sulu/Bundle/SecurityBundle/Tests/Functional/snapshots/user_details.json
  src/Sulu/Bundle/TestBundle/Testing/AssertSnapshotTrait.php
Labels: Technical Debt

#7966 Fixing pubic flysystem urls
  UPGRADE-3.x.md
  src/Sulu/Bundle/MediaBundle/Media/Storage/FlysystemStorage.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Media/Storage/FlysystemStorageTest.php
Labels: Bug

#7943 Add new properties parser which returns new metadata for sulu form xmls
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/FormMetadata/FormMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FieldMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/FormMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/ItemMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/PropertiesXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Parser/TagXmlParser.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/SchemaMetadataProvider.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/StructureFormMetadataLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/TagMetadata.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadataMapperInterface.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadataMapperRegistry.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/PropertyMetadataMinMaxValueResolver.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/SelectionPropertyMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/SingleSelectionPropertyMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/SchemaMetadata/TextPropertyMetadataMapper.php
  src/Sulu/Bundle/AdminBundle/Metadata/XmlParserTrait.php
  src/Sulu/Bundle/AdminBundle/Resources/config/services.xml
  src/Sulu/Bundle/AdminBundle/Tests/Application/config/forms/form_with_blocks.xml
  src/Sulu/Bundle/AdminBundle/Tests/Functional/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/FormMetadata/FormMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/FieldMetadataTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/FormMetadataTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/Loader/FormXmlLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/PropertyMetadataMinMaxValueResolverTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/SelectionPropertyMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/SingleSelectionPropertyMetadataMapperTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/SchemaMetadata/TextPropertyMetadataMapperTest.php
  src/Sulu/Bundle/CoreBundle/Resources/config/content.xml
  src/Sulu/Bundle/MediaBundle/Content/Types/ImageMapContentType.php
  src/Sulu/Bundle/MediaBundle/Content/Types/MediaSelectionContentType.php
  src/Sulu/Bundle/MediaBundle/Content/Types/SingleMediaSelection.php
  src/Sulu/Bundle/MediaBundle/Resources/config/services.xml
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/ImageMapContentTypeTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/MediaSelectionContentTypeTest.php
  src/Sulu/Bundle/MediaBundle/Tests/Unit/Content/Types/SingleMediaSelectionTest.php
  src/Sulu/Bundle/PageBundle/Content/Types/Email.php
  src/Sulu/Bundle/PageBundle/Teaser/TeaserContentType.php
  src/Sulu/Bundle/RouteBundle/Content/Type/PageTreeRouteContentType.php
  src/Sulu/Bundle/RouteBundle/Tests/Functional/Content/PageTreeRouteContentTypeTest.php
  src/Sulu/Component/Content/Metadata/Loader/AbstractLoader.php
  src/Sulu/Component/Content/Tests/Unit/Block/BlockContentTypeTest.php
  src/Sulu/Component/Content/Tests/Unit/Types/NumberTest.php
  src/Sulu/Component/Content/Types/BlockContentType.php
  src/Sulu/Component/Content/Types/Number.php
Labels: Technical Debt

#7967 Move AbstractLoader to Admin Bundle
  UPGRADE-3.x.md
  phpstan-baseline.neon
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/AbstractLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/FormMetadata/Loader/FormXmlLoader.php
  src/Sulu/Bundle/AdminBundle/Metadata/XmlParserTrait.php
  src/Sulu/Bundle/AdminBundle/Resources/config/schema/form-1.0.xsd
  src/Sulu/Bundle/AdminBundle/Resources/config/schema/properties-1.0.xsd
  src/Sulu/Bundle/AdminBundle/Resources/config/schema/schema-1.0.xsd
  src/Sulu/Bundle/AdminBundle/Resources/config/schema/template-1.0.xsd
  src/Sulu/Bundle/AdminBundle/Resources/config/schema/xml.xsd
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/StructureFormMetadataLoaderTest.php
  src/Sulu/Bundle/AdminBundle/Tests/Unit/Metadata/FormMetadata/XmlFormMetadataLoaderTest.php
  src/Sulu/Component/Content/Metadata/Loader/StructureXmlLoader.php
  src/Sulu/Component/Content/Tests/Unit/Metadata/Loader/StructureXmlLoaderTest.php
Labels: Technical Debt

#7965 Fix IcomoonProvider warning
  src/Sulu/Bundle/AdminBundle/Icon/providers/IcomoonProvider.php
Labels: Bug
